### ISSUE TITLE
Remove mislabelled Data Created field from resource view page templates

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#100]
On the resource view pages - ({domain}/dataset/dataset-name/resource/...) the field labelled Data Created - is actually the date the package/record was published. It should be removed from the resource view page templates.

**Comment by gjlawran** [comment]
Simplifying and  narrowing focus of these issues.

**Comment by Mbrownshoes** [comment]
I'm not entirely sure what was changed here. i don't see a 'Date Created' field on the resource page  or either Cat or Cad. I do see a 'created' field on the resource_show page (https://cad.data.gov.bc.ca/api/3/action/resource_show?id=87051364-3f4c-4b54-bee4-957cd02fe0df). 
Perhaps this change was made for a previous release?
