### ISSUE TITLE
resource_update for larger files results in duplicate rows to datastore resources

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#102]
Using *resource_update* of the [FileStore API](http://docs.ckan.org/en/latest/maintaining/filestore.html) to replace larger files results in duplicate rows in DataStore resources after DataPusher completes update.

See CITZEDC-819

**Comment by jrods** [comment]
@gjlawran @ll911 @Mbrownshoes  I need more information on what the statstrack and the exporter script is doing. What is the process? Which exporter script?

**Comment by gjlawran** [comment]
This ticket should not be initiated until 1.4.0 is delivered to production.

**Comment by kfishwick** [comment]
Can we please get an answer now to @jrods  question above?

**Comment by gjlawran** [comment]
The DataStore version of this CSV resource  - https://catalogue.data.gov.bc.ca/dataset/bc-data-catalogue-content/resource/4b721abc-46e0-4010-b366-5830c000eb56  - showed double the number of records that the CSV file held.  A manual update of the DataStore was initiated 2016/08/15  - and the resource now has  1468  entries - matching the number of records in the Filestore. @Mbrownshoes  will confirm this is resolved  with other resources .

**Comment by Mbrownshoes** [comment]
@jrods the exporter script updates the content of the https://catalogue.data.gov.bc.ca/dataset/bc-data-catalogue-content resources. The statstrack job updates uses google analytics data to update the site-usage pages (https://catalogue.data.gov.bc.ca/data/site-usage/dataset). It also runs the index rebuild command.
Here's the three paster commands it uses:
paster --plugin=ckan tracking update 
paster --plugin=ckanext-ga-report loadanalytics latest
paster --plugin=ckan search-index rebuild_fast

**Comment by Mbrownshoes** [comment]
This doesn't seem to be an issue any more. Closing.
