### ISSUE TITLE
Geographic data extraction API testing

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#104]
Conduct testing against OFI (Order Fulfiller Interface) to confirm it meets requirements for use in next sprint. Provide feedback to TL by July 18.

Related tickets include CITZEDC-608, CITZEDC-732, CITZEDC-733,

**Comment by kfishwick** [comment]
This is not a deliverable, just preliminary analysis on the existing delivery version of the API.

**Comment by gjlawran** [comment]
Awaiting response from vendor on questions regarding AOI and UIDs.  gjlawran needs to develop preliminary wireframes.
