### ISSUE TITLE
Test and Delivery are loading very slowly

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#110]
When logged in as an editor in test or delivery and change the ‘Order by’ field from ‘published date’  the page is taking >10 s to load. This is not observed in Prod, where the page loads in ~2 s. 

This is a critical issue with the 1.3 release. @gjlawran @ll911 @Darv72

**Comment by kfishwick** [comment]
Is this still an issue @Mbrownshoes

**Comment by gjlawran** [comment]
This is resolve in production. Closing.
