### ISSUE TITLE
email notifications not being sent

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#111]
In test and delivery email notifications are not being sent to organization's editors/admin when a record's state is moved to pending publish from draft. 

Here is the log.

[pid: 24147|app: 0|req: 10/18] 142.34.140.32 () {48 vars in 752 bytes} [Thu Jul  7 13:32:29 2016] POST /api/3/action/resource_show => generated 1159 bytes in 62 msecs (HTTP/1.1 200) 4 headers in 130 bytes (1 switches on core 5)
u'<p>As a BC Data Catalogue admin for the Ministry of Jobs, Tourism and Skills Training - DataBC, please be advised that the publication state of this record: <a href="https://cat.data.gov.bc.ca/dataset/autotest-geographic269">https://cat.data.gov.bc.ca/dataset/autotest-geographic269</a> is now "PENDING PUBLISH".<br><br>If you are no longer an admin for Ministry of Jobs, Tourism and Skills Training - DataBC or if you have a question or concern regarding this message please contact DataBC Catalogue Services <a href="&quot;mailto:datacat@gov.bc.ca">datacat@gov.bc.ca</a> .<br><br>Thanks.</p>'
[pid: 24147|app: 0|req: 11/19] 142.34.140.32 () {58 vars in 2799 bytes} [Thu Jul  7 13:32:28 2016] POST /dataset/edit/autotest-geographic269 => generated 303 bytes in 1442 msecs (HTTP/1.1 302) 5 headers in 198 bytes (1 switches on core 2)
Exception in thread Thread-8:
Traceback (most recent call last):
 File "/s00/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
   self.run()
 File "/s00/lib64/python2.7/threading.py", line 763, in run
   self.__target(*self.__args, **self.__kwargs)
 File "/tmp/bcdcsrc/src/ckanext-bcgov/ckanext/bcgov/logic/action.py", line 234, in check_record_state
   send_state_change_notifications(members, email_dict, site_title, site_url)
 File "/tmp/bcdcsrc/src/ckanext-bcgov/ckanext/bcgov/logic/action.py", line 119, in send_state_change_notifications
   raise MailerException("SMTP server does not support STARTTLS")
MailerException: SMTP server does not support STARTTLS

**Comment by ll911** [comment]
fixed by update smtp.starttls = false
