### ISSUE TITLE
layout bug in iPhone 5

### ISSUE THREAD

**Issue by ll911** [bcgov/ckanext-bcgov#115]
extra blue stripe on the right side screen and class "icon-sitemap" should be in hamburger menu
see screen attached 
![img_3490](https://cloud.githubusercontent.com/assets/11949273/16774674/f042c8c2-4811-11e6-86fa-d7d99696ccf8.PNG)

**Comment by Mbrownshoes** [comment]
It appear this is only a bug for geographic records with an object name.
