### ISSUE TITLE
Recording and displaying last date of upload for filestore resources

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#117]
As a user, I would like to know when the file resources were uploaded into the data catalogue so that I know how current they are. This should be displayed on the resource show page and possibly on the package page if it can fit.

Background:
The core resource_show API call indicates the following elements are present in the response **last_modified:** , **cache_last_updated:** ,** webstore_last_updated:**  however they are all NULL.

Core CKAN - is also not populating these fields for a resource http://demo.ckan.org/api/3/action/resource_show?id=b36d7da2-8a9e-4912-8f2b-b58c29a847ef

UK is using Archiver and QA extensions and recording dates within nested objects
https://data.gov.uk/api/3/action/resource_show?id=2ac8abba-4a71-4f12-af1b-57ad0e36b6a4

There  seems to have been lots of discussion about this issue - as it pertained to the DataStore - https://github.com/ckan/ckan/pull/2519 - it would also be helpful to know when the DataStore was last updated for a resource.  How is this determined? 

Before we use one of the above referenced element to refer to the date the last time the file resource was uploaded we should confirm how these are used in the code. 

Certainly the date of updates for resource record revisions are being tracked - although they may not be being displayed by the resource_show API call.

**Comment by jrods** [comment]
For the example on the ckan demo site, I'm not sure why it doesn't have last_modified set. As of ckan 2.4, each resource that's created/updated with an upload file, will have a last_modified timestamp. 

If last_modified doesn't exist in the metadata, what should be displayed? Unknown or nothing? This is to deal with resources that have been uploaded before the feature was included.

Should the timestamp for created be displayed as well?

Also, what is it meant by, displayed on the package view? As far as I can tell, there's Record Last Modified already in Metadata Information for Datasets.

**Comment by Mbrownshoes** [comment]
@jrods looks like it is being populated in Prod https://catalogue.data.gov.bc.ca/api/3/action/resource_show?id=1145c623-ff97-4383-adf5-2a12e9020ce7
and in CAT (1.5) https://cat.data.gov.bc.ca/api/3/action/resource_show?id=45fd1d70-8c5e-464e-8599-724451a19bc0

'last_modified' is also displayed for each resource on package_show so we're good there: https://catalogue.data.gov.bc.ca/api/3/action/package_show?id=42f7ca99-e7f3-40f7-93d7-f2500cccc315. Currently 'null' is displayed for resources that haven't been updated since the change, which is fine. 

I think the 'created' field should continue to be displayed, as it currently is.

**Comment by jrods** [comment]
@Mbrownshoes What should be added/changed for the web view?
Currently for datasets, Record Published and Record Last Modified are displayed. As for resources, Data Published displays, just have Last Modified display under it?

**Comment by Mbrownshoes** [comment]
@jrods Yes, let's just add 'Resource Last Modified' with the last_modified date at the resource view, just under 'Date Published'
