### ISSUE TITLE
Rename resource storage location names or have this auto-populate

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#118]
New editors often don't know what to select for 'Resource Storage Location'. Changing EDC Data Store to 'Catalogue File/Data Store' might be more helpful. Ideally, this should be automatic - if a file is uploaded this should be auto-populated. Same if the data is stored on an ftp site (external) or the link is set to pub.data.

**Comment by gjlawran** [comment]
We will remove this field from the interface under https://github.com/bcgov/ckanext-bcgov/issues/148
