### ISSUE TITLE
Displaying size of data resources

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#119]
As a user I would like to know the size of a file before I attempt to download it. When a file is uploaded to the FileStore record the size of the file in bytes and present in kB or MB depending upon size.

In the case of a compressed file the size presented will be the compressed file size **not** the size of the original expanded file.

When a file is presented from an external location (not in the filestore) allow the user to add/edit the filesize value. 

Note a **SIZE:** element is already returned by the core resource_show API action, 

Please review the [Archiver extension](https://github.com/ckan/ckanext-archiver) for patterns / code that may be reused. Sample implementation: https://data.gov.uk/api/3/action/resource_show?id=a6b2434f-3730-4a2e-86fd-d197392fbfa8 , https://data.gov.uk/dataset/monthly-land-registry-property-transaction-data

Please review and consider adding this to core - CKAN https://github.com/ckan/ckan/issues/1517

**Comment by kfishwick** [comment]
This would be a really good contribution, please assume it doesn't exist (read issue https://github.com/ckan/ckan/issues/1517)

UK has fixed this & contributed if you want to review their solution.

**Comment by gjlawran** [comment]
@kfishwick I don't believe UK has fixed this - they are using the  ARCHIVER extension - that is recording a resource_timestamp, etag, hash, mime-type and size - which could potentially be used - or this functionality could be brought into core

**Comment by kfishwick** [comment]
Thanks @gjlawran  actually @jrods has already made a pull request to core and is working through the solution.  https://github.com/ckan/ckan/pull/3205

**Comment by jrods** [comment]
@gjlawran where do you want the size of the resource to show on the page?

**Comment by kfishwick** [comment]
@gjlawran  and @Mbrownshoes  I would like to split out the manual edit/override of the size value, its a little more complicated.  Can you make a new ticket and we can schedule it when we have time?  Just leave this ticket for the core fix of detecting & storing the size of resources uploaded to the filestore.

**Comment by kfishwick** [comment]
(we still need an answer for @jrods  question above, where do you want to view the size of the resource record on the page - right now its available in the resource view API only)

**Comment by ll911** [comment]
@gjlawran @kfishwick @Mbrownshoes I vote against allow manual overwrite the size for resource. it should be either a computed value or n/a

**Comment by Mbrownshoes** [comment]
I think the size values should go next to the resource name, in brackets,  similar to https://data.gov.uk/dataset/monthly-land-registry-property-transaction-data

![screen shot 2016-08-25 at 9 34 59 am](https://cloud.githubusercontent.com/assets/3362533/17977694/9db9cbf6-6aa7-11e6-9b42-2478cdff22f3.png)

**Comment by jrods** [comment]
@Mbrownshoes what do you want to do for resources (linked data) that have 0 bytes, display or not?
<img width="940" alt="screen shot 2016-08-25 at 12 18 21 pm" src="https://cloud.githubusercontent.com/assets/5874122/17982732/1ab98018-6abe-11e6-91c8-1d5e16c2acec.png">

**Comment by ll911** [comment]
I think it should display (external link) for those resources

**Comment by kfishwick** [comment]
I think we should just hide the entire string between ( ) if it is zero.  Thats the current behaviour.

**Comment by Mbrownshoes** [comment]
Yes, lets hide if the resource isn't an actual file. We could display 'external link' for those files held externally (ftp,pub.data).

**Comment by Mbrownshoes** [comment]
It looks like resources have to be re-uploaded to the filestore in order to have the file size posted. I'm guessing there's not an easy way around this, or is there?

**Comment by jrods** [comment]
@Mbrownshoes a script could be made to utilize the api and update each resource accordingly. But one problem I can see is that for 'resource_update', it needs a data file to be present for the resource's metadata (size and mimetype in this case) to be updated. I don't know if just giving the exact same data file that's on the server will cause duplicates or not. There could be some workarounds if that's the case, more analysis and testing will be needed for a script to be made.

But before going ahead with this, I suggest waiting till ckan/ckan#3205 is merged into core.

**Comment by Mbrownshoes** [comment]
@jrods is it possible to just remove the empty '()', so nothing is there, until the resource has been updated?
