### ISSUE TITLE
Upgrade to CKAN 2.5.2

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#121]
As many issues associated with the DataStore and DataPusher, and updates to the authorization process have been made over the course of 2.3 > 2.5 - the 1.4.0 release will focus on upgrading from CKAN 2.3.4 to 2.5.2 .  This will also put us into a better position to more easily contribute to core.

**Comment by ll911** [comment]
it appears ckan org using solr 4.8.1 and postgresql 9.3 for ckan-2.5.2, should we downgrade solr and upgrade postgresql to match the same version? https://github.com/ckan/ckan/tree/ckan-2.5.2/contrib/docker

**Comment by jrods** [comment]
Maybe could asked on the ckan irc or mailing list to see if the versions we're running of postgres and solr are ok to continue use with ckan 2.5.2?

**Comment by gjlawran** [comment]
We can - but we are hoping the SOLR upgrade is going to resolve a couple of existing issues - so we should proceed with that at the minimum. Is there a reason why we would skip the PG upgrade? We haven't done it for awhile.

**Comment by gjlawran** [comment]
@ll911  looks like the latest install recommends Ubuntu - with latest installs of PG and SOLR - http://docs.ckan.org/en/latest/maintaining/installing/install-from-package.html  - that Dockerfile needs an update it is 2 years old

**Comment by jrods** [comment]
I have tested and updated the vagrant env to use ckan 2.5.2. Using @Khalegh-H3 changes in vagrant env, everything is good. I will create the PR to the branch with the new changes.

However one problem with the vagrant env, I can't push my changes to svn repo for bcdc-vagrant @ll911.

**Comment by ll911** [comment]
Isn't the vagrant source under bcdc-devops repo in GH?

Sent from Mobile




On Mon, Jul 25, 2016 at 4:47 PM -0700, "Jared Smith" <notifications@github.com<mailto:notifications@github.com>> wrote:


I have tested and updated the vagrant env to use ckan 2.5.2. Using @Khalegh-H3<https://github.com/Khalegh-H3> changes in vagrant env, everything is good. I will create the PR to the branch with the new changes.

However one problem with the vagrant env, I can't push my changes to svn repo for bcdc-vagrant @ll911<https://github.com/ll911>.

-

**Comment by jrods** [comment]
The bcdc-devops repo only has vanilla ckan and data-fp @ll911

**Comment by jrods** [comment]
The svn repo for the vagrant env now has the updated changes.

I will now update the change log with the necessary steps to preform the upgrade in delivery.

**Comment by jrods** [comment]
### Upgrade to Ckan 2.5.2 instructions
1. Preform the necessary backup of all data
	- db, datastore, uploads, etc.

2. Install Ckan from pip
		pip install ckan==2.5.2

3. Before installing ckanext-googleanalytics, comment out authz import
		sed -i 's/from ckan.model.authz/#from ckan.model.authz/' /apps/ckan/dlv/src/ckanext-googleanalytics/ckanext/googleanalytics/dbutil.py

4. Upgrade the `bleach` module
		pip install bleach --upgrade

5. Upgrade the DB
	- run paster command to upgrade the db
		paster --plugin=ckan db upgrade -c /etc/ckan/dlv/edcdlv.ini	

6. Update the Solr schema
	- should be included with the ckan install

7. Rebuild the Solr Index
	- run paster command to re-index solr
		paster --plugin=ckan search-index rebuild -c /etc/ckan/dlv/edcdlv.ini

**Comment by ll911** [comment]
If authz section not required for googleanalytic extension, can you make the changes in our forked repo instead of altering the code in runtime?

Sent from Mobile




On Tue, Jul 26, 2016 at 12:35 PM -0700, "Jared Smith" <notifications@github.com<mailto:notifications@github.com>> wrote:

Upgrade to Ckan 2.5.2 instructions

  1.  Preform the necessary backup of all data

     *   db, datastore, uploads, etc.
  2.  Install Ckan from pip
pip install ckan==2.5.2

  3.  Before installing ckanext-googleanalytics, comment out authz import
sed -i 's/from ckan.model.authz/#from ckan.model.authz/' /apps/ckan/dlv/src/ckanext-googleanalytics/ckanext/googleanalytics/dbutil.py

  4.  Upgrade the bleach module
pip install bleach --upgrade

  5.  Upgrade the DB

     *   run paster command to upgrade the db paster --plugin=ckan db upgrade -c /etc/ckan/dlv/edcdlv.ini
  6.  Update the Solr schema

     *   should be included with the ckan install
  7.  Rebuild the Solr Index

     *   run paster command to re-index solr paster --plugin=ckan search-index rebuild -c /etc/ckan/dlv/edcdlv.ini

-

**Comment by jrods** [comment]
Yes, I can submit a PR to the bcgov's version of googleanalytics to include the fix.

**Comment by ll911** [comment]
Thx Jared, also for Python module bleach, isn't the new required version included as part of ckan-2.5.2 requirement.txt? Shouldn't we just stick to that version instead? Why need upgrade on top of the requirement.txt ?

Sent from Mobile




On Tue, Jul 26, 2016 at 12:43 PM -0700, "Jared Smith" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, I can submit a PR to the bcgov's version of googleanalytics to include the fix.

-

**Comment by jrods** [comment]
@ll911 It is but from my testing in the vagrant env, it still throws an error when trying to run ckan, even after running the requirements.txt.

**Comment by ll911** [comment]
@jrods you mean 1.4.2 included in https://github.com/ckan/ckan/blob/ckan-2.5.2/requirements.txt not working?

**Comment by ll911** [comment]
@jrods created 2.5.3-bcgov branch for recline map fixes https://github.com/bcgov/ckan/tree/2.5.3-bcgov 

got following error when run paster db upgrade after switching to 2.5.2/2.5.3-bcgov
`paster --plugin=ckan db upgrade -c ckan.ini
Traceback (most recent call last):
  File "/apps/ckan/dlv/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/apps/ckan/dlv/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/apps/ckan/dlv/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/apps/ckan/dlv/src/ckan/ckan/lib/cli.py", line 205, in command
    self._load_config(cmd!='upgrade')
  File "/apps/ckan/dlv/src/ckan/ckan/lib/cli.py", line 142, in _load_config
    conf = self._get_config()
  File "/apps/ckan/dlv/src/ckan/ckan/lib/cli.py", line 139, in _get_config
    return appconfig('config:' + self.filename)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 261, in appconfig
    global_conf=global_conf)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 320, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 454, in get_context
    section)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 476, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 406, in get_context
    global_conf=global_conf)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 328, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 620, in get_context
    object_type, name=name)
  File "/apps/ckan/dlv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 646, in find_egg_entry_point
    possible.append((entry.load(), protocol, entry.name))
  File "/apps/ckan/dlv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/apps/ckan/dlv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/apps/ckan/dlv/src/ckan/ckan/config/middleware.py", line 28, in <module>
    from ckan.config.environment import load_environment
  File "/apps/ckan/dlv/src/ckan/ckan/config/environment.py", line 18, in <module>
    import ckan.lib.helpers as h
  File "/apps/ckan/dlv/src/ckan/ckan/lib/helpers.py", line 30, in <module>
    from bleach import clean as clean_html
  File "/apps/ckan/dlv/lib/python2.7/site-packages/bleach/__init__.py", line 8, in <module>
    from html5lib.sanitizer import HTMLSanitizer
ImportError: No module named sanitizer`

**Comment by ll911** [comment]
@jrods `bleach-1.4.3 html5lib-0.9999999` fixed the sanitizer issue, bleach-1.4.2 from the `requirement.txt` does not work

**Comment by ll911** [comment]
@jrods I have updated the requirement.txt in our forked branch to include bleach 1.4.3

**Comment by gjlawran** [comment]
This should be closed on production release after verification.
