### ISSUE TITLE
Move license JSON file out of code repo

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#123]
To expedite the update of the license configuration [file](https://github.com/bcgov/ckanext-bcgov/blob/master/ckanext/bcgov/scripts/data/bcdc_licenses.json) remove it from the code repository and update the licenses [group URL](http://docs.ckan.org/en/latest/maintaining/configuration.html#licenses-group-url).

**Comment by ll911** [comment]
both licenses and sectors file moved to gogs

**Comment by ll911** [comment]
@kfishwick @gjlawran this is completed in 1.4.0, licenses and sectors json file stored under gogs repo bcdc-licenses-data
