### ISSUE TITLE
list alignment in desktop browser

### ISSUE THREAD

**Issue by ll911** [bcgov/ckanext-bcgov#129]
![screen shot 2016-07-22 at 12 38 25 pm](https://cloud.githubusercontent.com/assets/11949273/17069030/35d37752-5009-11e6-8886-550846c4ed6f.png)
see samples [here](https://catalogue.data.gov.bc.ca/dataset/summaries-of-protected-lands-and-waters-in-b-c-)

**Comment by jeff-at-h3** [comment]
assign to Garrett once he gets github acct assigned

**Comment by garrettH3S** [comment]
Working in CAD. 
![jan-16-2018 08-45-52](https://user-images.githubusercontent.com/14841506/35000644-cadd2942-fa99-11e7-87d4-6159346b56ca.gif)

**Comment by garrettH3S** [comment]
Fixed in CAD. 
![screen shot 2018-01-16 at 9 14 16 am](https://user-images.githubusercontent.com/14841506/35002176-acfc6d3a-fa9d-11e7-98ac-d149461bca88.png)

**Comment by dkelsey** [comment]
added markdown to [this dataset](https://cat.data.gov.bc.ca/Dataset/bc-crown-land-indicators-and-statistics-active-crown-tenures-on-april-1-2009).

Formatting looks better the bullet's are not compressed into the margin:
![image](https://user-images.githubusercontent.com/3906047/37228128-6251cc38-2394-11e8-85c7-e6529b9e6e5c.png)

**Comment by dkelsey** [comment]
Tested this with an unpublished dataset.  it passes.
