### ISSUE TITLE
Update Vagrant setup to resolve issue with access to shared folders

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#130]
The vagrant up command fails with mounting shared folders because the Virtualbox Guest Additions fail to install in the VM.  Workaround is to wait for it to fail, then ssh into the vm and do sudo yum update -y, restart the vm and rerun vagrant up.

**Comment by ll911** [comment]
@gjlawran hashicorp has created successor/replacement for Vagrant
https://www.ottoproject.io/intro/vagrant-successor.html

**Comment by jrods** [comment]
The main issue is bento/centos-6.7 we use for vagrant. I believe that matches what's in delivery/test/prod? @ll911

**Comment by ll911** [comment]
@jrods maybe switch to the official image instead of 3rd party ones?
http://cloud.centos.org/centos/6/vagrant/x86_64/images/

**Comment by jrods** [comment]
After some testing and analysis, I found that just using `bento/centos-6.8` and updating all the Vagrantfiles to use the different box. Existing vagrant envs won't be affected by this change if a different `config.vm.box` is specified. They will continue to use the same box it was originally initialized with. This only affects new vagrant envs.

Will update all the Vagrantfile and README.md files in the bcdc-vagrant svn and bcgov/bcdc-devops repos

**Comment by ll911** [comment]
is this still a problem?

**Comment by jrods** [comment]
For bcgov/bcdc-devops repo, yes, it's still a problem. I haven't had the time to update that repo due to more important priorities.

**Comment by Mbrownshoes** [comment]
@ll911 can you confirm that this is working?

**Comment by ll911** [comment]
i don’t have problem locally, vagrant base image should be update to use cents 6.8

**Comment by Mbrownshoes** [comment]
@jrods is this complete or do we need to push to the next release?

**Comment by jrods** [comment]
This is complete. The svn repo has been updated with the needed changes.
