### ISSUE TITLE
datastore_info API call not working

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#137]
Making a datastore_info request as a post for a production resource ID 
curl --request POST \
  --url https://catalogue.data.gov.bc.ca/api/action/datastore_info \
  --header 'cache-control: no-cache' \
  --header 'content-type: multipart/form-data; boundary=---011000010111000001101001' \
  --form id=b12cd4cc-b58b-4079-b630-a20b6df58e8d

 returns:
"Bad request - Action name not known: datastore_info"

Test against - 1.3.1 (CKAN 2.3.4)

Syntax confirmed against demo.ckan.org 
API Reference - http://docs.ckan.org/en/latest/maintaining/datastore.html#ckanext.datastore.logic.action.datastore_info

**Comment by ll911** [comment]
@gjlawran 1.4.0 has proper response for datastore_info

**Comment by gjlawran** [comment]
Confirmed this is now working in production as of P1: v1.4.0 c28e02c.
