### ISSUE TITLE
Return to PIP core release using 2.5.3BC

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#139]
Will drop use of core CKAN  form from GitHub.

**Comment by kfishwick** [comment]
We can't do this for a while, there are a number of fixes in our forked ckan that will not be merged into core (because they are not going to backport some of them).  It might have to wait until we move to 2.6 or later.

**Comment by ll911** [comment]
@gjlawran @kfishwick ckan core 2.6+ requires PostgreSQL 9.2+, SOLR 5.x +.
CKAN core 2.7+ also added additional component redis to replace memcached for session manager.

**Comment by jeff-at-h3** [comment]
related to rebasing core 2.7 - rebasing work may take care of this

**Comment by jeff-at-h3** [comment]
@dkelsey suggest moving this to 1.8.x if we wont deploy as part of 1.7.x

**Comment by dkelsey** [comment]
@ll911 can this ticket be moved to **Revoew/QA**?

**Comment by ll911** [comment]
sure, we are back to core already for test/dev

**Comment by dkelsey** [comment]
@ll911 
I'm going to say this is done?
