### ISSUE TITLE
recline_map_view broken in our forked ckan/ckanext-bcgov

### ISSUE THREAD

**Issue by ll911** [bcgov/ckanext-bcgov#142]
recline_map_view is a new feature introduced in ckan 2.5.x
demo site works(mapquest base still failed): 
http://demo.ckan.org/dataset/test-for-mat/resource/f2c76d4b-a858-4775-b30d-738cc3da477f?view_id=59d1d3dd-2462-4b90-a225-06db3b573a77

our test site failed as map_config undefined:
https://cat.data.gov.bc.ca/dataset/bc-public-libraries-systems-branches-and-locations/resource/93da6d3c-86aa-4b82-a1fd-247c7a9df01e?view_id=d7dda0e9-d71f-4108-802f-620f4d97b94c

I guess failure related to the code change from @Khalegh-H3 to altering the default base.

**Comment by kfishwick** [comment]
The 1.3.1 fix was intended to work for recline view & recline map view, but we don't have to install the recline map view plugin.    We will remove that.

The error you are seeing is not related to the usage of the recline map view, its a js error in the code that was implemented in 1.3.1.    We can fix that.

**Comment by Khalegh-H3** [comment]
Yes, the error was in javascript and it is and easy fix. But, if we want to
use MapView without adding recline_map_view plugin some changes are
required. Currently, the code for getting map configuration parameters is
in reclineMapView plugin. The best case is to add helper functions for
getting map config to both reclineView and reclineMapView plugins.

Khalegh

**Comment by gjlawran** [comment]
@ll911 the recline_map_view extension (AKA Datastore Map) was implemented with the 2.3 CKAN release as part of the [resource views](http://docs.ckan.org/en/ckan-2.3.4/maintaining/data-viewer.html) functionality associated with that release . It allows a user to create a locked preview of a map that you can generate with the recline_view (AKA Data Explorer) extension . This is similar to the Datastore Graph - which we are using in this [record](https://catalogue.data.gov.bc.ca/dataset/motor-vehicle-serious-injuries-by-month/resource/4e34bda3-03bc-4f6f-b47e-b4d2c47d4f15?view_id=fb89b7c8-fbac-4c41-9d2a-1e328f8b609a).

The fix to allow parameters to specify the basemap tilecache should be with the recline_view extension. We do not currently need the recline_map_view extension - although we might wish to use it in the future.

**Comment by Khalegh-H3** [comment]
@gjlawran  With the new fix you can have recline_view and recline_map_view both or either. So if you need to enable recline_map_view later, all you need is to add reclinemapview plugin to the list of ckan.plugins in ini file.

**Comment by kfishwick** [comment]
Added back in recline_map_view to plugin list as per email from Leo/Greg.

**Comment by gjlawran** [comment]
recline_map_view is now working in Mozilla and IE11 - but not in Chrome.

**Comment by kfishwick** [comment]
Recommend investigating making this a candidate for fixing https://github.com/ckan/ckanext-spatial/issues/157
