### ISSUE TITLE
recline_map_view tile cache not working in Chrome

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#145]
The Mapbox basemap tilecache used in recline_map_view plugin (resource view) does not display in Chrome  browser. It works in Mozilla, IE and Safari.

https://cad.data.gov.bc.ca/dataset/testing-geographic/resource/92479e9f-6e2b-4624-afec-45ea076a2ae1?view_id=beb2eb3c-1f69-4bc0-bb58-342d8fd203cd

![image](https://cloud.githubusercontent.com/assets/1154765/17420603/9e53cdb4-5a58-11e6-923b-8d90049b8b20.png)

**Comment by kfishwick** [comment]
Jared can you take a look at this in vagrant...maybe try a few different base map providers and see if it changes the behaviour?

**Comment by jrods** [comment]
That resource seems to work for me in chrome:
<img width="1285" alt="screen shot 2016-08-04 at 3 49 54 pm" src="https://cloud.githubusercontent.com/assets/5874122/17420992/31299cc0-5a5b-11e6-9ba0-2c79aa57ddfa.png">

**Comment by ll911** [comment]
Chrome on mac works, chrome on windows seems still problematic.

**Comment by ll911** [comment]
Check this
[cid:image001.png@01D1EE6B.5F32C850]

[cid:image002.png@01D1EE6B.5F32C850]

**Comment by Khalegh-H3** [comment]
I don't think this is Chrome specific issue. I have seen similar behaviour in other browsers too. It really depends on what you select as latitude and longitude fields and how you create the map view. It also expects a GeoJson field and by default it picks the first field from resource data. From what I see the form is not as smart as the recline multiview on picking the view fields.

**Comment by gjlawran** [comment]
Tile cache is now working in Chrome, Firefox and IE11. Pass.
