### ISSUE TITLE
Remove the Photo Upload from dataset edit pages

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#149]
To avoid UX, UI  and copyright issues we have discouraged the use of the CKAN capability to upload / link photos to datasets. Rather than having users have to remember to avoid this feature we would like to remove it from the user interface.

![image](https://cloud.githubusercontent.com/assets/1154765/17865444/7599dd98-6857-11e6-80de-b83fc6b70eaa.png)

**Comment by Mbrownshoes** [comment]
verified in cad
