### ISSUE TITLE
Organization name does not appear to be included in dataset search index

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#151]
When a user searches for **BC Stats** from the [datasets page](https://catalogue.data.gov.bc.ca/dataset?q=bc+stats&sort=score+desc%2C+record_publish_date+desc) the response returns 41 datasets with only 17 of these from the **BC Stats** organization.  The organization based search finds that the BC Stats organization has [47 datasets](https://catalogue.data.gov.bc.ca/organization/bc-stats). 

The search index for datasets should include the full organization name.

**Comment by Khalegh-H3** [comment]
@gjlawran

Search for BC Stats in data catalogue returns 89 datasets and exactly 47 of them belong to Data BC.

![image](https://cloud.githubusercontent.com/assets/6463284/20448447/dbecefbe-ad98-11e6-9bb0-42d9adf6255c.png)

And you can access all 47 by faceted search and selecting BC Stat from search result 

![image](https://cloud.githubusercontent.com/assets/6463284/20448474/07972d6e-ad99-11e6-8079-4c222060ba9f.png)

Am I missing something?
