### ISSUE TITLE
Show editor names for an organization to all users

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#155]
It would be helpful if the names of the editors of an organization were visible so that those looking to publish records could know who to contact regarding record updates.

Can we change the security so that this page 
https://catalogue.data.gov.bc.ca/organization/members/databc
is visible to public.

**Comment by jrods** [comment]
This page is already visible to the public https://catalogue.data.gov.bc.ca/organization/members/databc , problem is it's showing admin controls
<img width="1019" alt="screen shot 2016-09-15 at 9 25 51 am" src="https://cloud.githubusercontent.com/assets/5874122/18558068/705ca07c-7b26-11e6-8255-3b35f4b058d5.png">

**Comment by jrods** [comment]
Would admins be visible as well, or just editors?

**Comment by Mbrownshoes** [comment]
@jrods How difficult would it be to hide the admin controls, so you just see the names?

**Comment by jrods** [comment]
I'll take a look to see what needs to be done, I think it's just a matter of setting up authorization checks in the template for the admin controls.

**Comment by jrods** [comment]
I made the PR, but before merging, what user roles should be displayed for each role when viewing the member list?

eg. 'public/anonymous' can only see editors, 'admin' can see all users part of the org

**Comment by Mbrownshoes** [comment]
@jrods I think just removing the controls is the important thing. They should just be visible to admins. thanks

**Comment by kfishwick** [comment]
Sounds good, this is done.
