### ISSUE TITLE
Downloads not populated on site-usage page

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#159]
In both test and prod the downloads values are not being populated: https://catalogue.data.gov.bc.ca/data/site-usage/dataset?month=2016-08&publisher=databc. The number of views is being added.

I see in both the most recent prod and test statstrack jobs encountered the same error
"OperationalError: (OperationalError) FATAL:  remaining connection slots are reserved for non-replication superuser connections
 None None"

**Comment by kfishwick** [comment]
@Darv72  can you please grant mine & Jareds' github account access to see & execute the statstrack job in delivery?

**Comment by Darv72** [comment]
@kfishwick the stats track job for delivery is in our production Jenkins environment.  It needs to be accessed with IDIR credentials.  Can you please provide me your IDIR ID as well as Jared's?

**Comment by jrods** [comment]
@Darv72 my idir account is: jaresmit , karen's idir account is: kfishwic

**Comment by Darv72** [comment]
Access has been granted as requested.

**Comment by jrods** [comment]
I believe I found the error that was causing missing Download stats.

@Mbrownshoes can you merge PR bcgov/ckanext-ga-report#6 and initiate a new build of CAD please?

**Comment by jrods** [comment]
Download stats working on CAD now.

Before:
<img width="1016" alt="screen shot 2016-10-19 at 11 54 43 am" src="https://cloud.githubusercontent.com/assets/5874122/19533660/8e902c32-95f5-11e6-969a-6f90dd93fa7e.png">

After:
<img width="1039" alt="screen shot 2016-10-19 at 12 13 47 pm" src="https://cloud.githubusercontent.com/assets/5874122/19533661/8e9c74e2-95f5-11e6-920b-7e5cbb2cb881.png">

**Comment by jrods** [comment]
@Mbrownshoes the fix is just in the ckanext-ga-report repo, for CAT just need to get the latest version of the ga-report ext and run the statstrack job for CAT.

**Comment by Mbrownshoes** [comment]
Looks like this was merged. @Darv72 can you redeploy cad?

**Comment by jrods** [comment]
@Mbrownshoes @Darv72 it's already deployed to CAD and working there. You should be able to verify. @kfishwick already did a re-deploy

**Comment by Mbrownshoes** [comment]
It looks like downloads were populated on site usage. Will download a bunch more today and see if they appear on monday

**Comment by Mbrownshoes** [comment]
working in test
