### ISSUE TITLE
Unable to duplicate a record in cat, cad

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#162]
I'm getting server errors when I try and duplicate a record in test (1.5). I click duplicate, change the title from the default to something else (e.g., DUPLICATE dec3-ge0), click add data where I fill out the required fields and add a file and then click 'Add', which leads to a server error. 

When I check the activity stream I see the duplicated record with the default duplicate name and url (not the new name I gave it) and there isn't a resource.

I had renamed this file and added a resource but it's not there:
https://cat.data.gov.bc.ca/dataset/__duplicate__dec3-ge0​

I just tried this on delivery and ran into the exact same issue.

Didn't see anything too helpful in the logs
![tst-dup-error-log](https://cloud.githubusercontent.com/assets/3362533/18109338/847c8710-6ec5-11e6-9e2d-b5026c1b097f.png)

**Comment by Mbrownshoes** [comment]
Here's a screenshot of the error I get just after I submit 'add data'. I don't remember seeing this url previously: https://cat.data.gov.bc.ca/dataset/new_resource/a088ea5f-5e98-4137-9213-6dc67cea8808
![screen shot 2016-08-31 at 2 24 12 pm](https://cloud.githubusercontent.com/assets/3362533/18146836/ab595388-6f86-11e6-903b-0200c1d65821.png)

**Comment by Mbrownshoes** [comment]
looks like Karen meant to assign this to Jared..

**Comment by Mbrownshoes** [comment]
@jrods have you been able to make any progress on this?

**Comment by jrods** [comment]
No progress to report on this. I was able to reproduce this in my local env, but I'm still not sure what the problem is yet.

**Comment by Mbrownshoes** [comment]
still occurring in Cad, but looks like you're still working on this.

**Comment by kfishwick** [comment]
Verified in CAD, can you try it @Mbrownshoes ?

**Comment by Mbrownshoes** [comment]
Beauty, works!
