### ISSUE TITLE
Organization name of records should link to organization page not dataset page

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#170]
**ENV:** DLV, TEST, PROD

**TESTCASE:**

* navigate to an organization, (any organization) from the `organization` link in the header
* navigate to any dataset within an organization, (clicking the organization will run a search. click any result)
* Under the dataset title click the second link in the `Published by the` line:
![aaaorg_not_working](https://user-images.githubusercontent.com/3906047/34695143-9888b04a-f47e-11e7-9dfd-e021eaed2bef.PNG)

**EXPECTED:**

You are taken to the Organization page listing all datasets in that organization:
![aaaorganization](https://user-images.githubusercontent.com/3906047/34695251-fc0b64aa-f47e-11e7-8795-383aac3589fb.PNG)

**ACTUAL:**

Your are taken to a Dataset Search result page:

![aaaorganization2](https://user-images.githubusercontent.com/3906047/34695315-3e1fd038-f47f-11e7-855e-6490ef0b95f9.PNG)

**Notes:**
* facets are not working in TEST and DLV: there is a bug reported for this.

**Comment by jeff-at-h3** [comment]
analysis and update ticket please

**Comment by dkelsey** [comment]
I see that what occurs is a search that the syntax look incorrect:

The query is 

https://cad.data.gov.bc.ca/dataset?organization=oil-and-gas-commission

the correct syntax is

https://cad.data.gov.bc.ca/dataset?q=organization:oil-and-gas-commission

@gjlawran Should the link go to the Organization page ?

I see that standard CKAN doesn't have the same presentation for metadata records.
It does have an icon which is a link to the organization.  

I may have clouded the issue but I am in agreement: the link should be to the organization, not a search results page.
@gjlawran  can you comment?

**Comment by dkelsey** [comment]
I'm going to say that the link should simply be to the Organization page as I've described in the test case.

**Comment by BrandonSharratt** [comment]
Created PR #662 to fix this

**Comment by jachurchill** [comment]
Passed in CAT and PROD
