### ISSUE TITLE
Non-used fields showing for application/webservice type

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#176]
'Data quality' and 'Lineage statement' are incorrectly showing in the UI for application and webservice record type, though these fields are not shown when editing records of these types (they are not part of the schema).

![screen shot 2016-09-20 at 8 49 05 am](https://cloud.githubusercontent.com/assets/3362533/18677824/fce8608a-7f0e-11e6-8eed-a22b68073c78.png)

These fields should be removed from the UI.

**Comment by kfishwick** [comment]
Should be a fairly straightforward fix, do you have a target milestone?

**Comment by Mbrownshoes** [comment]
1.6, if possible.

**Comment by jrods** [comment]
@Mbrownshoes related to #168 , do you want Data Quality and Lineage Statement to always display or only display if there's a value for those fields?

**Comment by Mbrownshoes** [comment]
Good question. I think we should always have them displayed for those types, for now.
