### ISSUE TITLE
google analytics not registering downloads

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#177]
Google analytics is showing and recording page visits, however downloads are not being registered as events from July 13 onward.
Visits:
![screen shot 2016-09-21 at 9 18 33 am](https://cloud.githubusercontent.com/assets/3362533/18719455/48458468-7fdc-11e6-969f-5898894cf184.png)
Events (downloads):
![screen shot 2016-09-21 at 9 19 12 am](https://cloud.githubusercontent.com/assets/3362533/18719476/5d86a398-7fdc-11e6-90c4-f784c8ac4eb6.png)

It looks like this coincides with the release of 1.3.0 on July 12 where ckan was upgraded to 2.3.4 and there was a fix for google analytics.. the header and foooter were also updated.
The GA fix allowed us to run ga_report and download past GA values but something stopped new downloads from being registered as events by GA.

This behaviour is also observed in TEST.
@ll911 @gjlawran

**Comment by jrods** [comment]
I may have found the issue, one of the js scripts that gets loaded in ckan wasn't using the new method of making a tracking request. Won't be able to tell if that was causing the problem, will need to have it be tested in cat.

**Comment by jrods** [comment]
@Mbrownshoes @Darv72 is cad setup with google-analytics? will you be able to check to see if it's now tracking dowanloads now?

**Comment by Mbrownshoes** [comment]
@jrods Yes, we can see the downloads on cad. @gjlawran are we going to try and push this through as 1.5.2?

**Comment by Mbrownshoes** [comment]
Downloads are being registered in CAT and are showing on the site-usage page.

**Comment by Mbrownshoes** [comment]
google analytics is stil showing Missing Tracking Code error
Page ...data.gov.bc.ca for property ...data.gov.bc.ca is missing valid tracking code.
