### ISSUE TITLE
Unable to add new organizations [urgent]

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#185]
We're getting a server error when attempting to add a new organization in prod and test. I'm not seeing the 'Add Organization' button in cad. 
This is urgent. Please fix ASAP.

**Comment by jrods** [comment]
Ok, I'll have a look, is it just an error 500 page on test/prod?
For cad, is the 'Add Org' button not showing for everyone (editors/admins)?

**Comment by jrods** [comment]
@Mbrownshoes in my local env, my sysadmin account can see the button, but as an editor i can't. What's the correct use case for adding organizations?

<img width="1033" alt="screen shot 2016-09-29 at 10 15 44 am" src="https://cloud.githubusercontent.com/assets/5874122/18964460/d67ba756-862d-11e6-83dc-eb2a9b3432ba.png">

**Comment by Mbrownshoes** [comment]
It’s the server error message displayed in the catalogue:


[cid:image001.png@01D21A3B.14BEB1C0]

Editors aren’t able to add new organizations. I do have admin access for CAD and can’t see the button.

**Comment by Mbrownshoes** [comment]
@jrods Only admin's are able to add organizations and in Prod and Test the button is showing, the button is shown but when pressed it results in a server error. 


![screen shot 2016-09-29 at 10 22 19 am](https://cloud.githubusercontent.com/assets/3362533/18964684/cb34dae2-862e-11e6-9ced-b47df9eae33e.png)
In Cad, I'm not seeing the button at all.

**Comment by jrods** [comment]
@Mbrownshoes i think i know what the problem is for the add org button. The 'admin' role is organization/sub org specific, this isn't the same as 'sysadmin'. So when a user is an 'admin' for an org, they don't have the same permissions as what a 'sysadmin' has in ckan; Ckan still considers that user just a 'member' and not a 'sysadmin'

**Comment by jrods** [comment]
@Mbrownshoes as for the error in prod/test when adding a new org, i am getting the same error message in my local env. I'm still doing some analysis on that issue.

**Comment by jrods** [comment]
@Mbrownshoes I have found and fix the issues, plus some additional changes for the ckan fork.
First, merge this PR for ckan core: https://github.com/bcgov/ckan/pull/10, it includes missing migration scripts, needed for db upgrade command. 

Second, this PR will fix the error when adding a new org: https://github.com/bcgov/ckanext-bcgov/pull/186

**Comment by kfishwick** [comment]
@Mbrownshoes  can you please test this in cad?
