### ISSUE TITLE
Resource last modified date is presenting GMT rather than local time

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#188]
As a user I would like to see all dates and times presented as local time rather than GMT.

The last release,which added the resource update date and time, is based on issue https://github.com/bcgov/ckanext-bcgov/issues/117

**Comment by jrods** [comment]
@gjlawran can you provide examples? On cad, i'm seeing last modified for resources displayed in local time.

**Comment by jeff-at-h3** [comment]
related to #369 
please reevaluate to make sure times are correct with timezone of current user

**Comment by garrettH3S** [comment]
@dkelsey  Working in CAD. 
![jan-16-2018 11-35-03](https://user-images.githubusercontent.com/14841506/35008453-5c443670-fab1-11e7-839c-4954b21690b1.gif)

**Comment by dkelsey** [comment]
**TESTCASE**
* uploaded a new version of a CSV

**EXPECTED**
* property formatted, current time is displayed and 
* correct timezone is displayed.

**ACTUAL**
![image](https://user-images.githubusercontent.com/3906047/37223923-de7afe64-2386-11e8-9b0b-bf705dde08e4.png)

----
From **PROD**
here's an example of the data-time format currently used in PROD.
![image](https://user-images.githubusercontent.com/3906047/37224076-46a8f2fc-2387-11e8-9e3c-3147318f0950.png)

@ll911 what time are our servers set to? GMT?

**Comment by jrods** [comment]
@dkelsey I tested this in my local env and it's also affected, I will investigate. submited around 2:23pm and is displaying 9:23pm.
In my ckan.ini, `ckan.display_timezone` is set to `America/Vancouver`

**Comment by jrods** [comment]
@dkelsey @cnewallbcgov what's the exact requirements here? I think i miss understood something, should the time displayed be the browsers local time?

If you're open to suggestions, maybe always displaying in Pacific time, considering all the data is BC specific? If not, I'll need to fix my PR #471

**Comment by dkelsey** [comment]
Displaying the date in Pacific time, makes sense to me.

**Comment by jrods** [comment]
@dkelsey deployed and verified in cad, but there's an issue with the timestamp storage itself that just came to my mind, when storing the time, there's no consideration of daylight savings time, because ckan stores time as utc now and is naive, so resources creating/modified during PDT will be correct in that time period but ill be off by an hour during PST, and vice versa.

**Comment by cnewallbcgov** [comment]
The timestamp being off by one hour 6 months of the year is not a big deal given that the date is the more useful information over the longer term.

**Comment by dkelsey** [comment]
Passes in PROD.
I uploaded a resource just now:

![image](https://user-images.githubusercontent.com/3906047/40456196-e91220c4-5ea4-11e8-9cd3-ae787df0f4a2.png)

Resource Last Modified | 2018-05-23 16:15:49 PDT
-- | --



Resource Last Modified | 2018-05-23 16:15:49 PDT
-- | --
