### ISSUE TITLE
The edit template for Applications record types should be changed to match the display template

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#192]
Edit is 
- Who can view this data?
- Who can download this data?

Display is:
Who can access this application?    Public
Who can view this record?   Public

Also remove the License field from the edit template - should default to access only.

**Comment by h3devin** [comment]
@gjlawran 

To clarify - did you want to hide the License field only when editing, only when editing Applications, or for editing & adding as well (again just Applications, or all dataset types)?

Additionally, I'm seeing fields for both "Who can view this data?" and "Who can view this record?" in the edit screen. Did you want to hide the "Who can view this data?" field?

**Comment by gjlawran** [comment]
@h3devin Thanks for the questions.

1) Remove the license field from the edit screen - default the value to Access Only for display purposes.

2( Remove who "Who can download this dataset'  field from the edit screen. It is already removed from display screen.

3) 'Who can view this Record'  should remain on both the edit and display screens.

4) On the edit screen relabel "Who can view this dataset" to  "Who can access this application" to match what is now on the display screen.


'

**Comment by Khalegh-H3** [comment]
@gjlawran 

If "Who can download this dataset" must be removed, then the schema for application datasets types must be changed. As, it will throw missing error on dataset create/edit when no value is given for download_audience field. And, you don't want any application type record to be listed on "Download Permission" search?
