### ISSUE TITLE
Map and Table tabs showing up automatically in the Resource View

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#193]
For csv files added to the datastore 'Map' and 'Table' tabs and now automatically shown next to 'Data Explorer' 
![screen shot 2016-10-05 at 1 38 56 pm](https://cloud.githubusercontent.com/assets/3362533/19131361/fa3ed6ec-8b03-11e6-8ce4-e2e9d06275a0.png)

I believe if we remove 'recline_grid_view' and 'recline_map_view' from the default_views we should be able to add these as views, but not have they appear by default. Shall I try this in delivery?

**Comment by gjlawran** [comment]
Added CSV file to TEST version v1.5.2 8d69571 and no grid_view and map_view were created by default.
