### ISSUE TITLE
Update to ckan.ini

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#196]
This ticket is to keep track of changes made to the dlv.ini file.
- added recline_grid_view as a ckan_plugin so that editor can create a chart that can be embeded.
- removed recline_map_view and recline_grid_view from ckan.views.default_views so they don't appear by default as tabs next to the data explorer.

@ll911 @gjlawran @Darv72 @kfishwick @jrods

**Comment by kfishwick** [comment]
@jrods  can you please upgrade the vagrant ini file & verify everything is working?
