### ISSUE TITLE
provide direction for adding new resource geographic projections as a vocab

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#197]
We have a new projection, which I added here:
https://github.com/bcgov/ckanext-bcgov/commit/c26e91b074708096a3959dbd141edb19c6ec9cc0

It's been merged and deployed in delivery but the new projection is not visible in the dropdown when creating a resource for a geographic record. Are there additional changes needed?

@ll911 @Darv72 @gjlawran

**Comment by Mbrownshoes** [comment]
I'm removing the change made to ckanext/bcgov/scripts/data/edc-vocabs.json
and moving this issue to the 1.6  release

**Comment by kfishwick** [comment]
@jrods  can you please provide instructions for how to do this?

**Comment by Mbrownshoes** [comment]
@jrods this is the name of the new projection "EPSG_3153 - NAD83(CSRS) BC Albers"

**Comment by Khalegh-H3** [comment]
@Mbrownshoes, @gjlawran 

New vocabulary tags must be added either by api calls or by running create_vocabs.py script. The script goes through the list of the vocabularies provided by edc-vocabs.json and adds any new vocabularies.
Please not that the script is using base.py  and needs config/import.ini.
But probably the easiest way to add a new tag to an available vocabulary,in this case projections, is to use postman or any other api client

1. Get the vocabulary id by calling /api/3/action/vocabulary_show?id=projection_name
This will show the list of available tags including vocabulary_id for each one.

2. Do the following post request using the vocabulary_id for projection_name :
site_url/api/3/action/tag_create
Request body :
name : EPSG_3153 - NAD83(CSRS) BC Albers
vocabulary_id : projection_name

You also need api_key for authorization.

Please note that ckan only accepts Alphanumeric characters plus - and _ as tag names. So, "EPSG_3153 - NAD83(CSRS) BC Albers" will throw an error unless you remove parenthesis from the name. 

I tested the api calls locally and the new projection, using "EPSG_3153 - NAD83-CSRS BC Albers" as the name, was added without any errors.

**Comment by Mbrownshoes** [comment]
@kfishwick @Khalegh-H3 can you please explain what exactly needs to be done to incorporate the new projections? the added projection has been added here 
https://github.com/bcgov/ckanext-bcgov/commit/c26e91b074708096a3959dbd141edb19c6ec9cc0

Just run the create_vocabs script and it will be added? I'm unsure how I would use the second option if a vocabulary_id doesn't exist for the new projection.

**Comment by Mbrownshoes** [comment]
the new projection has been added to cat.
