### ISSUE TITLE
Extension is broken by change to Google API

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#200]
As referenced in the Google-Analytics Extension repo - https://github.com/ckan/ckanext-googleanalytics/issues/2 - a change to the Google API has resulted in issues with this extension. Please investigate and estimate. 

Our current extension cannot show Site Usage by Month for Totals  https://catalogue.data.gov.bc.ca/data/site-usage . This may not be associated with the Google API change - but also requires investigation.

**Comment by Mbrownshoes** [comment]
This must be related to: https://github.com/bcgov/ckanext-bcgov/issues/177

**Comment by kfishwick** [comment]
I think #177  maybe have the same root cause but there might be additional areas of the site that need to be fixed.  Assigning to @Khalegh-H3  for analysis.

**Comment by kfishwick** [comment]
We don't think https://github.com/ckan/ckanext-googleanalytics/issues/2 is relevant - that is a 2012 reported issue and we are already using the oauth2 to connect to GA.

**Comment by gjlawran** [comment]
Confirmed - this issue was resolved in a previous core version - our new ticket https://github.com/bcgov/ckanext-bcgov/issues/177 is  tracking the problem with downloads not being registered.
