### ISSUE TITLE
Automated test script failing to run

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#203]
It seems our automated tests are having problems loading the selenium webdriver (both Chrome and Firefox). 
The problem appears to be here in webdriver.py

```
    if chrome_options is None:
        # desired_capabilities stays as passed in
        if desired_capabilities is None:
            **desired_capabilities = self.create_options().to_capabilities**()
```

We've never encountered this in the past and there hasn't been change to the code repo.

**Comment by Mbrownshoes** [comment]
@kfishwick looks like part of the issue was that I needed to update the chrome webdriver. It looks like this change has affected the tests as they are still failing to run: 
AttributeError: 'WebDriver' object has no attribute 'url'

I'll continue to investigate a bit.

**Comment by LeeZeitz** [comment]
@Mbrownshoes  The new WebDriver has changed that attribute from "driver.url" to "driver.command_executor._url"
I haven't got that particular functionality working in my Vagrant yet, but I think that's because of some weird cookie stuff revolving around "localhost". I expect it should work with any other url, i.e. development, test, or prod.

**Comment by Mbrownshoes** [comment]
@LeeZeitz great will test it out. thanks

**Comment by LeeZeitz** [comment]
@Mbrownshoes I didn't find it in any of their documentation, I had a look at the source code and found it in there.

**Comment by Mbrownshoes** [comment]
@kfishwick @LeeZeitz have the tests been updated (for the UI changes, issues on the gogs site)?

**Comment by kfishwick** [comment]
Matt, we are working through test changes but this particular ticket is code complete.

**Comment by Mbrownshoes** [comment]
sounds good. Yeah, gogs issues aren't great for tracking.. Maybe when the tests are updated we can great an issue here to keep track of the changes. Either place works for now. Eventually we should get the tests moved over to github.
