### ISSUE TITLE
Editors not receiving notifications in test and delivery

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#205]
Only Admin's are receiving "pending publish" notifications in cat and cad. Editors should also be receiving these. Editors are receiving notifications in production. 

In delivery this might be intentional as 'ckan.activity_streams_email_notifications = true' is commented out, but it isn't in cat. Again, admins do receive them. 
For our test editor account the last notification for cat was on Aug 31 and Aug 24 for delivery. 

Please investigate.

**Comment by kfishwick** [comment]
This is as designed,  admins only receive the pending notices and editors only receive rejected/published/archived.

**Comment by Mbrownshoes** [comment]
verified in CAD
