### ISSUE TITLE
Create a CKAN extension to show Swagger UI for Web Service datasets

### ISSUE THREAD

**Issue by banders** [bcgov/ckanext-bcgov#209]

**Comment by banders** [comment]
This issue is intended to supersede [Issue 96](https://github.com/bcgov/ckanext-bcgov/issues/96).

Suggested Approach:
- Develop as a standalone extension.  
- Embed the swagger UI in the dataset view, not in a resource view as was suggested in the discussion around Issue 96.

**Comment by gjlawran** [comment]
Moved to 96.
