### ISSUE TITLE
Simple geographic data selection tool

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#212]
As a user,  I don't want to go to a different user interface to extract a geographic dataset from the BC Geographic Warehouse because this is confusing and time consuming. 

I would like to have a simple interface where I can select the format, portion of the data I want, geographic projection and then either download the data directly or  if necessary provide an email to be notified when the download is prepared for pickup.

For the first iteration of this tool when the user selects the download dropdown from the  package page - provide a modal order window  ( MOW )interface to achieve these goals.

A prototype UI is being developed in this [repo](https://github.com/gjlawran/gdst).

This modal window will be presented whenever a user selects resource download for geographic datasets that have been configured by editors. 

TODOS: 
1) Confirm a list of object-names with maximum area (hectares) is available.
2)

**Comment by kfishwick** [comment]
Small detail, our decision with issue 213 was to create resources for each format, so the user would not actually be able to select a format.

**Comment by kfishwick** [comment]
Small detail, our decision with issue 213 was to create resources for each format, so the user would not actually be able to select a format.

**Comment by banders** [comment]
I forked the repo with the UI prototype, and added a leaflet map.  The "order" button is enabled/disabled based on the map area.

@gjlawran: I created a pull request with my changes to the UI prototype.  Perhaps you can merge my changes back into your repo..?

**Comment by kfishwick** [comment]
Further clarifications after meeting with @gjlawran 

1. When the user checks "I consent to the collection..." then hide the "The information on this form".  If they uncheck the consent checkbox then show the text again.

2. If the object name is not found in the max AOI resource, then assume there is no maximum and hide the text from "Maximum download..." down to "Please elect an area < ".  

3. After the user submits their order, display a confirmation page with the status from the OFI place order.

**Comment by kfishwick** [comment]
@gjlawran  and @Mbrownshoes can you confirm these details & supply the exact text for "please log in" and "you do not have access" use cases.

For an unauthenticated user attempting to access an OFI resource, we will make the call to see if the object is available.  If it is, we proceed to MOW.  If not, we provide "please log in" text.

For an authenticated user attempting to access an OFI resource, we will make the call to see if the object is available (for that user).  If it is, we proceed to MOW.  If not, we provide "you do not have access" text.

Where do you want the text for these cases, keeping in mind the user could be clicking Access/Download from the dataset resources page, or a resource detail page.

**Comment by kfishwick** [comment]
@gjlawran  and @Mbrownshoes  please note that we are still waiting on the exact message text as requested above.

**Comment by gjlawran** [comment]
Need to make the modal window a little shorter. Remove the title Geographic Data Download and replace with instruction. "Pan and zoom this map to select the geographic area of data to download. Then enter your email address." Add hover-text to email box - "An email will be received once order is placed and when data is ready for download."  

AOI limit text should read.

Due to the size of this dataset, please select an area of less than [x] hectares.   Current area selected is: x hectares.

We also have a small change to the collection terms.

**Comment by gjlawran** [comment]
When a user who is not logged in attempts to order a secure dataset. They receive this error message "Error: User is not allowed to view object.'

Could we alter this message to 

"Error: This is a dataset with restricted access. To place an order for download please [login first](https://[domain].apps.gov.bc.ca/int/eas/login.jsp).

**Comment by jrods** [comment]
I've updated the error message in this PR #271 @gjlawran

**Comment by Mbrownshoes** [comment]
@banders @jrods  I'm not seeing the order button disabled in tst when I try and order a dataset that is too large to download. I just this error message which isn't particularly helpful. 

![screen shot 2017-01-10 at 11 36 56 am](https://cloud.githubusercontent.com/assets/3362533/21826549/cc14bfa4-d73c-11e6-9306-fc175b2d8b00.png)
