### ISSUE TITLE
recline_map_view not showing points in correct locations

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#216]
When creating a map view, the points with correct latitude and longitude are being placed incorrectly
![screen shot 2016-11-03 at 1 52 41 pm](https://cloud.githubusercontent.com/assets/3362533/19984855/62750102-a1cd-11e6-8740-2bebac4835fa.png)

Map view is working in 1.51 but not in 1.5.3. I've tested this with a few resources.

**Comment by Mbrownshoes** [comment]
This isn't consistent, now it is looking correct
https://cat.data.gov.bc.ca/dataset/test-1-5-data/resource/0c1cbc16-e9ba-4256-a330-e1c378310103?view_id=cf3ffb1c-254e-48c4-8947-8bd1ad4150a5

**Comment by gjlawran** [comment]
Still a problem for these resource views ...
https://cat.data.gov.bc.ca/dataset/bc-public-libraries-systems-branches-and-locations/resource/93da6d3c-86aa-4b82-a1fd-247c7a9df01e?view_id=023e31cd-b0c2-4a2f-8466-5d46d4ffe7f6

**Comment by kfishwick** [comment]
@gjlawran This is what I see when I look at your link.  I'm not sure what is the actual issue, that the points are not distributed correctly or the background map isn't displaying?

![image](https://cloud.githubusercontent.com/assets/5503136/21788523/0ebafb3e-d684-11e6-8239-98ad2a676995.png)

I tried another one and it looks good:

https://cat.data.gov.bc.ca/dataset/stops-of-interests/resource/f3a17a60-537f-4b45-9d2f-020957f85ac5?view_id=53e245e3-dd25-4902-972f-f7667d72b5b1

**Comment by Mbrownshoes** [comment]
@kfishwick this is still an issue, the background in prod and test is gray. The background map only shows when the points are clicked.

**Comment by jrods** [comment]
@Mbrownshoes im just testing that resource in my local env, i notice that when you try to create a new view, the Longitude field gets set to Latitude.

**Comment by jrods** [comment]
@Mbrownshoes @kfishwick if the grey map tiles is a problem, can it be moved to a new issue please?

**Comment by Mbrownshoes** [comment]
@jrods moving the grey map tiles issue to https://github.com/bcgov/ckanext-bcgov/issues/287
