### ISSUE TITLE
When editing an organization, directory incorrectly shows 'members'

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#217]
<img width="1085" alt="screen shot 2016-11-04 at 9 03 51 am" src="https://cloud.githubusercontent.com/assets/3362533/20012880/4fe8011e-a26e-11e6-92f5-be0c02a57bdc.png">

It should say 'Edit' instead of 'Members' when editing an organization.

**Comment by jrods** [comment]
@Mbrownshoes I've checked in cad, it now displays 'Edit' instead of 'Members'

**Comment by Mbrownshoes** [comment]
Hmm, I see the members page also says 'edit' now. I assume this is due to us separating the members from the organization edit page.

**Comment by jrods** [comment]
Looks like this is because both the org/members page and org/edit page use the same base template, I'm looking into this problem now
