### ISSUE TITLE
Reordering resources not working

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#237]
When an editor or an admin attempts to reorder a record's resources the new order is often not retained when viewing the main record page. Furthermore, after refreshing the main record sometimes the order of the records jumps around. This has been observed in several records.
I just saved the order of these resources to:
![screen shot 2016-11-22 at 2 18 59 pm](https://cloud.githubusercontent.com/assets/3362533/20544347/7a9d383a-b0be-11e6-803e-c28212044998.png)
then refreshed and it reverted back to the previously saved order
![screen shot 2016-11-22 at 2 19 16 pm](https://cloud.githubusercontent.com/assets/3362533/20544362/8e3062e6-b0be-11e6-8a48-641044f5f676.png)

**Comment by hleckenb** [comment]
@mdunhamwilkie verify this is still a problem. I just tried it in PROD (Chrome) and it doesn't seem to be a problem.

**Comment by mdunhamwilkie** [comment]
appears to be fixed
