### ISSUE TITLE
Confirm download statistics working for all resources

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#253]
Reviewing the site usage values  https://catalogue.data.gov.bc.ca/data/site-usage/dataset?month=2016-11&publisher=medical-services  it appears there are no downloads being recorded for this organization since July.

Please determine why there are no downloads reported for the months of October and November after the fix to record downloads  was applied.

**Comment by kfishwick** [comment]
Looking at the referenced dataset, surgical wait times was downloaded 9 times.    I tried a new data set:

https://catalogue.data.gov.bc.ca/data/site-usage/dataset?month=2017-01&publisher=elections-bc

lots of downloads.  Maybe this is working again?

![image](https://cloud.githubusercontent.com/assets/5503136/21788276/91c352e4-d682-11e6-8ad6-33e943415adc.png)

**Comment by Mbrownshoes** [comment]
downloads appear to be working
