### ISSUE TITLE
ofi MOW order UX improvement

### ISSUE THREAD

**Issue by ll911** [bcgov/ckanext-bcgov#263]
1, when current extend is more than max downloadable extend, "place order" bottom should be disabled.
2, auto populate the email addresses for secured packages order, user already logged in, no need to fill the email address for registered users since the email address already there.

**Comment by ll911** [comment]
<img width="934" alt="screen shot 2016-12-07 at 11 38 14 am" src="https://cloud.githubusercontent.com/assets/11949273/20983553/c2642e08-bc71-11e6-863f-ab6e04469a5f.png">
<img width="935" alt="screen shot 2016-12-07 at 11 38 03 am" src="https://cloud.githubusercontent.com/assets/11949273/20983554/c26738be-bc71-11e6-9860-ba82c6451eb1.png">

**Comment by kfishwick** [comment]
That object is not in the list of objects that contains a max AOI.

https://catalogue.data.gov.bc.ca/api/action/datastore_search?resource_id=d52c3bff-459d-422a-8922-7fd3493a60c2

It's either missing from that list or OFI is erroneously returning the "max size" error.

**Comment by gjlawran** [comment]
Confirmed. This was a configuration issue. When a dataset does not have a max AOI specified - and it should  - the system will display this error.  This will not be a problem with the next version of OFI - as it will include the max AOI in the information response - and we will not be reliant on this configuration.

**Comment by ll911** [comment]
what about email address completion for logged in users?

On Dec 16, 2016, at 7:34 AM, Greg Lawrance <notifications@github.com<mailto:notifications@github.com>> wrote:


Confirmed. This was a configuration issue. When a dataset does not have a max AOI specified - and it should - the system will display this error. This will not be a problem with the next version of OFI - as it will include the max AOI in the information response - and we will not be reliant on this configuration.

-
