### ISSUE TITLE
Open api json resource 

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#264]
Please add this as a resource type.

**Comment by banders** [comment]
Not sure if we store mime types for the resource formats, but if we need a mime type I think we should use "application/openapi+json".  That seems to be the [recommendation](https://github.com/OAI/OpenAPI-Specification/issues/110) (though still unofficial) from the OpenAPI specification group:

**Comment by kfishwick** [comment]
@Mbrownshoes  can you or @banders  please provide a little more detail about what exactly you want to happen when a resource is creating with this resource type?

**Comment by banders** [comment]
@kfishwick We would like for resources of the new format (e.g. "openapi+json") to show the openapi_view on the resource preview page.  The openapi_view plugin is defined in this [extension](https://github.com/bcgov/ckanext-openapiviewer).  

The OpenAPI specification format is a subset of JSON, so I suggest we also offer the text_view to resources of the new format to show the raw JSON text.  

If possible, the openapi_view should be the default.

**Comment by kfishwick** [comment]
Ok and if you have not included the extension, what should happen?  I assume we have other situations like this so maybe @jrods  or @Khalegh-H3  already know the answer...

**Comment by jrods** [comment]
@banders i can't add openapi+json to ckan because for vocab tags you're only allowed alphanumeric characters or symbols: - _ 
I can do `openapi` or `openapi-json`

**Comment by banders** [comment]
That's too bad.  I think we need both words ("openapi" and "json") in the name because there is an alternative openapi format which uses "yaml" instead of "json" (although we don't currently support the "yaml format).

How about we  go with "openapi-json"?

**Comment by ll911** [comment]
the format is json, mimetype is openapi+json, since json already used, new mime type can be added via `add_type('application/vnd.openapi+json', '.openapi’)`
On Dec 20, 2016, at 9:56 AM, banders <notifications@github.com<mailto:notifications@github.com>> wrote:


That's too bad. I think we need both words ("openapi" and "json") in the name because there is an alternative openapi format which uses "yaml" instead of "json" (although we don't currently support the "yaml format).

How about we go with "openapi-json"?

**Comment by ll911** [comment]
```add_type('application/vnd.openapi+json', '.openapi')```

**Comment by gjlawran** [comment]
@jrods  will change resource format MIME type.

**Comment by kfishwick** [comment]
Also, @jrods  please change the ini file also.

**Comment by kfishwick** [comment]
@banders  will add the resource type in the openapi extension.

**Comment by jrods** [comment]
These instructions are similar to #197, the `resource_format` in the vocabulary table needs to be updated to include `openapi-json` for **cad/cat/prod** env. An authorized user in those env need to be able to use the `tag_create` api call ( @ll911 @Mbrownshoes ).

First step is to get the id for `resource_format`:
```
GET /api/action/vocabulary_show
id=resource_format
```
The request should return a json object with `id` in `result`, you'll need the value associated with the `id` key.

Second step is to create a POST for `tag_create`:
Note* im not sure if you'll need `SMSESSION` and `edc_auth` header fields to make the request
```
POST /api/action/tag_create
Content-Type: application/json
Authorization: <user api key>

{
    "vocabulary_id": "<id value from the first step>",
    "name": "openapi-json"
}
```
If all goes good, the request should return something like this:
```
{
    "help": "http://10.1.0.2:5000/packages?ver=%2F1&name=tag_create&logic_function=help_show", 
    "success": true, 
    "result": {
        "vocabulary_id": "a42b7f16-b269-46c1-9464-98edc903fa81", 
        "packages": [], 
        "display_name": "openapi-json", 
        "id": "a3d45295-4fe8-4b64-8de0-d1e43e45a6e2", 
        "name": "openapi-json"
    }
}
```

#### Add `openapi-json` to Text View
To have the resource also create a text view of the openapi file, add this to your ckan config ini file:
```
ckan.preview.json_formats = json openapi-json
```
You must do the steps above first before the text view can create a view for openapi files.
@gjlawran @Mbrownshoes Are `openapi-json` resources going to have a text view as well?

**Comment by ll911** [comment]
@Mbrownshoes @gjlawran @jrods no need for text view, the open api specs source would be in https://github.com/bcgov/api-specs as plain text.
