### ISSUE TITLE
Clicking 'add new resource' displays 'Manage OFI resources' window

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#274]
In geographic records that already have OFI resources created, clicking the 'add new resource' button causes the 'manage OFI resources' window to pop up, which is a bit confusing. This window should only be shown when the manage ofi resources button is clicked.

@ll911 @gjlawran shall we aim to have this fixed for the 1.6 release?
<img width="816" alt="screen shot 2017-01-11 at 1 43 44 pm" src="https://cloud.githubusercontent.com/assets/3362533/21868122/281c0d4c-d806-11e6-9b57-0a7ca5c816c5.png">

**Comment by kfishwick** [comment]
Analysis please @jrods?  Is this fairly straightforward?

**Comment by Mbrownshoes** [comment]
@jrods any word on this?

**Comment by jrods** [comment]
I remember trying to have it not automatically pop up when there are existing ofi resources on first implementation. I'll have a look at it again and have it not auto open.

**Comment by Mbrownshoes** [comment]
@jrods okay, I've moved this issue to the 1.7 release.

**Comment by jrods** [comment]
@Mbrownshoes PR #278 is now in cad and prevents the manager from automatically when there are ofi resources
