### ISSUE TITLE
Unable to create openapi resources for webservice records

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#276]
in test and delivery, when we attempt to add a new API Console resource to a web service record we are encountered with a server error when we click "add"
<img width="561" alt="screen shot 2017-01-17 at 1 54 27 pm" src="https://cloud.githubusercontent.com/assets/3362533/22041641/7ddd5848-dcbc-11e6-9e6b-194169418a07.png">

After navigating back to the record page, the resource is not there and [DRAFT] appears next to the title. This also occurs in delivery. 
![screen shot 2017-01-17 at 11 45 03 am](https://cloud.githubusercontent.com/assets/3362533/22041711/b58b2acc-dcbc-11e6-864c-ec2bc0a5e4ec.png)

@leo checked the database and the state for these records is not 'active' as they should be, but are 'draft'.

**Comment by kfishwick** [comment]
Analysis please @jrods ?

**Comment by kfishwick** [comment]
Actually @jrods has pointed out this may be an issue with @banders  extension.  @banders  can you please take a look & let us know?

**Comment by banders** [comment]
@kfishwick @jrods I have created a patch for ckanext-openapiviewer which will fix this issue.  My pull request to have the patch incorporated back into the 'bcgov' repo is [here](https://github.com/bcgov/ckanext-openapiviewer/pull/11).

**Comment by Mbrownshoes** [comment]
@jrods I see this has been merged with ckanext-openapiviewer. When that merge is done is cad redeployed or do you manually need to trigger a redeploy?

**Comment by jrods** [comment]
@Mbrownshoes a manual trigger needs to be initiated with changes to that ext. (Karen already did a redeploy, so the changes are in cad right now :)

**Comment by Mbrownshoes** [comment]
@jrods thanks, today I'm unable to recreate this issue in cat (I am able to create openapi resources), though cat has not been redeployed. I'm wondering how this fix was integrated.
