### ISSUE TITLE
Connections must be closed when using python ckanapi

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#284]
We've been encountering many server errors with the logs have showing the following message over the past few days:

OperationalError: (OperationalError) FATAL:  remaining connection slots are reserved for non-replication superuser connections

When using the ckanapi sessions must be closed or you will risk running out of connections:
https://github.com/ckan/ckanapi#session-control

**Comment by jeff-at-h3** [comment]
@Mbrownshoes  please validate and update the ticket

**Comment by Mbrownshoes** [comment]
@ I believe @ll911 implemented a fix for this by closing connections.
