### ISSUE TITLE
recline map view showing grey background

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#287]
After creating a view as an editor, the map tiles are grey until a point is clicked on
https://catalogue.data.gov.bc.ca/dataset/bc-aboriginal-business-listings/resource/1b9d73d0-62a7-485f-a177-55e46701073a?view_id=17e83456-38f4-4153-a160-b8516528f49a
![screen shot 2017-02-20 at 2 18 46 pm](https://cloud.githubusercontent.com/assets/3362533/23143725/c5bf5172-f777-11e6-8f59-3e7f995c4a07.png)

The map tiles did resolve at the zoomed out world scale before I clicked Auto zoom to features:
![screen shot 2017-02-20 at 2 21 22 pm](https://cloud.githubusercontent.com/assets/3362533/23143737/e00d19a6-f777-11e6-8df2-c498d569e386.png)

**Comment by jrods** [comment]
@Mbrownshoes is this still an issue? The linked resource here has a visible map.

**Comment by jrods** [comment]
Strange, the map will load if the tab loads the page in the background and the browser has another tab in the foreground. There could be some javascript blocking leaflet from completing the downloading of map tiles. I also notice the map view doesnt work at all when it's the plain grey background.

**Comment by jrods** [comment]
Seems like it's the auto zoom in on features that's causing this issue. I found a related issue on the leaflet repo https://github.com/Leaflet/Leaflet/issues/3198

**Comment by jrods** [comment]
An update on this issue, it looks like upgrading leaflet from version 0.7.3 to 0.7.7 fixes this issue. This could be raised to core ckan, because recline view uses version 0.7.3.

**Comment by jrods** [comment]
This was committed to core ckan, not sure if it will be in version 2.7 thou

**Comment by Mbrownshoes** [comment]
I believe this issue became resolved when we moved to leaflet.js 0.7.7
