### ISSUE TITLE
Remove 'eternal link' next to OFI resources

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#290]
When OFI resource are created 'external link' appears next to the resource title
https://catalogue.data.gov.bc.ca/dataset/provincial-electoral-district-voting-areas-gazetted-09-27-2012

This was introduced when we started displaying the size of resources stored in the file store. The external link is not very helpful, since when you click on the link you're now taken to the resource page, rather than triggering a download as it used to. OFI resources aren't really an external link.

Let's continue to display the size of resources in the file store and show nothing for all other resources.
@ll911 @dkelsey

**Comment by dkelsey** [comment]
This was fixed in [290](https://github.com/bcgov/ckanext-bcgov/issues/306)
