### ISSUE TITLE
unable to delete OFI resources 

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#297]
@jrods I'm unable to delete all OFI resources in cad. I was able to individually delete OFI resources.

![screen shot 2017-03-02 at 10 12 45 am](https://cloud.githubusercontent.com/assets/3362533/23520684/e20bfaa4-ff30-11e6-8868-887c964ad45c.png)

**Comment by jrods** [comment]
@Mbrownshoes I just tested in cad, and didn't get an error message for removing all ofi resources. What dataset what this on?

**Comment by Mbrownshoes** [comment]
@jrods I just tried again using the test editor account and was unable
/api/ofi/remove_ofi_resources 500 ()

test-ofi-visibility
and
secure-ofi-test
