### ISSUE TITLE
The process for deleting a single resource can cause the user to unintentionally delete all resources (all environments)

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#302]
**Steps**

1. Find a resource in a record you intend to delete.  _These must be Geographic Data OFI Records._
2. click 'Edit' from the dropdown.

![screen shot 2017-03-07 at 8 57 18 am](https://cloud.githubusercontent.com/assets/3906047/23668574/5fb1c91e-0316-11e7-8246-9c955854b0af.png)

**expected**
I would be taken to the page to edit that particular resource (and delete it).

**actual**
I get a pop-up context window containing buttons 'Delete', 'cancel' & 'edit'

![screen shot 2017-03-06 at 4 58 33 pm](https://cloud.githubusercontent.com/assets/3906047/23668598/702de8ea-0316-11e7-84a0-5088efa7e0e4.png)

* The 'Delete' button, if clicked will delete all resources, not the one I have selected to edit.
* The 'edit' button takes me to another pop-up window and allows me to edit all OFI resources simultaneously
* The 'cancel' button takes me to the page to edit the resource I selected to edit.

@Mbrownshoes

**Comment by kfishwick** [comment]
@Mbrownshoes  the approach to OFI managed resources was that they would be managed as a group, not individually.  We want to go back and change that now?
