### ISSUE TITLE
OFI Data Resource names lack cardinality

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#306]
*Steps:*

1. Navigate to a record with generated OFI resources and click on 'More Information'

![screen shot 2017-03-10 at 2 06 31 pm](https://cloud.githubusercontent.com/assets/3906047/23815031/df88c350-059a-11e7-9fa5-238b72527dab.png)

The Information page is displayed for the resource

**Expected:**
The resource navigation widget will identify the different resources available to review

**Actual:**
The titles are all the same

![screen shot 2017-03-10 at 2 02 12 pm](https://cloud.githubusercontent.com/assets/3906047/23815088/3f101148-059b-11e7-97ef-de666d4b1546.png)

**Comment by kfishwick** [comment]
Please provide an alternative naming convention ...again as related to issues 302 and 305, we were intending to manage OFI resources as a group, not individually.  Perhaps we need to look at visualizing them as a group rather than individual resources, or as has been requested, address them individually once they are created.

**Comment by Mbrownshoes** [comment]
@dkelsey @ll911 how about just 'CSV Resource' or 'CSV Resource - Additional Information'?

**Comment by dkelsey** [comment]
Remove 'Additional Information...' please.

![screen shot 2017-04-06 at 1 17 57 pm](https://cloud.githubusercontent.com/assets/3906047/24774224/ff70179e-1acc-11e7-9ef5-614848f15397.png)
![screen shot 2017-04-06 at 1 26 40 pm](https://cloud.githubusercontent.com/assets/3906047/24774233/08e7d41a-1acd-11e7-9df2-a8d027678ab7.png)

@Mbrownshoes

**Comment by Mbrownshoes** [comment]
But do we need to differentiate these from normal csv files that are uploaded to the catalogue and can be downloaded directly (and have preview and api availability)? I think it's good to have some sort of differentiation.

**Comment by dkelsey** [comment]
some ideas for differentiating these, add:
* `from DWDS`
* `in DWDS`
* `DWDS extraction`

**Comment by Mbrownshoes** [comment]
DWDS is kind of cryptic. I don't think anyone knows what that is outside databc.
@gjlawran any ideas on how to differentiate these, or do we need to? I thought differentiation would be good since the UI for these ofi resources is quite different than a csv file uploaded to the filestore..

**Comment by jrods** [comment]
Maybe something like 'Order {format} Package'?

**Comment by Mbrownshoes** [comment]
@dkelsey @gjlawran shall we just leave the name as the resource type:
'csv resource' 
or 
'Access csv'
?

**Comment by dkelsey** [comment]
@Mbrownshoes  and I were discussing this.

We arrived at the following:

**ArcView Shape** - _from Geographic Warehouse_
**CSV** - _from Geographic Warehouse_
**GeoJSON** - _from Geographic Warehouse_
**ESRI File Geodatabase** - _from Geographic Warehouse_

- The  _from Geographic Warehosue_ indicates to users where the file is coming from.  The contributes to the M.O.W. making sense.
- It also means that different resources are distinguishable in the Resources list - i'm referring to the one on the resource page, not the one on the metadata record page.

**Comment by jrods** [comment]
I tested in cad, it's now using the new name.

**Comment by dkelsey** [comment]
I created a new Geographic dataset and added OFI resources.
They are name as described above.
