### ISSUE TITLE
Retiring E00 and GeoRSS, need to remove from OFI and add Geojson

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#307]
@ll911 @dkelsey As planned #213, we are ready to retire E00 and GeoRSS and add Geojson as an option for download. @jrods are you able to remove these add add the new one? What do you require in order to configure the new type?

**Comment by jrods** [comment]
When creating OFI resources in ckan, the first call to DWDS is to get the available file formats and populate resources based on the returning file formats. No configuration is needed within ckan.

However, existing OFI resources will need to be updated manually by deleting the OFI resources first, then recreate the OFI resources.

**Comment by Mbrownshoes** [comment]
@jrods great. We've been manually deleting these but have to do a few more. tks
