### ISSUE TITLE
Update Postgres to 9.5.x

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#309]
The current postgres database is at the end of life. @ll911 suggests we upgrade to 9.5.x

**Comment by jrods** [comment]
I'm testing this as part of issue #298

**Comment by jeff-at-h3** [comment]
part of the rebasing 2.7 work - will be closed when #298 is closed

**Comment by dkelsey** [comment]
@ll911 what is the version of postgres in CAT?

**Comment by dkelsey** [comment]
@ll911 what is the version of Postgres is now deployed to PROD?

**Comment by ll911** [comment]
9.6.6
