### ISSUE TITLE
Comments not showing up + javascript error.

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#310]
The dataset in question is:

https://catalogue.data.gov.bc.ca/dataset/aquifer-vulnerability-to-saltwater-intrusion-pumping-hazard

![screen shot 2017-04-03 at 9 27 46 am](https://cloud.githubusercontent.com/assets/3906047/24620179/88d9065e-1851-11e7-9036-d5c760cc3ae0.png)

@Mbrownshoes

**Comment by Mbrownshoes** [comment]
@dkelsey have you tested in test as well? Please add that to the ticket. 
There's also 2 records this is affecting.

**Comment by dkelsey** [comment]
I attempted to test this in test and Delivery.  I added a comment but could not see how to get them approved.  Are there datasets in TEST that have comments?

**Comment by garrettH3S** [comment]
@dkelsey This seems to be an error in the configuration of the commenting system. `disqus.name`, or `edcdisqus.forum_name` has been modified in the .ini file, or they have been changed in the disqus admin pages.

**Comment by jeff-at-h3** [comment]
@garrettH3S is this fixed now?

**Comment by ll911** [comment]
it's not changed since day 1
https://bccatalogue.disqus.com/

**Comment by garrettH3S** [comment]
@ll911  Has anyone changed the settings in the disqus admin panels?

**Comment by dkelsey** [comment]
not me.

**Comment by ll911** [comment]
not I'm aware of.

**Comment by dkelsey** [comment]
@garrettH3S  is this fixed?  Do you have a test case in **CAD**?

**Comment by garrettH3S** [comment]
@dkelsey  Working in CAD. @ll911  Can you check the disqus moderation portal for my comment? 
![jan-16-2018 08-23-45](https://user-images.githubusercontent.com/14841506/35003122-b21f8218-faa0-11e7-8aed-2b3c26f27a12.gif)

**Comment by dkelsey** [comment]
I emailed Leo Monday Feb 19 2018 asking if I have the correct credentials.

**Comment by dkelsey** [comment]
Looking into the config (`ckan.ini`) it seems the forum is called `bccataloguet`
I don't see that in the disqus console when I log in.  I only see `bccatalogue`
I've asked @ll911 and @gjlawran in an email if they know of the correct account to use.

**Comment by hleckenb** [comment]
Commenting and user feedback on datasets and resources will be part of UX exercises to determine what users expect and what the business needs.
