### ISSUE TITLE
UI change for OFI resource creation

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#312]
A number of editors are having difficulty with the creation of geographic records, following the implementation of the OFI.
 
**Problem**
Editors are encouraged to start creating metadata records before resources have been configured for download.  However, the OFI only auto-creates resources with object names that have been configured for download.
 
Current workflow
When an editor is creating a draft record and they click ‘Add Data’ (after having added an object name), the following is displayed:
 
![image001](https://cloud.githubusercontent.com/assets/3362533/24725581/52488e66-1a04-11e7-9c2c-fc5d7ef34356.png)

Since the object has not been configured for download, the resources can’t be created. Clicking on cancel directs them to the normal resource creation page
This is problematic because:
- Here a file or url has to be added, but in most cases editors of geographic datasets only want the OFI resources – which they can’t create yet.
- If they exit out of here they will have created a record without any resources which are easy to lose because they don't show up as draft records in the datasets page and are not searchable.
- If they do create a temporary resource by linking to our restricted access page, it will have to be deleted when we add the real OFI resources, meaning this just adds extra work and a potential cause of confusion. 

**Solution**
 
Editors needs to be able to make geographic records without resources.  Thus, when an editor is creating a geographic dataset with an object name that has yet to be configured for download, they should be able to save a record after completing the first record creation page, without having to add data. These draft records should be searchable only for logged in editors of the record's branch.
 
The allow for this, please Add a ‘Save Dataset’ button at the bottom of the first record creation page which will create the new resourceless dataset.

**Comment by Mbrownshoes** [comment]
@ll911 @dkelsey a further question is how should the OFI resources get created. It would be nice to have a job that ran nightly and populated resources for objects that have been configured, but there should still be this button on the manage resource page:

<img width="518" alt="screen shot 2017-04-05 at 2 30 05 pm" src="https://cloud.githubusercontent.com/assets/3362533/24727980/f0bafc02-1a0c-11e7-9dd5-476b2613d171.png">

Except it should say 'Add Geographic Warehouse' resources or something other than 'OFI'.
thoughts?

**Comment by Mbrownshoes** [comment]
@jrods I'm not seeing a 'Save Dataset' button at the bottom of the first page of the geographic create dataset page. Was this feature added?

**Comment by jrods** [comment]
odd, can you show a screenshot? @Mbrownshoes

**Comment by dkelsey** [comment]
@jrods, @Mbrownshoes and I were chatting about this.  We would like
 ![screen shot 2017-04-19 at 11 26 01 am](https://cloud.githubusercontent.com/assets/3906047/25195588/ed293a04-24f2-11e7-9318-bc035699b03b.png)
to say:  `Manage DWDS Resources`

**Comment by dkelsey** [comment]
@jrods only Geographic Datasets should be allowed to be created without resources.  All other record types should still require at least one resource.

**Comment by dkelsey** [comment]
@jrods There's an issue with saving metadata records without resource.
The `Save Dataset` button on the first page of the Geographic Dataset creation process works correctly.
If you instead press the `Next: Add Data` button your are taken to the 'Add data to the dataset' page.
if you don't add data there is a `Previous` button.  
When I click that i'm taken back to the previous page.
Now, clicking the `Save Dataset` button does not save the dataset.
Instead I'm taken to the 'Add data to the dataset' page

We should be able to navigate back to the first page, and click `Save Dataset` and have the dataset saved without resources.
@Mbrownshoes

**Comment by jrods** [comment]
@dkelsey the reason why that happens is because when you click the 'save dataset' button first, it creates the dataset. So when you go back, the dataset you just create doesnt get delete or anything, it still exists. Now when you click the 'save dataset' button again it goes the normal route because the dataset exists and uses the normal path for new datasets. This is because the new function that allows for skipping the add data step doesn't consider updating existing datasets, so it takes the path of using the ckan core methods.
The dataset still gets saved either way, but I know the UX is janky, but changing the workflow for dataset creation moves way greatly from core ckan.

**Comment by dkelsey** [comment]
@jrods I don't imagine editors will proceed to the "add data page" and "go back" without adding a resource, with any regularity.  However, If they make an error or are confused and do so, there is nothing that indicates the record has been saved, and at that point they are caught in a loop where it appears they can't save the record or finish until they add a resource..   I'll leave it as is but I don't like it.

**Comment by dkelsey** [comment]
Creation of Geographic Datasets works.  I created the following without a resource.

https://catalogue.data.gov.bc.ca/dataset/testing-1-6-5-release-dk
