### ISSUE TITLE
OFI orders for the entire province should not send a bounding box parameter.

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#313]
When a user attempts to download a non-spatial BCDC dataset via an OFI resource the orders and failing to supply any data. This is because when an order is made the bounding box of the entire province is sent to the distribution service, and since the dataset does not contain a spatial component, no features are found within that bounding box. 

For OFI orders made using the default full province view, a bounding box (AOI type) of '0' and no coordinates (leave blank) should be passed to return the entire table.

@jrods can you investigate how much work would be involved in making this change. Would be nice to include it in the 1.6.5 release.

**Comment by kfishwick** [comment]
@Mbrownshoes  please confirm that aoi type of 0 and null coordinates will mean "return the entire province" if the dataset is spatial and "return everything" if the dataset is non-spatial.

**Comment by jrods** [comment]
@Mbrownshoes PR #347 is in cad now, will you be able to confirm that the payload being sent for orders are in fact non-spatial in DWDS?

**Comment by Mbrownshoes** [comment]
@jrods this seems to be working. We can order non-spatial resources.

**Comment by dkelsey** [comment]
I had to hunt to find a test case.  That and distribution was down.
Found a case (I think)
https://catalogue.data.gov.bc.ca/dataset/geographic-feature-code-catalog

I was able to download a `csv` of this and it had data.
