### ISSUE TITLE
Geographic draft records without resources should be viewable to branch editors.

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#323]
related to #315 
Now that draft geographic records can be saved without resources, we would like these records to be indexed and viewable to branch editors - similar to other draft records. This will allow editors to find the draft records they have created and continue working on them. 
These records should appear here:
![screen shot 2017-04-26 at 9 26 18 am](https://cloud.githubusercontent.com/assets/3362533/25445115/5a48655a-2a62-11e7-8316-fe66b8b5ccf3.png)

**Comment by jrods** [comment]
@Mbrownshoes  @gjlawran Is there any reason for datasets to have their state set to 'draft'? (not edc_state)
If a dataset's state is 'active', then it can be indexed to be viewable on the branch organization view.

Continuing with #315 i can have those datasets that are saved to have an 'active' state when created.

**Comment by Mbrownshoes** [comment]
@jrods is the only time  'state' = 'draft' when a record doesn't have a resource? Seems that way as draft records with resources have states of active. If that is the case than yes, let's make the save active when you save it without a resource.

**Comment by jrods** [comment]
@Mbrownshoes yes that is the case, I can submit a PR to have resource-less datasets be set to active when saved

**Comment by jrods** [comment]
@Mbrownshoes I've tested in cad, the datasets are now active when saving a dataset without resources, but it doesn't show in the org branch list, how often does solr re-optimize? 

@ll911

**Comment by ll911** [comment]
It doesn’t get re-optimize in CAD. It’s on demand.

**Comment by Mbrownshoes** [comment]
@jrods I indexed a record I just created without a resource and it is visible to branch editors

**Comment by dkelsey** [comment]
I created a Geographic Dataset without a resource 
https://cat.data.gov.bc.ca/dataset/testing-geographic-dataset-with-no-resource-dk
Mat created one in the demo:
https://cat.data.gov.bc.ca/dataset/show-and-tell

Both are visible to members of the organization, though both have no resources.

**Comment by dkelsey** [comment]
I created a dataset without a resource:

https://catalogue.data.gov.bc.ca/dataset/testing-1-6-5-release-dk

after 10 mins it was indexed and visible when logged in as another member of JTST. (dbcuser2)
