### ISSUE TITLE
remove kml format from geoview

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#325]
We are adding kml resources to geographic records, but since they are network links are wrappers for wms calls to be used in Google Earth they don't show in the preview and all the user sees is a map preview zoomed out to shoe the entire earth. Please remove kml in the ini from this line.

ckanext.geoview.ol_viewer.formats = wms **kml** wfs gft
@ll911 so we need @jrods to make this change to the deliver ini first?

**Comment by jeff-at-h3** [comment]
@ll911 , what is the status of this issue

**Comment by ll911** [comment]
this is done.
