### ISSUE TITLE
Turn off the dataproxy so external resources are not previewed

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#336]
The data proxy is not actively maintained https://github.com/okfn/dataproxy and is unreliable. As such we would like to turn off the data proxy and data explorer preview for external resources. If a csv is file is stored externally there would be no preview at all (similar to internal xlsx files).

**Comment by jrods** [comment]
@Mbrownshoes can you provide some example resources that are doing this?

**Comment by jrods** [comment]
My understanding is that Dataproxy is a service you have to setup with google app engine. 
CSV files that are external, for example, should be using the datastore api.

@ll911 do you know anything about Dataproxy being used in cad, cat or prod?

**Comment by jrods** [comment]
It looks like the recline.js in ckan uses a hardcoded url to jsonpdataproxy.appspot.com

**Comment by jrods** [comment]
@Mbrownshoes so there's no 'Off' switch for dataproxy. What happens is some resource views, for example, use the recline view. In ckan, if the resource has datastore_active set to false, the js module that renders the resource view, tries to use dataproxy. 

One option is like we do for xlsx resources, not display the resource preview for resources that have a size of 0 or datastore_active set to false. But the problem i can think of with this option is if the resource preview doesn't rely on the datastore at all and is an external resource, but still has some sort of resource view to display. I'm not sure how common this scenario is.

Also there is no mechanism to stop default resource views from being created without modifying the action that creates resources from core ckan.

**Comment by ll911** [comment]
@Mbrownshoes @jrods dataproxy is bundled in ckan and hardcoded in ckan core using https://github.com/okfn/dataproxy hosted by GCE

**Comment by jrods** [comment]
@ll911 dataproxy is not a module of ckan, compared to something like datastore or resource_proxy, it's only referenced in js code, from my analysis.

**Comment by ll911** [comment]
@jrods yup, it's not a module of ckan but external api that recline view use.

**Comment by kfishwick** [comment]
@Mbrownshoes  and @ll911  we are looking still for your feedback to these comments:
"One option is like we do for xlsx resources, not display the resource preview for resources that have a size of 0 or datastore_active set to false. But the problem i can think of with this option is if the resource preview doesn't rely on the datastore at all and is an external resource, but still has some sort of resource view to display. I'm not sure how common this scenario is.

Also there is no mechanism to stop default resource views from being created without modifying the action that creates resources from core ckan."

**Comment by Mbrownshoes** [comment]
@kfishwick @ll911 @dkelsey Sounds like we turning it off id datastore_active = false works. We know this will disable some previews that work for external resources, which is fine. We don't like the inconsistency of it only sometimes working for these resources. We'd rather they upload their data to the filestore

**Comment by ll911** [comment]
@Mbrownshoes @jrods @banders @dkelsey  this seems disabled the remote resource view which required by API console when source are hosted in Github
[CAT not working](https://cat.data.gov.bc.ca/dataset/physical-address-geocoding-web-service/resource/a15a8dcf-a5c6-445d-9538-138b0adfec4c)
[PROD working](https://catalogue.data.gov.bc.ca/dataset/physical-address-geocoding-web-service/resource/40d6411e-ab98-4df9-a24e-67f81c45f6fa)
both resource from https://raw.githubusercontent.com/bcgov/api-specs/master/geocoder/geocoder.json

**Comment by Mbrownshoes** [comment]
@kfishwick this change has been rolled back. I'm going to keep this as an open issue while we work on implementing @ll911 external proxy.

**Comment by ll911** [comment]
@BK01 any test [CAD](https://cad.data.gov.bc.ca/dataset/geocoder/resource/8f0b70e1-5a9f-45d7-b44e-8ae5637e8cef/view/37aa420c-44f8-4425-abf1-2d7f1567d63a)

**Comment by BK01** [comment]
Test successful. 2 consoles built (1x open, 1x gated) using JSON files hosted in the api-specs GitHub repo.

**Comment by mdunhamwilkie** [comment]
closing this since @ll911  has fixed the problem.
