### ISSUE TITLE
remove 'external link' text next to resource name of external resources

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#337]
Currently resources that are stored outside the filestore have external link next to the resource name e.g.
ArcView Shape - from Geographic WarehouseArcView Shape (external link)
We would like to remove this for these resources. For resources in the filestore the size of the file should still appear.

**Comment by dkelsey** [comment]
I looked at this using all 4 different metadata recordset types.  
* for existing and new OFI resources _(from Geographic Warehouse)_ appears
* for files, such as CSV . _(file size)_ eg _(118.1 KiB)_
* all else, nothing appears
