### ISSUE TITLE
remove the url link on geographic record resources

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#338]
The url on geographic resources sends users to the mow and cannot be copied and used to download a file directly, as it can for filestore resources. Thus, for these resources we would like to completely remove this link to remove a source of potential confusion. 

![screen shot 2017-05-30 at 2 26 11 pm](https://cloud.githubusercontent.com/assets/3362533/26605848/78adf968-4544-11e7-8624-ad712beae590.png)

**Comment by kfishwick** [comment]
@h3devin  can you please provide analysis for this?

**Comment by h3devin** [comment]
@kfishwick This should be a simple change - just need to tweak the resource read template and hide the URL when the package type is Geographic.

**Comment by jrods** [comment]
FYI, the datasets that have OFI resources, will have a param called 'ofi', you can use this param to do an if statement in templates for OFI specific resources.

**Comment by dkelsey** [comment]
tested this with [points-of-well-diversion-licences](https://catalogue.data.gov.bc.ca/dataset/points-of-well-diversion-licences)
passed.
