### ISSUE TITLE
Incorporate recent ckan patches

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#339]
http://docs.ckan.org/en/ckan-2.5.5/changelog.html

**Comment by kfishwick** [comment]
I just want to confirm our patch approach:
 - H3 will pull in changes from ckan v 2.5.5 to https://github.com/HighwayThree/ckan
 - H3 will perform merge conflicts, review modifications (we have custom changes in ckan core to support mime type & resource file sizes - we need to make sure we retain these modifications)
 - H3 will do a PR to bcgov/ckan
 - H3 will do a manual deploy

@ll911  and @Mbrownshoes  does this sound correct?

**Comment by ll911** [comment]
@kfishwick once you merge the [bcgov/ckan](https://github.com/bcgov/ckan], you can update [Jenkinsfile](https://gogs.data.gov.bc.ca/bcdc/deployment/src/master/cad/Jenkinsfile#L6) to update the ckan core brancn, then [build this](https://cis.data.gov.bc.ca/job/bcdc/job/BCDC/).

**Comment by jrods** [comment]
@Mbrownshoes cad has now been updated with ckan 2.5.5 patches

**Comment by ll911** [comment]
@jrods where is the pull request for ckan core change? https://github.com/bcgov/ckan/pulls, i created the branch, but did not see pull for 2.5.5

**Comment by dkelsey** [comment]
@kfishwick  I've run automated tests agains TEST.  Are there some specific test that can be done to verify we have not missed anything?

**Comment by dkelsey** [comment]
I see the merge by @jrod.  [Pull request 15](https://github.com/bcgov/ckan/pull/15)
