### ISSUE TITLE
Change 'Manage OFI Resources' button label

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#343]
Let's remote the OFI reference. 

![screen shot 2017-06-05 at 11 28 02 am](https://cloud.githubusercontent.com/assets/3362533/26797576/3079d0b6-49e2-11e7-9b14-9cc54987e8de.png)

Was thinking we could label the button as:
'Manage Geographic Warehouse Resources' but if that's too long it could be
'Manage BCGW Resources'
@ll911 @dkelsey

**Comment by dkelsey** [comment]
Looks fine in TEST.

**Comment by dkelsey** [comment]
I reviewed a DRAFT record https://catalogue.data.gov.bc.ca/dataset/child-care-map-data
