### ISSUE TITLE
turn off kml preview for kml resources

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#346]
All geographic records will have kml resources automatically added. the resource is a loader file for which the geo view preview doesn't work:
e.g.
https://openmaps.gov.bc.ca/kml/geo/layers/WHSE_WATER_MANAGEMENT.GW_AQUIFERS_CLASSIFICATION_SVW_loader.kml

Since the preview doesn't work we're thinking of turning off the preview for all kml resources. The impact of course will be that kml resource that the preview does work for will also stop working.
e.g. 
https://catalogue.data.gov.bc.ca/dataset/bc-public-libraries-systems-branches-and-locations/resource/9ce9e05c-4a53-415a-9ed9-e13730e833b7

The options are to turn off the preview for all resources or modify the extension to exclude the preview for resources with this link: 'ttps://openmaps.gov.bc.ca/kml/geo/layers/...' 
Thoughts?

**Comment by ll911** [comment]
@Mbrownshoes when do you need to turn it off? did you send the comms out?

**Comment by Mbrownshoes** [comment]
@ll911 @kfishwick  will disable in cad now by modifying ini file. Think a restart may be required.

**Comment by Mbrownshoes** [comment]
@ll911 does the ini need to be manually changed for cat as well?

**Comment by Mbrownshoes** [comment]
@ll911 can you update the cat ini to remove the kml preview

**Comment by Mbrownshoes** [comment]
@ll911 interesting, it seems kml resources have to be re-added (remove and then add link) in order for the preview to disappear.

**Comment by dkelsey** [comment]
How do I test this?
https://catalogue.data.gov.bc.ca/dataset/bc-public-libraries-systems-branches-and-locations-2016/resource/9ce9e05c-4a53-415a-9ed9-e13730e833b7
I see a preview for that resource.

**Comment by ll911** [comment]
here is the current geoview flag, i think old view still exist until deletion, you can delete the view and add kml see if kml preview auto created, if auto created then we may still have problem.
```ckanext.geoview.ol_viewer.formats = wms wfs gft```

**Comment by Mbrownshoes** [comment]
Yes, this is correct. New kml resources don't show a preview but old ones still do. The main reason we removed the preview because the preview didn't work for all the network kml previews added. Preview did still work for uploaded kml files. I don't think we need to remove the previews for the uploaded files since they work..

**Comment by Mbrownshoes** [comment]
@dkelsey I tested this by creating a new kml resource and saw the preview did not show.

**Comment by dkelsey** [comment]
@Mbrownshoes  Is the process to create a `KML` resource simply to upload a `KML` file?

**Comment by Mbrownshoes** [comment]
I just did that to test, but the script that populates the wms resource also populates the [kml now](https://catalogue.data.gov.bc.ca/dataset/regional-geochemical-survey-data/resource/847e96ef-de58-484a-9c70-19da0d05856d). I've run it on about half the geographic records but need to run it on the rest.

**Comment by webgismich** [comment]
I hope this wouldn't be uploading a KML file .. but rather referencing a KML at an URL link.
aka.. http://openmaps.gov.bc.ca/kml/geo/layers/WHSE_LEGAL_ADMIN_BOUNDARIES.ABMS_REGIONAL_DISTRICTS_SP_Loader.kml
