### ISSUE TITLE
API console not working for remote resources

### ISSUE THREAD

**Issue by ll911** [bcgov/ckanext-bcgov#360]
API console when source are hosted in Github, see following
[CAT v1.6.6 not working](https://cat.data.gov.bc.ca/dataset/physical-address-geocoding-web-service/resource/a15a8dcf-a5c6-445d-9538-138b0adfec4c)
[PROD v1.6.5 working](https://catalogue.data.gov.bc.ca/dataset/physical-address-geocoding-web-service/resource/40d6411e-ab98-4df9-a24e-67f81c45f6fa)
both using remote resource from https://raw.githubusercontent.com/bcgov/api-specs/master/geocoder/geocoder.json

**Comment by Mbrownshoes** [comment]
@ll911 I'm going to set up datastore_active = true to turn back on the proxy for external resources
https://github.com/bcgov/ckanext-bcgov/issues/336#issuecomment-309560509 
@kfishwick

**Comment by Mbrownshoes** [comment]
@kfishwick there was actually no change to the ini file needed. I just removed the last change @jrods had implemented, so external resources should preview. I will trigger a rebuild now.

**Comment by ll911** [comment]
i think the dataproxy api needs to be added in ini file as parameter and should not be hard code in ckan like the default gceapp.

**Comment by Mbrownshoes** [comment]
@kfishwick @ll911 api console is working in Cad.

**Comment by ll911** [comment]
@Mbrownshoes @dkelsey this is working as well

**Comment by ll911** [comment]
fixed with https://github.com/bcgov/ckanext-openapiviewer/releases/tag/2.0.0
