### ISSUE TITLE
replace dataproxy used by the datapusher/datastore

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#362]
We'd like to replace the dataproxy used by the datapusher/datapusher to preview external resources with an inhouse dataproxy: https://gogs.data.gov.bc.ca/bcdc/dataproxy

The configuration for the dataproxy should be stored in the ckan.ini file. 
@ll911

**Comment by jeff-at-h3** [comment]
needs analysis to determine strategy for dataproxy and whether we can leave it alone safely

**Comment by mdunhamwilkie** [comment]
It's been decided to remove the proxy - only allow files that have already been pushed to the datastore to be previewed.  There will be a new ticket (or set of tickets) for this.
