### ISSUE TITLE
timezone is not indicated for last modified on resource page.

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#369]
**TESTCASE**
as a user when I look at a resource page when I read the **Last Modified** field there is not indication of what timezone the date/time is in

**EXPECTED**
I'd clearly see `GMT`

**ACTUAL**
no indication of what timezone the date/time is in
![no-timezone](https://user-images.githubusercontent.com/3906047/32399882-3303e49c-c0b7-11e7-9a5e-42c0fe3b174b.PNG)

**Comment by garrettH3S** [comment]
@dkelsey  Is this a duplicate of https://github.com/bcgov/ckanext-bcgov/issues/188.

**Comment by dkelsey** [comment]
@garrettH3S yes it is a duplicate.  If it is straight forward to determine the timezone the user is in and present the data in the correct time-zone then  i'm happy. else simply indicate the time in in GMT.

**Comment by garrettH3S** [comment]
@dkelsey  This is already implemented, see #188

**Comment by dkelsey** [comment]
Duplicate
