### ISSUE TITLE
Navigating back from a selected sub-organization does not correctly return the user to the parent organization in the Organizations page.

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#370]
**TESTCASE**

- Starting from [Organizations/](https://catalogue.data.gov.bc.ca/organization) I click on the '+' symbol next to **Ministry of Forests, Lands, Natural Resource Operations and Rural Development**
  - The misc suborganizations are displayed.
- I click on [Archaeology (8)](https://catalogue.data.gov.bc.ca/organization/archaeology)
- When I go back in the history...

**Expected:**

* I expect to be brought back to where I started 
  - with the **FLNRO**  Organization expanded and 
  - sub organizations listed

**Actual:**

- I'm taken back to the Organizations page but
- to the Top of the page and 
- **FLNRO** is not expanded.

**Comment by mjmcclung** [comment]
Tested this in DELIVERY and got the expected result, but only when one organization was expanded.  If more then one organization is expanded the page is returned to the top of the lowest parent organization on the page, even if a higher organization was last chosen.

**TESTCASE**

- Starting from [Organizations](https://catalogue.data.gov.bc.ca/organization)/ I click on the '+' symbol next to **Ministry of Forests, Lands, Natural Resource Operations and Rural Development**
- The misc sub-organizations are displayed.
- I click on [Archaeology (8)](https://catalogue.data.gov.bc.ca/organization/archaeology)
- I then return and click on the '+' symbol next to **Ministry of Community, Sport and Cultural Development**
- The misc sub-organizations for this Ministry are also displayed.
- I click on [Local Government Governance and Structure](https://catalogue.data.gov.bc.ca/organization/local-government-governance-and-structure)
- When I go back in the history...

**Expected:**

- I expect to be brought back to the top of the Ministry of Community, Sport and Cultural Development Organization  with this Organization expanded and sub-organizations listed.  Other Organization can be expanded, but I expect to be brought back to the top of my last choice.

**Actual:**

- I'm taken back to the Organizations page but to the Top of the FLNRO Organization.  Both Organizations are expanded to show the sub-organizations.

**Comment by dkelsey** [comment]
The initial test case described has been satisfied.
@mjmcclung I've created another ticket for your test case #462

**Comment by dkelsey** [comment]
The initial test case describe has been satisfied and verified in PROD.
