### ISSUE TITLE
Ordering data through the MOW is broken for Objects listed in AOI lookup table. 

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#371]
**TESTCASE**

| ENV  | Test Case Data |
|------|------| 
|PROD | [AirPhoto Centroids](https://catalogue.data.gov.bc.ca/dataset/airphoto-centroids)|
|TEST | [AOI selector test](https://cat.data.gov.bc.ca/dataset/aoi-selector-test)|
| DLV | search for AOI _cad is down atm_|

This is occurring with [AirPhoto Centroids](https://catalogue.data.gov.bc.ca/dataset/airphoto-centroids)
_you must be logged in to see this. it is in `DRAFT`_
The AirPhoto Centriods Object name is registered in [AOI Lookup Table](https://catalogue.data.gov.bc.ca/dataset/aoi-lookup-table/resource/d52c3bff-459d-422a-8922-7fd3493a60c2)

- Initiate an order of the `ArcView Shape` file.  You should see:
![oder airphoto centroids](https://user-images.githubusercontent.com/3906047/32632540-dbb8bb26-c558-11e7-9b5d-27b03d0d95a7.PNG)
 - fill in your valid email address and
- check the consent check-box
- click ![place_order](https://user-images.githubusercontent.com/3906047/32632617-253f7e60-c559-11e7-972f-0cf7015af6e5.PNG)

**EXPECTED**

- A notification that the `AOI` must be below the maximum.

**ACTUAL**

- The order is submitted.  
- The order eventually fails.
   - `FME` has a 2GiB output file size limit.
   - When `FME` fails no notification is ever sent to the user that their order has failed.

**FURTHER** 

- If I zoom in before submitting, I get expected behavior.

@Mbrownshoes 
@gjlawran

**Comment by jrods** [comment]
I'm still looking into this issue, but while trying to using my local env another issue arose with using ckan 2.7.

**Comment by dkelsey** [comment]
This will likely be unnecessary as we will no longer be using the OFI/MOW.

**Comment by dkelsey** [comment]
closing this.
