### ISSUE TITLE
Resource "Supplemental Information" markdown not being renderred.

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#374]
**TESTCASE**

Find a records with a CSV resource.
modify the resource adding the following to the **Supplemental Information** section:

```
_this should be a heading_ **what about this** # and - this
```

**EXPECTED**

**Supplemental Information** will appear on the resource page with those items appropriately formatted.

**ACTUAL**

![md not working](https://user-images.githubusercontent.com/3906047/33345777-5aac6674-d442-11e7-9ef2-802623b6dbdf.PNG)

**Comment by dkelsey** [comment]
This is a simple code change in:

`ckanext\bcgov\templates\package\resource_read.html`
```jinja
114          {% if res.supplemental_info %}
115          <h2>{{ _('Supplemental Information')}}</h2>
116          <p>{{ res.supplemental_info }}</p>
117          {% endif %}
```

Should be:
```jinja
114          {% if res.supplemental_info %}
115          <h2>{{ _('Supplemental Information')}}</h2>
116          <p>{{ h.render_markdown(res.supplemental_info) }}</p>
117          {% endif %}
```

**Comment by garrettH3S** [comment]
verified in CAD.
![screen shot 2018-02-05 at 9 39 28 am](https://user-images.githubusercontent.com/14841506/35819754-7cc48542-0a58-11e8-9d21-b26655f0b4e8.png)

**Comment by dkelsey** [comment]
Added markdown to [this](https://cat.data.gov.bc.ca/dataset/inter-provincial-migration/resource/8bc04574-3b36-4d22-9b36-5a177ba0bcc3) resource.
Works.

![image](https://user-images.githubusercontent.com/3906047/37227863-809ea37e-2393-11e8-937b-f40761644b1d.png)

**Comment by dkelsey** [comment]
Working now.
