### ISSUE TITLE
'EPSG_3005 - NAD83 BC Albers' not default projection on resources for geographic datasets.

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#375]
**TESTCASE**

When adding a resource to a geographic dataset projection Name must be set.
Add a resource to a geographic dataset.  You may be prompted to add OFI resources.  simply click outside the modal window or close it.

**EXPECTING**

Projection Name is defaulted to `EPSG_3005 NAD83 BC Albers` or it is listed first.

**ACTUAL**

BC Albers is not listed first in the drop-down list box.   
BC Albers is not used as a default for that field.

I did a quick audit to see what projections are used:

|Projection | Resources using it |
| -----------| -------------------------------|
|EPSG_3005 - NAD83 BC Albers| 3470|
|EPSG_4326 - WGS84 - World Geodetic System 1984 | 1343|
|EPSG_4269 - NAD83| 13|
|EPSG_3857 - WGS84 Pseudo-Mercator -- Spherical Mercator| 4|
|EPSG_26910 - NAD83 UTM zone 10N| 3|
|EPSG_26707 - NAD27 UTM zone 7N| 3|
|EPSG_26907 - NAD83 UTM zone 7N| 1|
|UTM| 1|
|EPSG_26708 - NAD27 UTM zone 8N| 1|
```

**Comment by dkelsey** [comment]
I talked to Annika about this.  She was the one who raised this. 
After she looked at the stats here she stated that a lot of these are using the wrong projection.

**Comment by webgismd** [comment]
what wrong projection is being used?

**Comment by webgismd** [comment]
yes some of those projections listed don't look quite right -   (u'UTM', 1),

and why no Zone 9? Nad83 or 27..

I wouldn't bother with 'EPSG_4269 - NAD83'  anymore..

**Comment by garrettH3S** [comment]
Verified in CAD. 
![screen shot 2018-02-01 at 8 32 51 am](https://user-images.githubusercontent.com/14841506/35690369-8b201a56-072a-11e8-9ca2-5549bedf76df.png)

**Comment by dkelsey** [comment]
The field is mandatory, yet we are propagating it with a default value.

If it remains as a manditory field I'd like the following behavior:

The default selection is blanks:
(This is the current behavior in PROD)
![image](https://user-images.githubusercontent.com/3906047/37362789-68c4bff4-26b3-11e8-882f-b7fc924b0e38.png)

When the user clicks the drop-down BC Albers is at the Top of the list.

![image](https://user-images.githubusercontent.com/3906047/37363123-5fe518a6-26b4-11e8-9f25-fbd8944f5a76.png)

**Comment by jrods** [comment]
@dkelsey delivered to cad and EPSG_3005 is always at the top of the this.

**Comment by dkelsey** [comment]
@jrods the sort works, however my request to have the default select as blank does not work.
 can we make the default 'un-selected'  so the user must make a selection.

This is a sample of what is currently in PROD::
```html
<select id="field-projection_name" name="projection_name" data-module="autocomplete" class="required">
   <option value =''  selected="selected"  disabled>Select a projection name</option>
	
   <option value="EPSG_26707 - NAD27 UTM zone 7N"
   >
       EPSG_26707 - NAD27 UTM zone 7N
   </option>

   <option value="EPSG_26708 - NAD27 UTM zone 8N"
    >
    EPSG_26708 - NAD27 UTM zone 8N
    </option>
...
```

**Comment by jrods** [comment]
@dkelsey I see, I guess I missed that, I will resubmit a PR.

**Comment by jrods** [comment]
@dkelsey fixed in cad, 'Select a Projection Name.' will now display as the un-selected option. As well, EPSG3005 is still listed as the top option.

**Comment by dkelsey** [comment]
The validation works.

**Comment by dkelsey** [comment]
Validated in PROD.
