### ISSUE TITLE
Remove redundant words from search results listing

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#380]
`ENV:` PROD, TEST, DLV

**TESTCASE**

Navigate to the search results page: https://catalogue.data.gov.bc.ca/dataset

**EXPECTED**
Effective use of space to relay information regarding Published and Modified dates.

**ACTUAL**
The words `Record` is redundant.
![redundantwordsui](https://user-images.githubusercontent.com/3906047/34131595-1ea89624-e401-11e7-8df2-451c4c325498.PNG)

**Comment by Mbrownshoes** [comment]
Having "Record' published and last modified differentiates it from a resource last modified. That's probably why it is there. This makes that clear.

**Comment by dkelsey** [comment]
I'd say we should remove it all together.  Who cares about `Record Last Modified`.  
I suspect users would be more interested in date information about the data not when someone got around to publishing it.

**Comment by garrettH3S** [comment]
@dkelsey  @Mbrownshoes  has there been a decision on what this text should say?

**Comment by dkelsey** [comment]
## This was duplicated in #472 **Remove "Record Last Modified" from display in search results**
Closing
