### ISSUE TITLE
There are two Data API buttons in Cad

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#381]
![screen shot 2017-12-19 at 5 07 43 pm](https://user-images.githubusercontent.com/3362533/34186240-58087b12-e4df-11e7-8c66-3a213137c165.png)

**Comment by Mbrownshoes** [comment]
@jeff-at-h3 @dkelsey this bug exists in test (cat) as well (v.1.7).

**Comment by jrods** [comment]
@dkelsey I'm just looking at this, and there's an issue with it, quite abit of template smell. Not sure what's going on, this may take longer than expected, probably due to the ckan update, still investigating.

**Comment by jrods** [comment]
@dkelsey this is now in cad, just go to any resource with a datastore resource and one button should now display and clicking on it will open the modal.

**Comment by dkelsey** [comment]
**TESTCASE**
* navigate to any dataset with a CSV resource (_Not and OFI resource_)
* navigate to the resource record page

**Expected**
* Only one Green API button:
![image](https://user-images.githubusercontent.com/3906047/37220569-da907618-237b-11e8-8884-c980cd5a56e2.png)

**Comment by dkelsey** [comment]
This passes.

**Comment by dkelsey** [comment]
This passes in PROD
