### ISSUE TITLE
resources for OFI records are incorrectly all caps format. Should be lowercase 

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#386]
Resource format type should be lowercase, but the OFI auto resource creation is making them ALL CAPS
https://catalogue.data.gov.bc.ca/api/3/action/package_show?id=6aa12006-5c23-4e3a-9145-29454b9ed493
This leads to duplicate formats (there are two 'csv's visible in the format search 
<img width="124" alt="screen shot 2017-12-20 at 11 46 32 am" src="https://user-images.githubusercontent.com/3362533/34225524-9b0611da-e57b-11e7-9530-a7f1bbed98a8.png">
@dkelsey

**Comment by garrettH3S** [comment]
@ll911 If you run these db scripts, that will fix the environment.
`UPDATE resource_revision SET format = LOWER(format);`
`UPDATE resource SET format = LOWER(format);`

This requires solr to be re-indexed. I'm not sure how these formats were entered into the database with different cases. The data entry point for format information is from a dropdown. 
![screen shot 2018-01-05 at 1 49 30 pm](https://user-images.githubusercontent.com/14841506/34630043-4a95995e-f21f-11e7-9618-1f4a5ce0b03e.png)

Has this recently been changed? Is there another way to add format information into the database?

**Comment by ll911** [comment]
they were added via api, not sql insert

**Comment by dkelsey** [comment]
@garrettH3S this is marked as **Code Complete**  it is fixed?

**Comment by dkelsey** [comment]
I logged in and I don't see anything.  @ll911 is there a test or delivery disqus account?

**Comment by garrettH3S** [comment]
@dkelsey  Im going to remove the two above comments since there not related to this ticket.

**Comment by garrettH3S** [comment]
@ll911 Have you ran that script in cad?

**Comment by ll911** [comment]
@dkelsey yes, you can see the config file to get the cad disqus id

**Comment by ll911** [comment]
@garrettH3S your group have full access in CAD.

**Comment by dkelsey** [comment]
@ll911  when I navigate to the disqus url for CAD I get **Whoops, you're not allowed on that page.**

**Comment by dkelsey** [comment]
i'm confused about the disqus comments.  **why are they here?**

**Comment by dkelsey** [comment]
I re-indexed in CAD and it didn't make a difference.

**Comment by dkelsey** [comment]
I used the API to update the metadata for resources that had the wrong case, setting all to lower case.
see `resource_format_Analysis.ipynb`
I re-indexed.  This resolved the 'duplicate formats' issue.  
This exposed another issue for which I'll create a ticket for.
in addition, I encountered a dataset that had an incomplete schema.
Because of the Solr failed to updated the index correctly for this record.
I added the missing schema elements, through the API, which resolved this issue.
I suspect the other issue is due to an issue Solr has with the schema.

**Comment by dkelsey** [comment]
Ran the script in PROD.
I think a re-index is required 
@ll911

**Comment by dkelsey** [comment]
There are still 2 groupings of `CSV` facets.

**Comment by hleckenb** [comment]
@jachurchill can you look into why the two CSV facets are showing up ... both are in lowercase, however, seems to be separated. Please identify what the reason is.

**Comment by jachurchill** [comment]
This can probably be closed as it will be resolved with #524
