### ISSUE TITLE
Add SPATIAL_DATA_TYPE to core BCGOV schema

### ISSUE THREAD

**Issue by jeff-at-h3** [bcgov/ckanext-bcgov#394]
From and email from NRS:

|Element|Description|Outcome|Comment|
|----|----|----|----
|Geometry Type | Point, Line, Polygon, Raster,   LIDAR | Data   BC Add | Data   BC: Would prefer to find a standardized list   Can we combine with Source Format, Spatial Datatype?

| question | answer |
|----|----|
|What is implied by _"core BCGOV schema"_?|<ul><li>There is no single _core schema_.  </li><li>We have 4 metadata schema: <ul><li>Dataset,</li><li> Geographic, </li><li>Application, </li><li>WebService.</li></ul>  </li><li>There are shared fields and some different.<br></li><li>The topic of moving to a single schema and getting rid of the 4 was raised and collected in a Github ticket: #391</li></ul>|

**Comment by jeff-at-h3** [comment]
Conversation from Meeting Dec 17
1.What do you mean by core schema? 
CN> BCGOV schema – we have spoken of rationalizing to only having one

**Comment by jeff-at-h3** [comment]
![spatial](https://user-images.githubusercontent.com/33915381/34588154-5e8b432e-f160-11e7-84c1-0d9e84d4de91.png)

**Comment by garrettH3S** [comment]
@dkelsey  How does this look?
![screen shot 2018-01-26 at 9 44 16 am](https://user-images.githubusercontent.com/14841506/35453019-835d4b88-027d-11e8-88fc-c897d7967d07.png)

**Comment by dkelsey** [comment]
This is good to see.
couple if things
* The filed is Spatial Datatype  but the values should be `sdo_geometry` or `sed_binary`, or `st_geometry`

I'm getting clarification from the NRS

* We don't want NRS in the label for the field.
* The order: the new field should come before the Object Name.

**Comment by garrettH3S** [comment]
I've updated the form and schema. Whenever @jrods reviews my pull well deploy to CAD.
@ll911 This command will need to be added to the server startup script so that the edc vocabularies are updated. 
```
## 
# Creates new vocabularys. This can be ran multiple times without recreating old vocabs.
#
paster --plugin=ckanext-bcgov edc_command create-all-vocabs -c /apps/ckan/conf/dlv.ini
```

**Comment by jrods** [comment]
@garrettH3S you'll probably have to add that paster command to the entrypoint script? @ll911

**Comment by ll911** [comment]
@jrods @garrettH3S you both can ran that directly in ocp, it only need to be ran once right?

**Comment by dkelsey** [comment]
I attempted to run the paster command in `OCP`.
@jrods @ll911 

| Q there's no environment to activate? 
| Q I simply run the paster command?

it failed with:

```
sh-4.2$ paster --plugin=ckanext-bcgov edc_command create-all-vocabs -c /etc/ckan/ckan.ini                                                                                                
Traceback (most recent call last):                                                                                                                                                       
  File "/usr/local/bin/paster", line 11, in <module>                                                                                                                                     
    sys.exit(run())                                                                                                                                                                      
  File "/usr/local/lib/python2.7/site-packages/paste/script/command.py", line 101, in run                                                                                                
    command = commands[command_name].load()                                                                                                                                              
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in load                                                                                            
    return self.resolve()                                                                                                                                                                
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2414, in resolve                                                                                         
    module = __import__(self.module_name, fromlist=['__name__'], level=0)                                                                                                                
  File "/opt/app-root/src/ckanext-bcgov/ckanext/bcgov/commands/edc_commands.py", line 28, in <module>                                                                                    
    class EdcCommand(CkanCommand):                                                                                                                                                       
  File "/opt/app-root/src/ckanext-bcgov/ckanext/bcgov/commands/edc_commands.py", line 46, in EdcCommand                                                                                  
    os.path.dirname(ckanext.bcgov.__file__),                                                                                                                                             
AttributeError: 'module' object has no attribute '__file__'                                                                                                                              

```

**Comment by jrods** [comment]
@dkelsey does adjusting the importing of the bcgov ext fix it?

```
#line 19
import ckanext.bcgov as bcgov

#line 46
os.path.dirname(bcgov.__file__)
```

**Comment by ll911** [comment]
@dkelsey no need for virtualenv activation inside OCP as you are already running inside container, it makes no sense to active another virtualenv wrapper.
you have the right syntax, i think you need try with @jrods suggestion

**Comment by dkelsey** [comment]
Thanks @ll911   I'll try your suggestions @jrods.

**Comment by dkelsey** [comment]
This passes.

**Comment by dkelsey** [comment]
I published the record and for Public users the field does not appear.
![image](https://user-images.githubusercontent.com/3906047/37489173-04fbf85a-2854-11e8-932f-8ff76928968f.png)

**Comment by dkelsey** [comment]
Working in PROD
