### ISSUE TITLE
Add number of record views and resource downloads to the record page and its search results summary

### ISSUE THREAD

**Issue by jeff-at-h3** [bcgov/ckanext-bcgov#403]
Data providers and consumers will both benefit from this intelligence.

**Comment by jeff-at-h3** [comment]
Is this analytical data? i.e. going to google analytics? 
Where do you expect to apply this info (API, front end display, etc)
CN> need to discuss
Next Steps: determine the source of the metrics (google analytics) design and develop

Dynamically display on resource page

**Comment by jeff-at-h3** [comment]
Need to determine who holds the next steps? Data BC or H3?

**Comment by jeff-at-h3** [comment]
[Mockup for BC Data Ckan issue 403.docx](https://github.com/bcgov/ckanext-bcgov/files/1624240/Mockup.for.BC.Data.Ckan.issue.403.docx)

**Comment by garrettH3S** [comment]
@ll911  For when you need to deploy to CAT and Prod. You must add this config to the .ini file.
`ckan.datasource.downloads.resource = <BCdata catalog data downloads resource_id> `
e.g., `ckan.datasource.downloads.resource = 9f5f9bb5-2ddc-4bb2-95ca-5abcba9e6388`

**Comment by cnewallbcgov** [comment]
I have confirmed that this is implemented in CAD environment reviewing [this record](https://cad.data.gov.bc.ca/dataset/mb-1-6-3-0308-mb).

Reporting Recent Views was not in scope, however we can report this info if we understand what "recent" means.  What is the measure for recent and does it have any relationship to the flame icon for some records?  Instead of recent can we specify a specific period?  X days?  Or is this more complex?

Also, the UX needs attention.  Can we please adopt the look of the following Youtube example.  https://www.youtube.com/watch?v=B33wVf4tdOA

Screenshot:
![image](https://user-images.githubusercontent.com/15148144/35990999-acc2409a-0cba-11e8-9e21-cf6fea356f9f.png)

Summary:  below the record title, the text would look like this:  XX views (XX recent)

Please advise on "recent" questions before enhancing.

**Comment by garrettH3S** [comment]
@cnewallbcgov  The recent means number of days within the last 14 days. see [here](http://docs.ckan.org/en/latest/maintaining/tracking.html).
How does this look?
![screen shot 2018-02-19 at 9 58 15 am](https://user-images.githubusercontent.com/14841506/36391451-6c08a978-155b-11e8-82d6-bba080dc6f0a.png)

**Comment by dkelsey** [comment]
Working.
![image](https://user-images.githubusercontent.com/3906047/37226666-91916a1c-238f-11e8-94c7-c1727093be1d.png)

AND
![image](https://user-images.githubusercontent.com/3906047/37226696-ac434e66-238f-11e8-92b9-9c563b017d63.png)

@cnewallbcgov do you want to review this.

**Comment by cnewallbcgov** [comment]
Fails.

The screenshots reflect first draft and do not match my expectations for this feature.

Hopefully the correct code is complete and only awaits a pull request?

Please advise.

Thanks





Sent from my smartphone.


-------- Original message --------

**Comment by jeff-at-h3** [comment]
Hi Colin,

Can you be more specific on your expectations related to the screen shot?

Thanks,
Jeff

**Comment by jeff-at-h3** [comment]
Hi

There was an email thread on this and examples in the Github ticket.  I recall Garrett sending a mockup that I approved.

Colin




Sent from my smartphone.
-------- Original message --------
From: Jeff Audette <jeff.audette@highwaythreesolutions.com>
Date: 2018-03-09 2:02 PM (GMT-08:00)
To: bcgov/ckanext-bcgov <reply@reply.github.com>, "Newall, Colin G JTT:EX" <Colin.Newall@gov.bc.ca>, Garrett Culos <garrett@highwaythree.com>, Jared Smith <jared@highwaythreesolutions.com>
Cc: "Kelsey, David M JTT:EX" <David.Kelsey@gov.bc.ca>, "McClung, Melinda J JTT:EX" <Melinda.McClung@gov.bc.ca>
Subject: Re: [bcgov/ckanext-bcgov] Add number of record views and resource downloads to the record page and its search results summary (#403)

Hi Colin,

Can you be more specific on your expectations related to the screen shot?

Thanks,
Jeff

On Mar 9, 2018, at 12:09 PM, Colin Newall <notifications@github.com<mailto:notifications@github.com>> wrote:

Fails.

The screenshots reflect first draft and do not match my expectations for this feature.

Hopefully the correct code is complete and only awaits a pull request?

Please advise.

Thanks





Sent from my smartphone.


-------- Original message --------

**Comment by jrods** [comment]
@cnewallbcgov I need some clarification on what needs to be fix (i have no knowledge of anything outside this issue thread)

First, I understand that in David's comments, that the second image fails and this mockup should be use: ![screen shot 2018-02-19 at 9 58 15 am](https://user-images.githubusercontent.com/14841506/36391451-6c08a978-155b-11e8-82d6-bba080dc6f0a.png)

Second, is the first image in David's comment pass or fail? If it's also a fail, was there a mockup made for that one?

**Comment by cnewallbcgov** [comment]
Hi Jared.


Yes. The record level mockup you shared is what is expected.

Reporting the counts in search results is out if scope, and there was no mockup for this reason.

Colin





Sent from my smartphone.


-------- Original message --------

**Comment by jrods** [comment]
@cnewallbcgov would you like to keep what's in the first image in the extension for now or do you want me to remove it?

**Comment by cnewallbcgov** [comment]
Hi

It is preferred to remove counts from search results; creeping elegance, begs testing, etc.

Can code be preserved but made inactive, e.g. commented out?

Thanks





Sent from my smartphone.


-------- Original message --------

**Comment by jrods** [comment]
Yes, I can hide it with the mockup change.

**Comment by jrods** [comment]
@dkelsey I've updated cad with the latest mockup for datasets, and removed (commented out) the display on the gallery page

**Comment by dkelsey** [comment]
Gallery looks good
Records look good too.

**Comment by jrods** [comment]
@dkelsey i didn't know the old display was added to resources, submitting a PR to fix.

**Comment by cnewallbcgov** [comment]
Confirming in CAD:
- Count info at record level - good.
- No counts in search results (Gallery?) - good.
- Counts at resource level - **not good** (was never in scope).  Thanks for removing this.

**Comment by jrods** [comment]
@dkelsey updated, Tracking summary only displays on records as showing in the mockup.

**Comment by dkelsey** [comment]
This appears to function correctly
How do I assert that the values are correct?

**Comment by cnewallbcgov** [comment]
Hi David - Garrett referenced this link above on Feb. 19.  Perhaps it helps answer your question?
http://docs.ckan.org/en/latest/maintaining/tracking.html
