### ISSUE TITLE
Improve site usage time series graph to roll up to ministry level and make more accessible

### ISSUE THREAD

**Issue by jeff-at-h3** [bcgov/ckanext-bcgov#412]
Usage stats are currently available but not easily discoverable or accessible.

Org level is too granular and needs to roll up to ministry/agency.  

COALFILE outlier needs to be dealt with in some manner

**Comment by jeff-at-h3** [comment]
Does this relate to the google analytics report? Need more clarity and likely some Ba work to design
CN> yes – that report.  Can discuss.

Next Steps
May need to be completely replaced
Perform research and outline options – Ministry team will take away and may develop internally

**Comment by mdunhamwilkie** [comment]
Closing this issue and replacing it with one that is more all-encompassing
