### ISSUE TITLE
Can't create a dataset of any type in TEST

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#417]
**ENV:** `TEST` fails, `DLV` works. `PROD` is remains at 2.5 so is excluded.

**TESTCASE:**

using Chrome Web browser fails
FireFox succeeds.

* logon to cat with privs that allow you to create datasets.
* nav to **Datasets** and click **'Add Dataset'** button.
* select any type of dataset from the drop down
* click **Create Dataset**

**EXPECTED:**

* The next page would be a form for adding more metadata.

| Type | URL |
|----|----|
|Application| https://cat.data.gov.bc.ca/Application/add|
|Dataset| https://cat.data.gov.bc.ca/Dataset/add|
|Web Service - API| https://cat.data.gov.bc.ca/WebService/add|
|Geographic Dataset| https://cat.data.gov.bc.ca/Geographic/add|

**ACTUAL**

* the URL is:  https://cat.data.gov.bc.ca/dataset/add regardless of the type of dataset selected AND
* the page is empty.

| Type | URL |
|----|----|
|Application| https://cat.data.gov.bc.ca/dataset/add|
|Dataset| https://cat.data.gov.bc.ca/dataset/add|
|Web Service - API| https://cat.data.gov.bc.ca/dataset/add|
|Geographic Dataset| https://cat.data.gov.bc.ca/dataset/add|

**Comment by ll911** [comment]
it relates to the same error #416 when serve via wsgi not pylon. there is bug in repoze.who

```
  File "/apps/cis/workspace/bcdc/bcdc-rc/src/ckan/ckan/config/middleware/common_middleware.py", line 61, in __call__
    return self.app(environ, start_response)
  File "/apps/ckan/tst/lib/python2.7/site-packages/paste/registry.py", line 379, in __call__
    app_iter = self.application(environ, start_response)
  File "/apps/ckan/tst/lib/python2.7/site-packages/repoze/who/middleware.py", line 117, in __call__
    wrapper.finish_response(remember_headers)
  File "/apps/ckan/tst/lib/python2.7/site-packages/repoze/who/middleware.py", line 177, in finish_response
    write = self.start_response(self.status, headers, self.exc_info)
TypeError: http header key must be a string
```

**Comment by ll911** [comment]
work around is run with gunicorn

**Comment by ll911** [comment]
@dkelsey please confirm

**Comment by dkelsey** [comment]
Verified that with the switch to gunicorn resolves the issues.

Every dataset type works.  was able to get to the **Create Dataset** page for each dataset type in both CAT and CAD

**Comment by jeff-at-h3** [comment]
Leo can you please validate in CAT?

**Comment by ll911** [comment]
fixed by gunicorn
