### ISSUE TITLE
dataset type facets do not function on search page 

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#418]
**ENV** TEST, DLV

**You must not be logged in**
----
**TESTCASE 1:**

* ensure you are logged out of CAT
* navigate to https://cat.data.gov.bc.ca

**EXPECTED**

* By default only **Public** datasets will be displayed:  2247 according to the selected **Public** facet.

**ACTUAL:**

* **3819 datasets found** is displayed in the search page

**NOTE** 

* same behavior occurs in CAD though the numbers are different

----
**TESTCASE 2:**

* ensure you are logged out of CAT
* navigate to https://cat.data.gov.bc.ca
* scroll down and select **Geographic Dataset** to activate that facet.

**EXPECTED**

* By default only **Public** datasets will be displayed:  2247 according to the selected **Public** facet.
* Further only **Geographic** datasets should be displayed

**ACTUAL:**

* **3819 datasets found** is displayed in the search page
* There are examples of all dataset types displayed in the search results

**NOTE** 

* same behavior occurs in CAD though the numbers are different

**Comment by garrettH3S** [comment]
@ll911 @dkelsey I can reproduce  this issue in cad. Looks like its all facet filters (query parameters in the dataset query) aren't being used. 
![screen shot 2018-01-08 at 1 45 38 pm](https://user-images.githubusercontent.com/14841506/34694010-6fb7632c-f47a-11e7-92d2-4979ae82e16b.png)

Unfortunately I cannot reproduce this bug locally.
![screen shot 2018-01-08 at 1 47 29 pm](https://user-images.githubusercontent.com/14841506/34694029-84809ea4-f47a-11e7-99fc-cd8861a2aad3.png)

**Comment by dkelsey** [comment]
@garrettH3S **DLV** is **CAD** .  I pointed out in the **ENV** section that this is occurring in **DLV**.  I should have used **CAD** I guess.
You should have access to the logfiles in **DLV** to diagnose what's going on.  I'm going to guess that somehow facets aren't being correctly passed in **DLV**

**Comment by dkelsey** [comment]
I figured out further that in **CAD** and **CAT** if you are logged in facets work.  If you are not logged in facets do not work.

**Comment by ll911** [comment]
is that expected, should the facet works regardless?

Sent from mobile




On Tue, Jan 9, 2018 at 5:04 PM -0800, "Dave Kelsey" <notifications@github.com<mailto:notifications@github.com>> wrote:


I figured out further that in CAD and CAT if you are logged in facets work. If you are not logged in facets do not work.

-

**Comment by dkelsey** [comment]
In PROD Facets work regardless of whether the user is logged in or not.  That is the expected behavior.  CAT and CAD do not work this way.  They should work the same way as PROD does now.

D

**Comment by dkelsey** [comment]
This behavior is fine on my Vagrant environment.  I suspect this is an issue with the configuration of CAT and CAD

**Comment by garrettH3S** [comment]
@ll911  Please Investigate.

**Comment by dkelsey** [comment]
Passes in TEST

**Comment by dkelsey** [comment]
Passes in PROD
