### ISSUE TITLE
Add N/A as an option for Projection Name 

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#421]
We need to have an N/A option to allow adding a non-geospatial resource to a Geographic Dataset.

**Comment by SteveChapmanBCDX** [comment]
Closing.  This option was originally added as "N/A" and then changed to "N-A".  The latter option was failing, which led to the fix at PR-765.[PR-765](https://github.com/bcgov/ckanext-bcgov/pull/765)
