### ISSUE TITLE
Selected facets are not removable in the area above search results

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#450]
**ENVIRONMENT**  `CAD`, `CAT`

**TEST CASE**

* select any facet 
* the facet will appear under the search box

**EXPECTED**

![image](https://user-images.githubusercontent.com/3906047/36748352-7675f09e-1bac-11e8-8ddf-431006fee8f6.png)

**ACTUAL**

* The facet doesn't have a remove tick box:

![image](https://user-images.githubusercontent.com/3906047/36748214-0b1e6858-1bac-11e8-9cab-6028d48e2755.png)

**Comment by jrods** [comment]
The sidebar has an icon that removes facets if selected.
<img width="783" alt="screen shot 2018-02-27 at 12 16 25 pm_edit" src="https://user-images.githubusercontent.com/5874122/36752927-787c520e-1bb9-11e8-9b6e-f706609d8129.png">

@dkelsey are you looking at making this issue an UX improvement?

**Comment by dkelsey** [comment]
@jrods  Have a look at how it currently works in `PROD`.  
This feature in CAT and CAD is not functioning as it does in `PROD`.

**Comment by jrods** [comment]
@dkelsey ahh, ok, the problem might be related to the font-icon change in ckan 2.7

**Comment by jrods** [comment]
@dkelsey delivered and verified in cad

**Comment by mdunhamwilkie** [comment]
@dkelsey, can this be closed? Appears to work fine in PROD.

**Comment by dkelsey** [comment]
indeed it is fixed in **PROD**.  
I suspect this issue was missed because of the non-standard milestone number.  
Closing
