### ISSUE TITLE
Upload of large PDF does not fail gracefully

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#464]
Relates to #365 

# ENV
**Fails in:  CAT and CAD**
**Works as expected in PROD**

|ENV | **Example Datasets**|
| --- | --- |
|**PROD**|[Test PDF](https://catalogue.data.gov.bc.ca/dataset/test-pdf)|
|**CAT**|[Test Large PDF](https://cat.data.gov.bc.ca/dataset/test-large-pdf)|
|**CAD**|[Test Large PDF](https://cad.data.gov.bc.ca/dataset/test-large-pdf)|

# TESTCASE
* add an additional resource: a PDF that is 59MB 

# EXPECTED
* the file is below the 150MB and will upload successfully

# ACTUAL:

![image](https://user-images.githubusercontent.com/3906047/37368679-2c1a6f84-26c4-11e8-9900-32fcb7ec98f4.png)
----

# MORE STEPS
* navigate to view the record the resource was added to.
# EXPECTED
* the resource that generated the error is not listed in **Data and Resources**
# ACTUAL

![image](https://user-images.githubusercontent.com/3906047/37368869-b434900c-26c4-11e8-8a7d-24698853f70b.png)

-----

# MORE STEPS
* navigate to the resource that was added
# EXPECTED
* The resource was uploaded, so the PDF preview should display correctly.
# ACTUAL
![image](https://user-images.githubusercontent.com/3906047/37369054-3770d610-26c5-11e8-8043-04531c3122f4.png)

The error is:
```
PDF.js v1.0.1207 (build: 72cfa36)
Message: Missing PDF "https://cat.data.gov.bc.ca/dataset/fd530a84-1210-4d8f-9041-d13e9df77068/resource/63a62bb5-fd20-44c4-ba64-0987d127a5f4/download/latin-lipsum_59mb.pdf".
```

**Comment by mdunhamwilkie** [comment]
In PROD I downloaded latin-lipsum142mb.pdf from https://catalogue.data.gov.bc.ca/dataset/test-pdf and then renamed it to latin-lipsum142mb_copy.pdf and added it back as a resource.  Both the upload and the subsequent viewing (PDF preview) worked as expected.  So closing the ticket
