### ISSUE TITLE
Upgrade from 2.7.2 of core CKAN to 2.7.3

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#468]
2.7.3 contains a number of fixes for Solr, minor fixes for Postgres and other minor fixes.
The complete ChangeLog is [here](https://github.com/ckan/ckan/blob/ckan-2.7.3/CHANGELOG.rst)

We should consider upgrading.

Questions:
* When?
* What are the risks/benefits?

**Comment by jeff-at-h3** [comment]
@cnewallbcgov is this something you want to look at for 1.7x? Jared figures it would be about 1 day (8 hours) work. 
Next question: @dkelsey are you looking for us to do the analysis on this? if so, is this analysis for 1.7x?

**Comment by dkelsey** [comment]
@jeff-at-h3 I created this ticket so that we're made aware of it.  I discussed this with Colin, and Jared, Leo and I discussed it.  we agree we're not going to touch this this fiscal year.

**Comment by hleckenb** [comment]
@mdunhamwilkie this came up in our scrum this morning. Would you mind taking a look at the priority of upgrading to CKAN core (to be determined which version). I believe an analysis and perhaps a workflow for updates would be a good thing to analyse. Perhaps recommend for next sprint?

Reference: https://docs.ckan.org/en/2.8/maintaining/upgrading/index.html

**Comment by SteveChapmanBCDX** [comment]
Closed.  Upgraded from CKAN 2.7.2 to 2.7.5 at [PR-759](https://github.com/bcgov/ckanext-bcgov/pull/759).
