### ISSUE TITLE
Popularity ICON missing from popular resources (in CAD/CAT, not PROD)

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#469]
# ENV
this occurs in CAT and CAD
The correct behavior occurs in PROD

# TESTCASE
## Premable
* we restrict access to resources by setting the content of the resource as a link to the following URL:  http://apps.gov.bc.ca/notice/edc/faq/ 
* This is used often across many dataset.  
* The link is clicked often so it is counted as a popular resource.
* Popular resources are indicated, visually, by a "flame" icon -- meaning this is a _hot_ resource.
## Testcase
Navigate to a dataset that has uses the FAQ url.

# EXPECTED
* A flame icon appear next to the resource description in the **Data and Resources**
![image.png](https://images.zenhubusercontent.com/58a4843351aa2c305774867d/13cace4c-b961-461c-96c3-97fc2fbf3b41)

# ACTUAL
![image.png](https://images.zenhubusercontent.com/58a4843351aa2c305774867d/112677b3-1b9f-41d8-837a-9a237e3e2b0a)

# MORE INFO

Code snippet from PROD
```html
<a class="heading resource-url-analytics" href="/dataset/strategic-land-and-resource-plans-current-generalized-view/resource/81ac45f0-e368-41ed-b257-4fb8ba25a733" title="Strategic Land and Resource Plans - Current (GENERALIZED VIEW)">
      Strategic Land and Resource Plans - Current ...<span class="format-label" property="dc:format" data-format="other">other</span>

  <!-- Snippet snippets/popular.html start -->
  <span class="popular ckan-icon ckan-icon-flame" title="225 views" 
     xmlns="http://www.w3.org/1999/xhtml">Popular</span>
  <!-- Snippet snippets/popular.html end -->
</a>
```

Code snippet from CAD
```html
<a class="heading resource-url-analytics" href="/dataset/bc-wildfire-active-weather-stations/resource/63de553f-ad73-4742-8c6c-c01b48e14598" title="Restricted Access"> 
      Restricted Access<span class="format-label" property="dc:format" data-format="other">other</span>
    
<!-- Snippet snippets/popular.html start -->
<!-- Snippet snippets/popular.html end -->
</a>
```
@cnewallbcgov

**Comment by mdunhamwilkie** [comment]
This appears to be working fine in PROD now. Closing ticket.

**Comment by dkelsey** [comment]
The issue is not occurring in PROD.  it's happening in CAD and CAT.  My concern is that when we do the next release this will stop working on PROD.
If we can find a dataset in CAT that exhibits this we can close this.

**Comment by dkelsey** [comment]
This relates to the stats collection for the TEST env. 
It is not scheduled to run and therefore there are no stats.
It is not an issue that can be introduced with the 1.7.10 release.
