### ISSUE TITLE
Add "Dataset Usage" tab to Data Catalogue banner

### ISSUE THREAD

**Issue by cnewallbcgov** [bcgov/ckanext-bcgov#474]
The "Dataset Usage" tab is available on banner bar of data.gov.bc.ca but does not currently carry over to catalogue.data.gov.bc.ca.

Screen shot of data.gov.bc.ca
![image.png](https://images.zenhubusercontent.com/5a7c85584b5806bc2bc62b7f/a3c90cf1-8113-4922-a6a1-bd382e2cdc73)

Screen shot of catalogue.data.gov.bc.ca
![image.png](https://images.zenhubusercontent.com/5a7c85584b5806bc2bc62b7f/846367d9-c23b-4bf9-8ef8-0f29a5dd9aa7)

**Comment by jrods** [comment]
@cnewallbcgov adding this link adds too many items and cause the navbar to push down, something needs to come out

![Uploading Screen Shot 2018-03-21 at 2.33.26 PM.png…]()

**Comment by cnewallbcgov** [comment]
@jrods I agree that "Data Catalogue" is redundant with the hyperlinked banner image as well as "Datasets" on the sub nav bar.  Users knee deep in the Catalogue can either of these to return to the root of the Catalogue.  So please go ahead and remove "Data Catalogue" to make room for "Data Usage".  Thanks

**Comment by jrods** [comment]
@dkelsey delivered and verified in cad

**Comment by dkelsey** [comment]
Verified in CAD

**Comment by dkelsey** [comment]
Verified in CAT

**Comment by dkelsey** [comment]
Verified in PROD
