### ISSUE TITLE
'Resource Storage Location' not set correctly for POW resources.

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#484]
# ENV
`PROD`,  `CAT`, `CAD`

### This relates to #401 
# TESTCASE
### For a Geographic Dataset that has an `objectname` with distribution configured 
* Edit the metadata record
   * click 'Resources' tab, then 'Manage BCGW Resources'
      you will be presented with **Object is available, would you like to add the resource link?** 
   * click `Yes` -> Save
     You'll see **Successfully added.**
* After the script adds the resource navigate to the resource page and scroll to **Additional Information**

# EXPECTED
* **Resource Storage Location** would be `BC Geographic Warehouse`

# ACTUAL
* **Resource Storage Location** is `BCGW DataStore`

**Comment by kfishwick** [comment]
Just confirming @dkelsey, this only occurs in dev & test?

**Comment by dkelsey** [comment]
Just checked: PROD too.

**Comment by mdunhamwilkie** [comment]
@dkelsey is this still an issue?  After adding an OFI resource I don't even see resource storage location in the metadata

**Comment by mdunhamwilkie** [comment]
@dkelsey can this be closed?

**Comment by dkelsey** [comment]
@mdunhamwilkie No.  The code still sets the value wrong.  I did a quick search of the repository and there are a number of hard-coded "BCGW Data Store" and "BCGW DataStore"

**Comment by dkelsey** [comment]
### To state this another way:
When editors use the 'Manage BCGW Resources' _widget_ is was setting `resource_storage_location` incorrectly.
This ticket was simply to correct the widget so that is uses the correct string.
Cleaning up the old, incorrect settings is another task.

### I've checked this now in PROD and it correctly sets the `resources_storage_location`
