### ISSUE TITLE
Adopt Standard Government Header on Dataset Usage Page

### ISSUE THREAD

**Issue by cnewallbcgov** [bcgov/ckanext-bcgov#487]
The Dataset Usage page has a totally different header without a search box.  Contact Leo @ll911                         re. particulars on what needs to be done.

Ref. https://catalogue.data.gov.bc.ca/data/site-usage/dataset

**Comment by jrods** [comment]
@cnewallbcgov this is a bug, the ga-report extension overrides some styling that messes up the header

**Comment by cnewallbcgov** [comment]
Steps to resolve?

**Comment by jrods** [comment]
@cnewallbcgov The fix will be applied to the bcgov/ckanext-ga-report , will have to apply ga-report specific styling rules that don't conflict with the header

**Comment by jrods** [comment]
@dkelsey delivered and verified in cad

**Comment by cnewallbcgov** [comment]
I look at CAD today and the header now appears and behaves the same as the header in the rest of the Catalogue.

**Comment by dkelsey** [comment]
The headers appear the same on both https://data.gov.bc.ca and https://catalogue.data.gov.bc.ca
