### ISSUE TITLE
Site usage get request produces "server error" 

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#492]
The site analytics URL 
https://catalogue.data.gov.bc.ca/data/site-usage/dataset

when manually trunctated like this 
https://catalogue.data.gov.bc.ca/data/site-usage/

produces server a Server Error 500

as do the other requests that the analytics extension supports
/data/site-usage#browsers_names
/data/site-usage#totals

See https://data.gov.uk/data/site-usage#totals  for working examples.

**Comment by mdunhamwilkie** [comment]
It's timing out now.  Looks like it's trying to connect to the Catalogue on a bogus port
https://catalogue.data.gov.bc.ca:54321/data/site-usage

**Comment by BrandonSharratt** [comment]
How are you getting that url? When I go to any of the links in the original issue it works fine (ish the css could use some love). The url you mention in the comment @mdunhamwilkie does time out (as expected with a bad url). But where in the program are you getting that url?

**Comment by mdunhamwilkie** [comment]
@BrandonSharratt , looks like this is fixed somehow.  Before I was getting this by just pressing the "Dataset Usage" button in the page header.  Seems to work now though.  Closing ticket.
