### ISSUE TITLE
Users with EDC_ADMIN and EDC_EDITOR do not see the States facet.

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#495]
# ENV
`PROD`, `CAT`, `CAD`

# TESTCASE
* login with the a user account that has `edc_admin`, `edc_editor` and is not a `sysadmin` in the catalogue.
* navigate to `Datasets` and scroll to the bottom of the page

# EXPECTED
* The user should see the `States` facets
![image](https://user-images.githubusercontent.com/3906047/38435214-d5f44880-3985-11e8-9f17-a32c75fdc71f.png)

# ACTUAL
* the user does not see the `States` facets
![image](https://user-images.githubusercontent.com/3906047/38435310-27bed2ca-3986-11e8-9fa8-1252a0243b01.png)

@gjlawran

**Comment by jachurchill** [comment]
@mdunhamwilkie so I have a potential fix for this, I've added a check when setting the facets that will check if the user is an admin in any organization, this isn't the most ckan way to do it as if we were to add a user as an org admin (not currently done) they would also get to see these facets. I have tested this though and it does work so we can absolutely do it if we desire.

**Comment by SteveChapmanBCDX** [comment]
With the new UI in Prod imminently, let's not do this one.  Closing as "Won't Do".
