### ISSUE TITLE
Formatting of metadata element headings  in Additional Information section is inconsistent

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#498]
The 'Purpose',  heading is an H2 format , while the Data Quality and Lineage Statement elements are Strong. These should all be consistently portrayed - Data Quality and Lineage Statements are not  children of Purpose.

![image](https://user-images.githubusercontent.com/1154765/38573609-7de0b51a-3cab-11e8-8a1a-3469299dcbb3.png)

**Comment by mdunhamwilkie** [comment]
This is still an issue in CAT: https://cat.data.gov.bc.ca/dataset/cbm-integrated-cadastral-fabric

**Comment by dkelsey** [comment]
The formatting is better.

**Data Quality** has no values set yet it appears.  i'm creating another ticket for that.

**Comment by jachurchill** [comment]
Verified in CAT and PROD
