### ISSUE TITLE
Remove hyperlinks to dataset type icons, sectors and resource formats to improve UX

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#50]
As a user I find the hyperlinks presented for each dataset in the datasets list / search pages ( http://catalogue.data.gov.bc.ca/dataset  and http://catalogue.data.gov.bc.ca/organization/[orgname])  inconsistent and confusing.  

1) When I click on a Dataset Type Icon,  I am adding  that as a facet filter to what I have filtered, 
2) When I click on the sector name (e.g. "Natural Resources") I am applying a global search - wiping out what I have already added as filters,
3) When I click  the resource type icons (w.g. WMS, CSV) - I am taken to the record.

To resolve this confusion and improve consistency - suggestion is to remove these hyperlinks and just ensure that hovertext is in place. 

Hovertext for the Dataset Type icons:
* Tabular Record
* Geographic Record
* API Record
* Application Record

Hovertext for Sectors:
* 'Sector'

Hovertext for Format icons: 
* 'Data Format'

Linked to https://apps.bcgov/int/jira/browse/CITZEDC-805

**Comment by kfishwick** [comment]
Delivered to cad.
