### ISSUE TITLE
Search for 'trapline' without quotes fails to return results.

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#503]
# ENV
 `CAT`, `CAD`

# TESTCASE
* type the word **trapline** or **traplines** in either search box and press the enter key.

# EXPECTED
* There should be search results

# ACTUAL
*  no search results.

# MORE INFO
* do the same only put double quotes around trapline: **"traplines"**
* This does return results.

# MORE TESTCASES
* search for **Parks** e: should return many results.  a: `0` results
* search for **Test** e: should return many results: a: `0` results
* search **UAT Test** returns 375 records, search **Test UAT** e: many results a: `0` results.

**Comment by dkelsey** [comment]
I suspect this is a configuration issue with Solr

**Comment by jrods** [comment]
@dkelsey So after some investigation, this maybe an issue with the behaviour using the standard query search. Jeff posted a ckan core issue to see if the behaviour has changed in newer versions of Solr. ckan/ckan#4235

In prod, using the solr syntax, eg. text:trapline or using text:park, will perform the same search. In cat this works as well.

This could be a configuration issue, but looking at older solr schemas in ckan ,the latest changes only change the schema version. With ckan's solr config.xml, in our old local env that used solr 4, we never used ckan's provided solr config.xml, only what solr provided in its packaged binaries.  I dont know what prod used, @ll911 would have to comment.

**Comment by dkelsey** [comment]
### I think I resolved the issue.  

* The previous version of Solr had default `AND` or `OR` logic that could be configured for the server.
* All queries would use the default logic if not specified.
* The previous version of Solr also allowed users to _“inject”_ the logic setting in the query at query-time, just for that query.  The syntax was:
 
```...{!lucene q.op=AND}...```
 
_this sets the logic to AND for the query…at run time/query time. the complete query is not shown_
 
This syntax has changed in the new version of Solr…The old syntax no longer works.
 
the ckanext-bcgov extension had code that injected this syntax into every query….incorrectly—_or at least the syntax now, with the new version of Solr, no longer works._
 
When we search with the query `imagery` the search being made was turned into  

```{!lucene q.op=AND}imagery```

This failed to return results.
 
I removed the injected syntax and the query succeeded and returns results.  129 in fact.  **PROD** returns 131 – My environment is from a DB dump from March.

@jeff-at-h3 
@cnewallbcgov

**Comment by dkelsey** [comment]
This works in `CAT`

**Comment by dkelsey** [comment]
Works in PROD
