### ISSUE TITLE
Links to 'Markdown Formatting" in 'Manage BCGW Resource' form do nothing

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#507]
# ENV
 `CAT`

# TESTCASE
* Login and edit [Test 1.2 Geographic Dataset](https://cat.data.gov.bc.ca/dataset/test-1-2-geographic-dataset)
* Click the **Resources** tab (next to **Edit metadata**)
* Click **Manage BCGW Resources**
  You will see a modal dialogue box:
![image](https://user-images.githubusercontent.com/3906047/39727255-d65cef40-5206-11e8-92d8-16845d18d551.png)
* click the **Edit** button.
* You will see the **Manage BCGW Resource** modal widow
* click the **Markdown formatting** link
![image](https://user-images.githubusercontent.com/3906047/39730220-33dd3784-5215-11e8-85a6-7abee5a59202.png)

# EXPECTED
*  Either a new window opens with whatever the link is supposed to go to or
* the current page is replaced by whatever the link is supposed to go to.

# ACTUAL
* Nothing happens.  Clicking the link does nothing.

# NOTE
* when editing the metadata record, clicking the **Markdown formatting** link opens a modal hint:
![image](https://user-images.githubusercontent.com/3906047/39730328-d4ec6438-5215-11e8-863e-1ff58953aebf.png)

**Comment by mdunhamwilkie** [comment]
Appears that the URL attached to the "Markdown formatting" text is pointing to the #markdown bookmark on the same page:

![image](https://user-images.githubusercontent.com/34721902/48422484-99786800-e713-11e8-934f-015a1a54a260.png)

**Comment by dkelsey** [comment]
I got blocked testing this in CAT.  I may have discovered and issue with Named User datasets.
I'm crating another ticket for this.

**Comment by hleckenb** [comment]
![image](https://user-images.githubusercontent.com/24461217/51140310-15b62700-17fb-11e9-8797-eb9ecfb9972e.png)

CAT and PROD - Note: markdown popups cannot be closed in FireFox. All pop-ups need to have a close option.

I will raise a new ticket to address this.

**Comment by hleckenb** [comment]
Verified that markdown formatting help pop up does work and meets criteria in PROD. Passed

**Comment by hleckenb** [comment]
Verified that markdown formatting help pop up does work and meets criteria in CAT. Passed.
