### ISSUE TITLE
Error message is useless when 'Resource Storage Location' is not set.

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#514]
# ENV
`PROD`

# TESTCASE
* Use any geographic metadata record (you may want to use a draft record or create a draft record)
* Add a new resource - a CSV file will do.
* Do not set a value for the **'Resource Storage Location'** field.
* Set values for all other mandatory fields.
* click the **Add** button at the bottom of the page, in order to save the resource.

# EXPECTED
* An error message that indicates that the **'Resource Storage Location'** field is missing

# ACTUAL
* a useless error message
![image](https://user-images.githubusercontent.com/3906047/40854738-397777a6-6587-11e8-9022-d94696c5aa1a.png)

**Comment by cnewallbcgov** [comment]
More evidence of the bug:

Graphic 1:  When the Resource Storage Location field value is set.  The save behaviour correctly identifies the other mandatory fields missing values.

![image](https://user-images.githubusercontent.com/15148144/40997208-bbb18b42-68b8-11e8-8d43-2ca5437c369b.png)

Graphic 2: When the Resource Storage Location field is not set and the other mandatory fields are set, the incorrect behaviour occurs - evidenced by the transient warning message in upper left screen.  The warning fades after a few seconds.  This behaviour does not resolve until a value is set.

![image](https://user-images.githubusercontent.com/15148144/40997281-f012d788-68b8-11e8-831f-cee3f104cdb1.png)

**Comment by dkelsey** [comment]
The test case passes in CAD
