### ISSUE TITLE
Parent organization cannot be determined from child organization

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#52]
As a user, when I am viewing a child organization page  (e.g.  http://catalogue.data.gov.bc.ca/organization/enterprise-data-services )  I would like to be able to see the parent organization name and have a hyperlink to it, so that I know the context of the child organization and can quickly access the parent records.

Some example CKAN templates that implement the hierarchy extension include: 

- Data.gov -
  has organized child organizations as searches that reference the parent organization - e.g. https://catalog.data.gov/dataset/food-access-research-atlas  

- Data.gov.uk 
presents a hierarchy icon (top right) that presents a window to explore the organization (publisher) hierarchy - e.g. https://data.gov.uk/publisher/health-and-social-care-information-centre

**Comment by kfishwick** [comment]
Investigate adding the parent org to the breadcrumb (need to trim it and add "...") similar to 

![image](https://cloud.githubusercontent.com/assets/5503136/16819650/4a4cc412-4902-11e6-8039-3c41a601a666.png)

The information does exist in the "Published by" row but it should also be in the breadcrumb.

**Comment by h3devin** [comment]
@gjlawran I've added the parent organization to all of the breadcrumb menus on organization pages, it looks like this (long organization names get trimmed):
![screen shot 2016-08-10 at 9 21 25 am](https://cloud.githubusercontent.com/assets/6014656/17561642/e8d078d8-5edb-11e6-8461-50ffeb598212.png)

Did you want to add the parent organization to dataset pages breadcrumb as well?

**Comment by Mbrownshoes** [comment]
@kfishwick Yes, please add the parent organization to the dataset page breadcrumb as well. We would like the name of the record removed though, since we already have the record title.
![screen shot 2016-08-16 at 10 36 44 am](https://cloud.githubusercontent.com/assets/3362533/17709684/078070cc-639f-11e6-9b4c-988d99bbb71a.png)
