### ISSUE TITLE
BCDC POW integration for mapsheet AOI parameters

### ISSUE THREAD

**Issue by hleckenb** [bcgov/ckanext-bcgov#521]
ISSUE: POW parameter call in BCDC for mapsheet's AOI fails.

POW mapsheet AOI works well in iMap through parameter call = "null".

RECOMMEND FIX:
Accommodate parameter call for POW mapsheet AOI to allow = "null" and = "".
Ensure documentation supporting POW is updated to reflect changes.

UAT:
Workflow allows user to specify mapsheet AOI without error message.
Test environment - Data resource using POW: https://cat.data.gov.bc.ca/dataset/test-1-2-geographic-dataset#edc-pow

**Comment by dkelsey** [comment]
See #590 for test case

**Comment by hleckenb** [comment]
@dkelsey please add notes to reflect where this ticket is at, as per your email.
@mdunhamwilkie release needs to be directly linked to Git Repo

**Comment by dkelsey** [comment]
This passes in PROD.
