### ISSUE TITLE
Case of resource file format  is not being consistent applied

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#524]
Because the format labels (e.g. CSV) are not being consistently applied some records are labeled with an upper case and some with lower case  which results in 2 different counts for CSV files appearing in the facet filter.  It looks like the OFI code is writing the value as upper case while regular interface code is writing values as lowercase.

[csv = 352 records](https://catalogue.data.gov.bc.ca/dataset?res_format=csv)
[CSV = 102 records](https://catalogue.data.gov.bc.ca/dataset?res_format=CSV)

**Comment by mdunhamwilkie** [comment]
@jachurchill, please review and come up with options,

**Comment by dkelsey** [comment]
@jachurchill I worked on this issue before.
Here's the ticket #386 
**resources for OFI records are incorrectly all caps format. Should be lowercase**

After completing this, some incorrectly cased facets remained.

**Comment by gjlawran** [comment]
Not sure if this is related - but now many files are being represented by multiple res_format tags - e.g. shapefiles are now being given three different format extensions SHP (original), SHAPE and ArcView Shape, there are also 3  representations of geodatabase files (fgdb, ESRI File Geodatabase, GEODATABASE_FILE). You can see the diversity in format tags quite easily via https://catalogue.data.gov.bc.ca/api/action/package_search?facet.field=[%22res_format%22]&facet.limit=100&rows=0  . Perhaps an issue with population via OFI?

**Comment by hleckenb** [comment]
@jachurchill follow up with Dave.

**Comment by jachurchill** [comment]
This has been run successfully against a dump from PROD with some changes to make it work, will touch base with @dkelsey on Monday for next steps

**Comment by hleckenb** [comment]
@jachurchill CAT same file extension types are all lower case and numbers are consolidated = pass. 
CAD all are lower case = good, but numbers haven't been consolidated. 
PROD all are lower case = good, but numbers haven't been consolidated.

Need to determine if consolidating file types is required, e.g. xls + xlsx; txt + text. Not sure if this is a UX investigation.

**Comment by gjlawran** [comment]
PROD still has both uppercase and lowercase 'CSV' resource_format tags / facets.  The human readable display handle for both tags are now lowercase, but there are still different res_format values - 'CSV' and 'csv'.
![image](https://user-images.githubusercontent.com/1154765/52128836-d5bcb580-25ea-11e9-8b70-a271d9001c8c.png)

Note these are the URLs linked to each of the lower case search facets displayed in the UI
https://catalogue.data.gov.bc.ca/dataset?res_format=csv&download_audience=Public
https://catalogue.data.gov.bc.ca/dataset?res_format=CSV&download_audience=Public

Perhaps see https://github.com/ckan/ckan/blob/master/ckan/templates/snippets/facet_list.html ?

**Comment by SteveChapmanBCDX** [comment]
I tested this issue in Prod.  It appears to be fixed.  Closing issue.

Specifically, the URL format parameter appears now to be case-sensitive:
* https://catalogue.data.gov.bc.ca/dataset?res_format=csv - PASS (returns datasets)
* https://catalogue.data.gov.bc.ca/dataset?res_format=CSV - FAIL (returns 0 datasets)
