### ISSUE TITLE
The POW fails to submit orders for Datasets that are restricted to IDIR download

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#538]
# ENV
`PROD`, `CAT`

# TESTCASE
* as a logged in user, use the POW to submit an order for a geospatial dataset that is restricted to IDIR download.

# EXPECTED
* Submission of the order should succeed; the order submission email should be received.
* the order should complete; the order completion email should be received.

# ACTUAL
* Submision fails with
![image](https://user-images.githubusercontent.com/3906047/43930238-374255cc-9bed-11e8-88f4-774288c9dba1.png)

**Comment by dkelsey** [comment]
This relates to:
PR #534 
PR #535 

# TESTCASE
For non-public download datasets, 
* Launch the POW
* copy the URL from the location bar
* decode it
* look for the `secureSite` value.

# EXPECTED
* Restricted download datasets will have `secureSite=true`
* unrestricted (Public) download dataset will have `secureSite=false`

**Comment by hleckenb** [comment]
@dkelsey please add notes to reflect where this ticket is at, as per your email.
@mdunhamwilkie please ensure this is attached to Git repo release.

**Comment by dkelsey** [comment]
# FAIL

I'm reviewing all issues first before investigating this further.  
I have sent an email requesting access to logs and asking for verification that the `secure_url` for the `ofi_api` is correct.

**Comment by dkelsey** [comment]
# PASS
As a logged in user I successfully submitted an order for IDIR restricted data.
As a public user, I was redirected to login before.  I logged in and successfully submitted an order for IDIR restricted data.
