### ISSUE TITLE
ckan.ini setting bcgov.pow.env fails to use delivery

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#539]
# ENV
`PROD`, `CAT`, `CAD`

# TESTCASE
* set the following in the `ckan.ini`
(easy enough to do this in CAD)
`bcgov.pow.env = delivery`
* restart the server
* logon to the catalogue (CAD) and navigate to a resource that represents the POW in a geographic dataset. 
* open the devloper tools and navigate to the console.

# EXPECTED
* the  console will show that `env` is set to delivery.
```JSON
...
"env": "delivery"
...
```

# ACTUAL
* env is set to the empty string
```
...
"env": ""
...
```
# NOTES
* In PROD `"env"` will be empty
* In TEST `"env"` will be "test"
* In Delivery `"env"` will be "delivery"

The value is taken from `bcgov.pow.env` in the `ckan.ini`

**Comment by dkelsey** [comment]
This relates to:

#515 
PR #536 
PR #540 
PR #541 
PR #542 
PR #543 
PR #545

**Comment by hleckenb** [comment]
@dkelsey please add your comments from your email. Provide course of action post this ticket through creating a new ticket for the backlog.

**Comment by dkelsey** [comment]
<img width="415" alt="screen shot 2018-11-21 at 10 02 29 am" src="https://user-images.githubusercontent.com/3906047/48860051-b09f0180-ed74-11e8-9872-4226b3cf0383.png">

This passes in PROD
