### ISSUE TITLE
Get error recalculating the size of order when in POW

### ISSUE THREAD

**Issue by mdunhamwilkie** [bcgov/ckanext-bcgov#552]
# ENV
`CAT`, 

# TESTCASE
* navigate to https://cat.data.gov.bc.ca/dataset/research-installations-industry-view
* select custom download
* press Access/Download

# EXPECTED
* POW screen with no errors

# ACTUAL
* Error: An error occurred recaculating the size of your Order. Error Message: An unknown error occured calculating your Order Size.
![image](https://user-images.githubusercontent.com/3906047/46682284-fecfbb00-cba1-11e8-9407-c2a9d224053a.png)

![image](https://user-images.githubusercontent.com/3906047/46682305-0becaa00-cba2-11e8-99e7-9d5ae1e8a18f.png)

**Comment by dkelsey** [comment]
The errors listed in the console were:

a 404, followed by a number of `'Access-Control-Allow-Origin'` errors.
This is because the POW is on `https://test.apps.gov.bc.ca` and the `OFI API` url is `https://apps.gov.bc.ca`

This is a configuration issue.
