### ISSUE TITLE
Error when reading/validating a download order on a new dataset 

### ISSUE THREAD

**Issue by mdunhamwilkie** [bcgov/ckanext-bcgov#554]
# ENV
`CAT`

# TESTCASE
* add a new geographic dataset https://cat.data.gov.bc.ca/dataset/mike-test-of-adding-bc-airports-2, publicly downloadable, WHSE_IMAGERY_AND_BASE_MAPS.GSR_AIRPORTS_SVW
* press Add Data button at bottom, get error saying URL already used (this is ok)
* change airports-2 to airports-3
* press Add Data button at bottom, go to next page, press the manage button and nothing happens
* go back to previous page and press Save Dataset, get error saying URL already used
* change airports-3 to airports-4 and press Save Dataset
* edit the dataset to add resources; this works (accept the ones associated with the view)
* try to do a download  

# EXPECTED
* should go to POW

# ACTUAL
* get error on POW 

![image](https://user-images.githubusercontent.com/34721902/46675229-cecceb80-cb92-11e8-9425-92dc469df448.png)

**Comment by dkelsey** [comment]
The error you are seeing is a CORS error:

![image](https://user-images.githubusercontent.com/3906047/46685293-fda28c00-cba9-11e8-9eeb-71cdd67d784e.png)

the TEST POW is requesting resources on the PROD OFI API.

**Comment by mdunhamwilkie** [comment]
Closing this ticket.  Should not be a problem if we keep TEST BCDC pointing to TEST POW/OFI
