### ISSUE TITLE
bug: cannot add OFI resources in the add dataset workflow

### ISSUE THREAD

**Issue by mdunhamwilkie** [bcgov/ckanext-bcgov#556]
Different behaviours (both buggy) in TEST and PROD

# ENV
`PROD`

# TESTCASE
* Add a new geographic dataset, specify a table that has been configured for download (WHSE_IMAGERY_AND_BASE_MAPS.GSR_AIRPORTS_SVW). Specify the table name in the appropriate column. Press the "Next: Add data" button

# EXPECTED
* You should be told that OFI resources exist

# ACTUAL
* You get a screen with a single "Manage BCGW Resources" button. This button is associated with this URL: https://catalogue.data.gov.bc.ca/dataset/new_resource/mike-test-of-adding-bc-airports-7#ofi-results but pressing it does not do anything.
* Cannot press Finish or Previous without getting an error that you haven't filled in the fields.

# ENV
`TEST`

# TESTCASE
* Add a new geographic dataset, specify a table that has been configured for download (WHSE_IMAGERY_AND_BASE_MAPS.GSR_AIRPORTS_SVW). Specify the table name in the appropriate column. Press the "Next: Add data" button

# EXPECTED
* You should be told that OFI resources exist

# ACTUAL
* You get a screen with a single "Manage BCGW Resources" button. This button is associated with this URL: https://catalogue.data.gov.bc.ca/dataset/new_resource/mike-test-of-adding-bc-airports-7#ofi-results but pressing it does not do anything.
* If you press Previous then you do go back to the previous (add dataset) page, but pressing "Save Dataset" takes you to the add a resource page.

**Comment by dkelsey** [comment]
This is simply another example of the poor quality of what was done in the past.
Before releasing this my testing uncovered unreliable behavior.  I point this out and was ignored.

I resolved this by completing the add resource form and uploading a csv.
I was able to do that.  Once the resource existed, the "Manage BCGW Resources' button functioned correctly.

**Comment by mdunhamwilkie** [comment]
was a duplicate, so closed it.
