### ISSUE TITLE
Add additional download audience choices to the "Who can download this data" field

### ISSUE THREAD

**Issue by mdunhamwilkie** [bcgov/ckanext-bcgov#562]
Currently the choices are: 
![image.png](https://images.zenhubusercontent.com/5bd88f7331161867d1965f96/e4838ce7-e52f-442a-b389-e22b1e277ed3)

We should change this to:

Public
Government (IDIR)
Government (IDIR) & Business BCeID
Named users (including applications)
Not downloadable

**Comment by jachurchill** [comment]
@mdunhamwilkie so ckan doesn't support parentheses in tags so I had to implement these without the parentheses, double checked this with @hleckenb , one further question right now the "Who can view this data?" is the same as "Who can download this data?" should view also be updated to reflect this change? 
From the API: 
>  the name for the new tag, a string between 2 and 100
>  characters long containing only alphanumeric characters and ``-``,
>  ``_`` and ``.``, e.g. ``'Jazz'``

**Comment by mdunhamwilkie** [comment]
@jachurchill , I'll create a second ticket for "who can view".  It's slightly different. As for the choices for download, please change these to

Public
Government 
Government & Business BCeID
Named users
Not downloadable

The parenthetic parts were just meant for clarity - we will accomplish this later through help text.

@hleckenb @dkelsey fyi.

**Comment by hleckenb** [comment]
@jachurchill  pull request

**Comment by mdunhamwilkie** [comment]
This works now in PROD, closing
