### ISSUE TITLE
The Contact Sub-org list blanked out when you enter a contact email address 

### ISSUE THREAD

**Issue by mdunhamwilkie** [bcgov/ckanext-bcgov#579]
# ENV
`PROD`, `CAT`, `CAD`P1: v1.7.X d564f9e

# TESTCASE
Add a geographic dataset
enter org and suborg
go to contacts section
this is what you'll see, if using Chrome with suggestion lists.
![image](https://user-images.githubusercontent.com/34721902/47858524-84ade300-dda9-11e8-8a31-c360058dccb8.png)

Enter name and email address (I selected from suggested pick list).  This is now what you'll see
![image](https://user-images.githubusercontent.com/34721902/47858437-4dd7cd00-dda9-11e8-83a0-8ead628e1f77.png)

And there are no choices available for suborg - have to select a different org and then pick the original org again to refresh the selection list  

# EXPECTED
*

# ACTUAL
*

**Comment by BrandonSharratt** [comment]
Created PR #629.

Note that this issue made me notice another related issue, where if you autofill a select2 box with multiple select2 boxes on the screen and one scrolled out of view. it will flicker back and forth between where you are and the organization box at the top of the page in this instance.

I tried updating my local copy to have the select2js from the newest master branch of CKAN as our version of select2 is quite old and that fixes this flicker issue. So it's a non issue for now

**Comment by dkelsey** [comment]
This passes in CAT

**Comment by dkelsey** [comment]
This passes in PROD
