### ISSUE TITLE
Divide Plugin/Extension Into multiple.

### ISSUE THREAD

**Issue by BrandonSharratt** [bcgov/ckanext-bcgov#586]
# ENV
`PROD`, `CAT`, `CAD`

# TESTCASE
Look at current codebase, note how it is one large package

# EXPECTED
Should be multiple plugins/extensions devoted to doing one thing and doing it well. In theory they could be the ones that the plugin itself is importing:

edc_dataset=ckanext.bcgov.plugin:SchemaPlugin
edc_app=ckanext.bcgov.forms.edc_datasets:EDC_ApplicationForm
edc_geo=ckanext.bcgov.forms.edc_datasets:EDC_GeoSpatialForm
edc_ngeo=ckanext.bcgov.forms.edc_datasets:EDC_NonGeoSpatialForm
edc_webservice=ckanext.bcgov.forms.edc_datasets:EDC_WebServiceForm
edc_disqus=ckanext.bcgov.plugin:EDCDisqusPlugin

# ACTUAL
Is one large package

**Comment by BrandonSharratt** [comment]
After digging into this more I've made slightly different modules.
1) ckanext-bcgov-disqus -> This is all of the disqus functionality that was in the main bcgov repo. With the disclaimer removed and that part of the template overriden in the main repo
2) ckanext-bcgov-cli -> This is the edc_commands like create vocab and create organizations. 
3) ckanext-bcgov -> The theme and the forms

The reason that 3 is still the theme and all the forms is that everything in there is very tied together and it would take a lot more work to seperate it out without getting that much more benefit.

After discussions yesterday I believe the plan is also to create ckanext-bcgov-common to include things like openshift templates.

The repos mentioned above are created, and the PR to update ckanext-bcgov has been submitted but not yet reviewed

**Comment by hleckenb** [comment]
@dkelsey review in your environment please.

**Comment by ll911** [comment]
one more undocumented extension
`edc_pow`

**Comment by SteveChapmanBCDX** [comment]
This issue has been sorted, with solution deployed.
