### ISSUE TITLE
Initiate BCDC User Group for Testing & Feedback

### ISSUE THREAD

**Issue by hleckenb** [bcgov/ckanext-bcgov#588]
As product owner I need to be aware of BCDC's user requirements through speaking directly with them and having them test the product so that work completed meets their needs and is appropriately prioritized.

DoD
Collect a list of potential participants through existing avenues (webinar attendees, BCDC Editor roles, BCDC Admin roles, product sponsors, data distribution users, external to government users)
Determine levels of users by Power User, data sharer, data user, workflow users or something like that.

**Comment by hleckenb** [comment]
Initial list collected with contributions from MDW and BD.

**Comment by hleckenb** [comment]
@dkelsey assigned to you as a reminder to pull the user list, Please ensure we can look at frequency of use logs.

**Comment by dkelsey** [comment]
I've sent a list out.

**Comment by hleckenb** [comment]
Draft testing plan sent out by Mike. User list created. Shared test scenarios out.
