### ISSUE TITLE
Review open tickets tagged as having a release number < 1.7.10

### ISSUE THREAD

**Issue by mdunhamwilkie** [bcgov/ckanext-bcgov#589]
As a product owner I need to know whether the tickets with release less than 1.7.10 that are in the needing QA or testing pipelines really belong there. or whether they should be moved back to the New Issues pipeline.

**Comment by hleckenb** [comment]
@mdunhamwilkie please ensure this ticket has been completed for our Sprint Review/Planning next Thursday so we can plan the 1.7.10 release. Note the release number must be associated with the Git repo in order for it to tie in correctly.

**Comment by mdunhamwilkie** [comment]
@dkelsey and @hleckenb.  Right now some tickets have "1.7.10" as the milestone and some have "sprint 0".  There is a "release" field but it's not being used.  How about if we use milestone for the sprint number and release for the release (e.g., 1.7.10).  @hleckenb, not sure what you mean by "Note the release number must be associated with the Git repo in order for it to tie in correctly."
