### ISSUE TITLE
BCeID users require the ability to download BCeID restricted and Named User restricted Data through the catalogue and POW

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#591]
**As a** user with a BCeID Business account,<br>
**I want** the ability to download restricted data, BCeID restricted and Named BCeID User restricted as I am able to do using the old distribution interface<br>
**so that** my ability to download and use BCeID restricted data continues.

**Comment by dkelsey** [comment]
PR's related to issue #539 have added starting point to fulfill this.
PR #541 
PR #543
PR #545

**Comment by hleckenb** [comment]
@mdunhamwilkie I'd suggest creating this as an epic and breaking down the tasks associated with completing the full action.

**Comment by hleckenb** [comment]
@mdunhamwilkie please take care of this as discussed.
