### ISSUE TITLE
Permalink Button Appears to do Nothing

### ISSUE THREAD

**Issue by hleckenb** [bcgov/ckanext-bcgov#595]
# ENV
`PROD`

# TESTCASE
* As a user of the catalogue I would like to grab the dataset permalink to share with another through a medium of my choosing. Evidence: Chrome & Firefox

# EXPECTED
*When button is selected a popup would appear displaying the permalink to be copied.

# ACTUAL
*When button is selected nothing seems to happen.

**Comment by mdunhamwilkie** [comment]
Sent a question out to DataBC users

Hi everyone, I’m looking for some advice on how you think the permalink button should behave:

 

Currently when this button is pressed nothing appears to happen (in the eyes of a novice user at least).  Actually, the URL on the address bar changes, but this is easy to miss if you aren’t expecting it.  What do you think should happen?

1.	I’d prefer to have a popup that displays the permalink, with a copy button? or
2.	Leave it the way it is – I know what to do; I don’t want to have to dismiss this window every time I want a permalink.
3.	Other options?

In option 1 the popup could include some text on why referring to a dataset using the permalink is important.

What do you think?

Thanks
Mike

**Comment by mdunhamwilkie** [comment]
Lots of feedback:

I had same first experience when I used the permalink button.  Now that I know what happens I’m fine with it the way it is now (option 2).  
But it would probably be easier for new users (and also to anyone training new users) to have something more obvious happen when you click the permalink button.

One thing I thought would maybe happen is that a copy of the permalink could get copied to the clipboard (saving the user having to make the copy themselves)? (so maybe a “copy permalink” button? …and continue to have the permalink change in the address bar).

----------------------------------

I’d suggest a mouse over that clarifies what clicking the “permalink” will do.
The ‘chain-link’ icon: wtf is that?  It should be a copy to clipboard icon—a familiar metaphor users have been conditioned to. 

What do all the other things on that bar do?  We should collect data on whether any of those links are ever used.  That is valuable realestate.  

I’ll limit my ideas to one more:  NO SCROLLING -  how much useless scrolling are we causing by having common information off the visible window?

----------------------------------------------------
Just to make sure I know what you mean by “A Copy Button and not the Link Button that actually copies the url”:

-	Button will be renamed from “Permalink” to “Copy Permalink”
-	Pressing button will do two things:
o	Change the URL displayed in the address line to the permalink URL 
o	Copy the URL into the clipboard
-	Add hover text “Copy permalink to the clipboard”

Am I understanding this right?
------------------------------------
Implement option one as it is a common user behaviour.
-------------------------------------------
I like the idea of having one URL to the metadata record page.
I’ve asked this before, but I want to confirm again…

Is it possible to have BOTH the name of the record and the permalink in one URL?

For example, both of these links refer to the same metadata record:
•	mnemonic version: https://catalogue.data.gov.bc.ca/dataset/university-of-victoria-aquifer-stress-evaluation
•	permalink version: https://catalogue.data.gov.bc.ca/dataset/17ffdf71-28f3-4a65-bba2-134622b50e8f

Instead, could there be just one URL that includes the mnemonic and the permalink?
•	https://catalogue.data.gov.bc.ca/dataset/17ffdf71-28f3-4a65-bba2-134622b50e8f/university-of-victoria-aquifer-stress-evaluation
•	Users could copy-paste the link directly from the browser address bar
•	And only the permalink GUID is used to locate the metadata record.
•	In fact, after the GUID the mnemonic text could be ignored completely, but it’s in the standard URL to every metadata record (visible to the user to make it obvious what the metadata record is for)
•	However, is the URL too long maybe?
------------------------------------------------------
Some people don’t know what “permalink” means or refers to… i.e. if they’re reading (or scanning) the “how to” documentation that refers to permalink then the documentation must clearly describe what the heck a permalink is and where to find it.
----------------------------------------------------
And here’s a link showing some alternatives:

http://library.sbcc.edu/wp-content/uploads/2011/10/CopyingArticlePermalinks.pdf

And go to this page https://discuss.newrelic.com/t/synthetics-for-siebel-open-ui/59566 and click on the chainlink

--------------------------------------
The problem for me with 

•	https://catalogue.data.gov.bc.ca/dataset/17ffdf71-28f3-4a65-bba2-134622b50e8f/university-of-victoria-aquifer-stress-evaluation

is that it might lead to confusion if we ever change the name of the dataset.  Say it was decided that “aquifer stress evaluation” no longer means what it used to and the custodian changes the name of the dataset to make it reflect current reality.  The link will still work, but the person reading it might get the wrong idea of what it points to. If we change the link to reflect the new name then it won’t be a permalink anymore. And if the permalink remains just the first part then the users will have to know that they have to just copy the first part – try to explain that one!

Greg just reminded me of why we don’t just use the permalink.  The mnemonic portion is called a “slug” and it’s very important for search engine optimization that we use it.  It’s why we get such good performance in google.

----------------------------------------------
Mike I understand what you mean by potential confusion when an old URL with text becomes different from an updated name (and URL) for a metadata record. But the other side of the argument is that an OLD non-permalink URL becomes a dead link if an editor ever changes a title to a record.  (I think Meg is right about users not understanding or using Permalink URLs, so most metadata records are shared as the text-only version.)

FYI:

I noticed that the link to the New Relic webpage has both a permalink number (59566) and a slug/mnemonic text “synthetics-for-siebel-open-ui”: https://discuss.newrelic.com/t/synthetics-for-siebel-open-ui/59566 
This URL works similar to what I was proposing: if you replace the “synthetics-for-siebel-open-ui” with any text, it will still locate the web page using the permalink number. Example: https://discuss.newrelic.com/t/ANY-TEXT-CAN-GO-HERE/59566

**Comment by hleckenb** [comment]
@mdunhamwilkie I would consider using dataset/record GUIDs only in permalink scenario. This way the user can change the name to their heart's content without breaking permalinks. This scenario should be the same for any "shares" (FB etc) for the dataset/record. 

Also, common user experience is the ability to have a pop-up display the link in a box with offer of button to copy.

**Comment by mdunhamwilkie** [comment]
@hleckenb I'm ok with what you are suggesting.  You've convinced me. Putting this back in the backlog for consideration for sprint 2.

**Comment by BrandonSharratt** [comment]
Created pull request #643 which adds the modal in the same style as the disqus modal (fades the background). 

Workflow is now:
Click Permalink Modal opens
Modal has a readonly input box with the permalink url in it, and a copy icon beside it.
Pressing the copy button puts the link onto the users clipboard
(The user can also manually select and copy the permalink)

An X or clicking out of the modal will close it.

**Comment by hleckenb** [comment]
Tested, performs as described.

**Comment by hleckenb** [comment]
Verified in PROD. Passed.

**Comment by mdunhamwilkie** [comment]
There are some changes I'd like
1) Add "https://" to start of permalink - e.g., https://catalogue.data.gov.bc.ca/dataset/4417e353-48a0-4576-903a-7ec342599b7a instead of catalogue.data.gov.bc.ca/dataset/4417e353-48a0-4576-903a-7ec342599b7a. See https://proj.data.gov.bc.ca/jira/browse/MDRPS-54
2) can you add a tooltip to the copy icon - "copy permalink"?
3) can the box containing the permalink be set up so that you can use the arrow keys, home, end, etc. to move within the text box.?

**Comment by jachurchill** [comment]
@mdunhamwilkie the first 2 were done, the 3rd item cannot be done if we leave the input as readonly

**Comment by mdunhamwilkie** [comment]
@jachurchill this change does not appear to be in delivery.  For the third item can you just ensure that the box shows the entire string? Note that the URL will be longer in PROD (cad -> catalogue)

**Comment by dkelsey** [comment]
@mdunhamwilkie [PR 714](https://github.com/bcgov/ckanext-bcgov/pull/714) has been merged and is in `CAD`

**Comment by mdunhamwilkie** [comment]
Thanks @jachurchill and @dkelsey ,.  A couple of things:
- looks like 'http://' is being prepended instead of 'https://' as requested
- the copy button adds a "#" to the end of the displayed (non-permalink, on the URL line) URL.
- make the box wide enough to display the complete URL (in Chrome the rightmost 8 or so characters are truncated

**Comment by mdunhamwilkie** [comment]
@jachurchill the permalink doesn't appear to work at all anymore in CAD or CAT.  Can you check this please?

**Comment by mdunhamwilkie** [comment]
@jachurchill  please migrate the fix to CADI as soon as possible so that I can test. Right now in CADI clicking the permalink button does nothing but put a # on the end of the URL. No popup. I'd like this in CATI and PROD as soon as possible,

**Comment by jachurchill** [comment]
@mdunhamwilkie I've fixed the issue and made a PR for a hotfix, the modal will once again appear, some javascript got deleted at some point so I just had to restore it. As for the other points you've made, the `#` is not avoidable, that is a side effect of opening the modal, the width of the modal is not set, we could make it arbitrarily larger but there is no consistent way to do this as link size and the size of the window are variable factors, I'll verify the `https` part when it gets to CAD or CAT as when I check in my local env it is running as `http` and will detect as such

**Comment by mdunhamwilkie** [comment]
@jachurchill , given what you've said above I'd like to revert to the original functionality, with one slight change - change the button label from "Permalink" to "Show the Permalink"

![image](https://user-images.githubusercontent.com/34721902/58108622-0710bf80-7ba1-11e9-8821-c01c83448820.png)

**Comment by SteveChapmanBCDX** [comment]
@jachurchill - I tested reverted code in Test.  It works properly.

The final step is here is to change the label from "Permalink" to "Show the Permalink" per @mdunhamwilkie's request.

**Comment by SteveChapmanBCDX** [comment]
Tested in cati.  The label has been changed to "Show Permalink".  The button works properly.

Closing issue.
