### ISSUE TITLE
Correct spelling of centroid in geographic dataset addition page

### ISSUE THREAD

**Issue by mdunhamwilkie** [bcgov/ckanext-bcgov#602]
# ENV
`PROD`, `CAT`, `CAD`

# TESTCASE
* Navigate to any geographic dataset that does not have a preview configured
* Review the **Preview Information** section when in edit mode.

# EXPECTED
centroid spelled correctly

# ACTUAL
![image.png](https://images.zenhubusercontent.com/5bd88f7331161867d1965f96/53655097-b73f-4c93-b65c-7218cde317e2)*

**Comment by dkelsey** [comment]
This passes in CAT

**Comment by dkelsey** [comment]
This passes in PROD
