### ISSUE TITLE
Authenticated IDIR users can download IDIR restricted data

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#607]
**As a** logged in IDIR user,<br>
**I want** the ability to submit orders for IDIR restricted data<br>
**so that** I can download data restricted to authenticated Government IDIR users..

**Comment by hleckenb** [comment]
CAD - working as it should.

**Comment by dkelsey** [comment]
did you test CAD or CAT?

**Comment by hleckenb** [comment]
CAT - working as it should.

**Comment by dkelsey** [comment]
Closing as this passes in PROD
