### ISSUE TITLE
Tab fails to go to the next field

### ISSUE THREAD

**Issue by BrandonSharratt** [bcgov/ckanext-bcgov#627]
---
## User Story
**As a** _user_,<br>
**I want** _use tab to go to the next field when creating a dataset_<br>
**so that** _I can easily enter data quickly_.

---
## Test Case

# ENV
`PROD`, `CAT`, `CAD`

# TESTCASE
Create a new dataset. Select any input field, and press Tab.

# EXPECTED
The next field of the form should be selected

# ACTUAL
Nothing happens.

# MORE INFORMATION
This appears to be due to the edc_gov.js file. It captures tab and arrow key presses, so that it can navigate the menu option bar instead. It does this regardless of whether or not that button menu is showing because its css selector is very vague.

**Comment by BrandonSharratt** [comment]
Created PR #628 

There was code implemented in edc_gov.js that specifically uses tab and the arrow keys to navigate around a menu that is only visible when it is in a very small window. While very small windows and burger menus like this are normally targeted towards mobile devices rather than remove the functionality entirely I made it properly check if the menu was visible and thus restored the normal tab functionality when being used in a PC sized window.

**Comment by dkelsey** [comment]
This passes in CAT TEST

**Comment by dkelsey** [comment]
This passes in PROD
