### ISSUE TITLE
Prod Openshift

### ISSUE THREAD

**Issue by BrandonSharratt** [bcgov/ckanext-bcgov#630]
## User Story
**As a** _Developer_,<br>
**I want** _production to be in openshift_<br>
**so that** _all environments are in the same environment and deployments are predictable_.

---

This has a few dependencies before we can move prod to openshift. Specifically database migration via api scripts are required so that we can move the data to the new prod environment, and so that we can duplicate data between environments without copying over sensitive information like users as we would get from a pg_dump.

Currently OpenShift is set up to track 3 environments
Dev, Delivery, and Test

Dev is the current dev, but will be more free form and updated more freely by devs. 
Delivery is the new dev environment and will track the master branch of the repo and thus be updated less often.
Test is new and will tag the current version of delivery with latest when the update is approved.

Master will be based off of that and will use the specific hash of latest when that update is approved.

**Comment by ll911** [comment]
also needs data etl ready for 
filestore
datastore
ckan db w/o users

**Comment by hleckenb** [comment]
@ll911 I assume the filestore and datastore deal with the backup aspect you were speaking to yesterday?

**Comment by ll911** [comment]
@hleckenb it's more than just backup.

**Comment by ll911** [comment]
@SteveChapmanBCDX as discussed previously, UI will be remaining in OKD, and prod like env will be in OKD, actual prod will be remain on existing server as storage & performance concern.
