### ISSUE TITLE
Ensure all components of the catalogue work in latest versions of browsers

### ISSUE THREAD

**Issue by hleckenb** [bcgov/ckanext-bcgov#653]
## User Story
**As a BC Data Catalogue editor, administrator and data downloader,<br>
**I want to be able to access and carry out all applicable tasks to my role when using the browser and version of the broswer of my choice, <br>
**so that I do not receive a browser version error message and can successfully complete my tasks.

---
## Test Case

# ENV
`PROD`

# TESTCASE
*DA needed to amend an organization's members list in the catalogue, this is an administrator role. when the task was attempted the DA was blocked with an error message stating the browser being used was not supported. This browser was Chrome 71.0.3578.80

# EXPECTED
*Any interaction with the catalogue should be backward or forward compatible with any browser. Focus should be browsing through Chrome, IE, FireFox, Apple Safari, Opera, Edge for at least the last 3 versions. 

# ACTUAL
*As above![bcdc browser error.jpg](https://images.zenhubusercontent.com/5aea2fe44b5806bc2bd18ba5/98250766-80db-444a-8a8c-a6d31deb7619)

DoD:
Option (a) making the catalogue more robust to be cross compatible with different browsers and versions.
Option (b) creating an interim fix which enables compatibility with Chrome 71.0.3578.80.

**Comment by mdunhamwilkie** [comment]
Let's do option b for now.  Just fix the logic for figuring out whether you are using Chrome or Firefox or neither. Try to make the test as resilient as possible to prevent upgrades to browsers breaking it in the future.

**Comment by hleckenb** [comment]
@BrandonSharratt create new ticket to carry out auto test/check against different browsers and versions to determine catalogue compatibility/reliance on browser versions. Goal is to validate if a browser check is truly required.
