### ISSUE TITLE
Amend incompatible browser error message

### ISSUE THREAD

**Issue by hleckenb** [bcgov/ckanext-bcgov#654]
As a user of the Catalogue I want to ensure that the message I received when using an incompatible browser version is easy to understand and delivers a clear message so that I can complete my task without blockage.
---
---
## Test Case

# ENV
`PROD`

# TESTCASE
*DA needed to amend an organization's members list in the catalogue, this is an administrator role. when the task was attempted the DA was blocked with an error message stating the browser being used was not supported. This browser was Chrome 71.0.3578.80

![bcdc browser error](https://user-images.githubusercontent.com/24461217/49551113-cd722380-f8a2-11e8-98e8-9157bf338f74.jpg)

# EXPECTED
When the error message displayed it should indicate which browsers and versions are compatible (at the very least) or ensure the Catalogue is compatible with several browsers and versions.

I would suggest this wording

> You are attempting to update or edit BC Data Catalogue content using a non-supported web browser or version.  Supported browsers are Google Chrome (downloadable from https://www.google.com/chrome/) and Firefox (downloadable from https://www.mozilla.org/en_US/firefox/new/). Not all version of these browsers are supported.  If you are seeing this message and you are using Google or Chrome, then please report this problem to DataBC Catalogue Services.

Eventually as part of the UX work we will look at how to best report a problem (rather than telling people to email someone). 

# ACTUAL
Current message tells user to use Google or Chrome (presumably the latest version, which for Chrome is not compatible). It suggests going to an OCIO site that has been deprecated.

**Comment by BrandonSharratt** [comment]
I saw that the message said "Google or Chrome" which I assume is supposed to mean Google or Firefox, so I've added the message as such

You are attempting to update or edit BC Data Catalogue content using a non-supported web browser or version. Supported browsers are Google Chrome (downloadable from https://www.google.com/chrome/) and Firefox (downloadable from https://www.mozilla.org/en_US/firefox/new/). Not all version of these browsers are supported. If you are seeing this message and you are using Firefox or Chrome, then please report this problem to DataBC Catalogue Services.
