### ISSUE TITLE
Onboard UX resource

### ISSUE THREAD

**Issue by hleckenb** [bcgov/ckanext-bcgov#660]
As a new ux resource to the team I need to understand the product, project and workings of the team to be in a position to establish ux work requirements and planning so that I can ensure the team can make informed decisions about work and priorities going forward.

DoD:
Understand product meaning and mechanics in PROD
Understand the team dynamics
Understand the current state of users and stakeholders involved in the project

**Comment by hleckenb** [comment]
@mdunhamwilkie a prompt for work once contract is in place.

**Comment by mdunhamwilkie** [comment]
I still need to review the responses.

**Comment by hleckenb** [comment]
Completed.
