### ISSUE TITLE
Users with EDC_ADMIN privs cannot add user to suborg

### ISSUE THREAD

**Issue by mdunhamwilkie** [bcgov/ckanext-bcgov#663]
---
## User Story
**As a** _user with the EDC_ADMIN role, but not the sysadmin _,<br>
**I want** _to be able to add a user who has never logged in before as an EDC_EDITOR_<br>
**so that** _I don't have to bug someone with the sysadmin priv_.

---
## Test Case

# ENV
`PROD`, `CAT`, `CAD`
P1: v1.7.X ef8c3f6 
Using Firefox 63.0.3 (64-bit) (not sure if that is relevant)

# TESTCASE

Find a user who is not already recorded in the Catalogue
`
import json
import requests
api_key = '******************************************'
headers = {'X-CKAN-API-KEY': api_key, 'content-type': 'application/json;charset=utf-8'}`
ckan_base = 'https://catalogue.data.gov.bc.ca/api/3/action'
base_url = ckan_base + '/user_list?q='\<idir\>' '
collect = list()
for r in range(1):
    resp = requests.get(url=base_url, headers=headers)
    resp = resp.json()['result']
    collect.extend(resp)
resp
<nothing displayed>
`
Give them the EDC_EDITOR priv in Adam
Log in as DBCUSER3 (edc_admin but not sysadmin)
Try to add them as an editor in the DataBC suborg
#
# EXPECTED

user should be added successfully.

# ACTUAL
*
![image](https://user-images.githubusercontent.com/34721902/49949197-e9308780-fea9-11e8-8130-41494db6f011.png)

**Comment by mdunhamwilkie** [comment]
Need to determine if this is a Firefox bug or if it happens with other browsers (i.e., chrome) as well

**Comment by SteveChapmanBCDX** [comment]
Closing this - under new UI, all admins will be sysadmins.
