### ISSUE TITLE
Document procedures for setting up a BCDC development environment

### ISSUE THREAD

**Issue by mdunhamwilkie** [bcgov/ckanext-bcgov#664]
---
## User Story
**As a** _Developer working on the BC Data Catalogue_,<br>
**I want** _clear instructions on how to set up a development environment on my Windows 7/Windows 10 laptop_<br>
**so that** _I can be as productive as possible as quickly as possible_.

DefinitionOfDone

@mdunhamwilkie  is able to follow the instructions to set up a development environment on his Windows 7 laptop.

**Comment by BrandonSharratt** [comment]
Got a version of this working on my computer. There is definitely some cleanup to do but I think the next step would be to get someone else to test it to make sure it works on another machine.

**Comment by BrandonSharratt** [comment]
The code is now complete, and it has been installed once successfully, after some troubleshooting machine discrepancies and adding those to the README. I have now handed this off for one more review on another machine. If that one goes smoothly a repo will be created for this code, the code will be pushed and this will be considered Code Complete

**Comment by hleckenb** [comment]
@mdunhamwilkie to give a trial run

**Comment by BrandonSharratt** [comment]
https://github.com/bcgov/ckan-bcgov-terraform

**Comment by SteveChapmanBCDX** [comment]
Reviewed with the team.  Instructions for Mac and Linux have been tested and work.  

Testers were unable to create working local environment for Windows.

Closing as "Won't do".  Can reopen issue in future if required.
