### ISSUE TITLE
Openshift pipeline to support delivery of multiple extensions

### ISSUE THREAD

**Issue by hleckenb** [bcgov/ckanext-bcgov#666]
As a developer I want Openshift pipeline to support delivery of multiple extensions so that as we divide BC Gov ext into multiple extensions they get automatically deployed to create efficiencies for the team.
---
## User Story in a table
| **As A** | **I Want** | **So that** |
|--------|---------|---------|
| _< persona >_ | _< feature >_ | _< reason >_ |

---
## Test Case

# ENV
`PROD`, `CAT`, `CAD`

# TESTCASE
*

# EXPECTED
*

# ACTUAL
*

**Comment by BrandonSharratt** [comment]
This is already supported by the pipeline. The pipeline sets a dockerfile and a docker deployment strategy.

The deployment strategy sets environment variables: BCDC_PUB_EXT, and BCDC_INT_EXT

each of them iterate over either public or internal extensions and get them so if we were to add ckanext-bcgov-disqus for instance to the deployment environment variable it will deploy that extension as well

 for pp in ${BCDC_PUB_EXT}; do pip install --no-cache-dir -e git+https://github.com/bcgov/${pp}@master#egg=${pp}; done
