### ISSUE TITLE
Organize workflow for next release

### ISSUE THREAD

**Issue by hleckenb** [bcgov/ckanext-bcgov#669]
---
## User Story
**As a user of the data catalogue,<br>
**I want to be able to use the latest improvements ready for release< feature >_<br>
**so that I can have an improved user experience and get my work done more easily.

---
Once all current pull requests have been completed.
UAT
Schedule release to TST for 3rd Jan, 2019
Test
Schedule release to PROD for 8th Jan, 2019

---
## Test Case

# ENV
`PROD`, `CAT`, `CAD`

# TESTCASE
*

# EXPECTED
*

# ACTUAL
*

**Comment by SteveChapmanBCDX** [comment]
Release 1.7.17 issued January 15, 2019.  Closing ticket.
