### ISSUE TITLE
BCDC - manage BCGW resources button doesn't do anything

### ISSUE THREAD

**Issue by mhoole** [bcgov/ckanext-bcgov#680]
# ENV
`PROD`, `CAT`, `CAD`

# TESTCASE
* using Firefox (Quantum 64.0)
* step 1... create geographic dataset...
* step 2... fill out all required details
* step 3... click "next add data", and land on the "resources" page
* step 4... click "manage BCGW resources"

# EXPECTED
* the first dialogue box that confirms the object was found should appear.

# ACTUAL
* nothing happens when "manage BCGW resources" is clicked.  F12 shows "Empty string passed to getElementbyID()"
* workaround:  Save dataset first.  Hit wrench to edit, click the resources tab, and click the "manage BCGW resources" button.

**Comment by mhoole** [comment]
20190107 - this issue appears to be fixed in test https://cat.data.gov.bc.ca/

**Comment by hleckenb** [comment]
CAD Chrome & FireFox - Not able to access adding dataset nor resources. 
PROD - Seems Chrome causes browser error and FireFox issue remains.

**Comment by hleckenb** [comment]
Verified in PROD. Passed
