### ISSUE TITLE
Formatting of data elements: Data Quality is empty and should not be presented.

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#683]
# ENV
`CAT`, `CAD`

# TESTCASE
* navigate to CBM Integrated Cadastral Fabric (in TEST)
* scroll down to the additional information section.

# EXPECTED
* Field elements that contain information are displayed with proper formatting

![screen shot 2019-01-08 at 5 05 20 pm](https://user-images.githubusercontent.com/3906047/50869392-9f33a800-1368-11e9-9cfe-5ccce973846b.png)

# ACTUAL
* Formatting of metadata elements is correct yet **Data Quality**, which contains no information, is displayed.  It should not be displayed.

![screen shot 2019-01-08 at 4 57 50 pm](https://user-images.githubusercontent.com/3906047/50869080-6fd06b80-1367-11e9-9369-fd61a8534103.png)

**Comment by SteveChapmanBCDX** [comment]
I tested this in TEST/PROD against the "Fibre Recovery Zones" database.  This database contains neither "Data Quality" nor "Lineage Statement" information.
Testing complete.  Issue fixed.  Closing the issue.
