### ISSUE TITLE
Remove browser checking when adding or editing datasets

### ISSUE THREAD

**Issue by mdunhamwilkie** [bcgov/ckanext-bcgov#685]
---
## User Story
**As an** _editor of BC Data Catalogue records_,<br>
**I want** _to be able to use any modern browser (even IE) and take my chances_<br>
**so that** _I don't have to use a browser I don't feel comfortable using or which has other bugs_.

Remove the test that produces this screen:

![image.png](https://images.zenhubusercontent.com/5bd88f7331161867d1965f96/0a931056-6972-4dc9-a650-6c42dac50b86)

**Comment by BrandonSharratt** [comment]
I have tested in Opera and Safari after having removed the check and successfully created a dataset in both browsers, didn't seem like an issue. Could not test IE or Edge

**Comment by hleckenb** [comment]
@BrandonSharratt this would be in which environment?

**Comment by hleckenb** [comment]
@BrandonSharratt CAT IE11 still produces error page. Relates to #698

**Comment by SteveChapmanBCDX** [comment]
Tested in TEST.  Reviewed behaviour with @mdunhamwilkie.  Closing issue.
