### ISSUE TITLE
Markdown modal help popover does not close

### ISSUE THREAD

**Issue by hleckenb** [bcgov/ckanext-bcgov#687]
## User Story
**As a dataset editor of the bc data catalogue,<br>
**I want to be able to close the markdown formatting popover<br>
**so that I can see the rest of my screen.

---
## Test Case

# ENV
`PROD`, `CATI`, `CADI (unverified)`

# TESTCASE
PROD - https://catalogue.data.gov.bc.ca/dataset/environmental-emergency-response-eer-district-boundaries
CATI - https://cati.data.gov.bc.ca/dataset/environmental-emergency-response-eer-district-boundaries
1. log in
2. navigate to above dataset
3. Select "edit" for "BC Geographic Warehouse Custom Download"
4. Select "markdown formatting" in "resource Description" or "supplemental information"

# EXPECTED
* Popover appears and user can close the popover either by focusing away from the popover or by clicking on an "x".

# ACTUAL
* Popover remains open, note accumulates popovers each time "markdown formatting" is selected. Only removed once user moves to new page. Note: happens for any instance where the popover is offered for markdown formatting.

![image.png](https://images.zenhubusercontent.com/5aea2fe44b5806bc2bd18ba5/b0d13d63-8a73-4917-b704-284921a8c71d)

**Comment by mdunhamwilkie** [comment]
@jachurchill, this was not implemented as specified.  The popup should be dismissed by pressing on an x in the top right corner or by changing the focus by clicking somewhere else. This needs to be fixed.
