### ISSUE TITLE
Custom Download (POW) does not launch in IE 11.

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#698]
# ENV
`PROD`, 
`CAT`, `CAD` - have not tested these environments

# TESTCASE
* Using IE 11
* Navigate to any geographic record which has the "BC Geographic Warehouse Custom Download" resource; the POW resource.
* Navigate to the resource page
* click the **Access / Download** button
![screen shot 2019-01-17 at 4 01 09 pm](https://user-images.githubusercontent.com/3906047/51356909-3edfed00-1a71-11e9-961c-2ae493da3695.png)

# EXPECTED
* The Persistent Order Widget opens with the order included.
![screen shot 2019-01-17 at 4 01 33 pm](https://user-images.githubusercontent.com/3906047/51356919-4b644580-1a71-11e9-9aae-6d381598bd83.png)

# ACTUAL
* The button does nothing.

# NOTE
* In our last release we modified a "browser check" such that all modern browsers are supported.  Previously IE was not supported.

**Comment by hleckenb** [comment]
PROD: testcase is true. POW or any download resource does not launch upon selecting Access/Download. Tried right click to open download ... opened in new tab - the dataset page, not the download.
IE11 - https://catalogue.data.gov.bc.ca/dataset/bc-wild-mountain-sheep-registry-distribution/resource/c5bc7317-99ab-484f-911d-16522f646688#edc-pow

**Comment by hleckenb** [comment]
Test case true in TEST too.

**Comment by hleckenb** [comment]
Note: check "browser check" code as when I tried to add a dataset in IE11 CAT I was provided with the non-supported browser error window. Popups seems to not work, Permalink pop up does not fire.

**Comment by hleckenb** [comment]
@BrandonSharratt could do a check on the browsers supported to determine if IE11 was missed or somesuch?

**Comment by cbexson** [comment]
Finding this issue using the new POW as well as the 'old' data distribution service.

**Comment by dkelsey** [comment]
I removed **Check other editing functionality in IE as well.** from the title as I didn't add it.
This is a test case that clearly demonstrates that IE can't launch the POW.

Mike, you can create another ticket to  "Check other editing functionality in IE as well."
Though that statement is ... very open.  There are documented test cases that can be followed which will achieve what you are requesting.

**Comment by SteveChapmanBCDX** [comment]
Reviewed and tested with @mdunhamwilkie.  Closing issues as "completed".
