### ISSUE TITLE
Cannot edit the metadata Object Name or BCGW resource - the object name is incorrect

### ISSUE THREAD

**Issue by cbexson** [bcgov/ckanext-bcgov#709]
**RE dataset: https://catalogue.data.gov.bc.ca/dataset/baba3bbe-363a-4d0a-b030-c1e356226b75**

# ENV
`PROD`

# TESTCASE
* Tested on 2019-01-25 and 2019-01-28 - same action, same result.
* The object name for the above dataset is incorrectly set in the metadata record.  Somehow, the BCGW resource was successfully added in at some point. To fix this, I tried to:
1. enter edit mode, then edit the object name in the metadata record to the correct object name and
2. remove the BCGW resource

# EXPECTED
* I am able to edit the object name, then click Save Dataset and the object name is successfully updated.
* I am able to edit the resource and click Delete to remove the BCGW resource.

# ACTUAL
* When trying to edit the object name, I can make the change to the name, but get the following error after clicking Save Dataset:
![image](https://user-images.githubusercontent.com/44584495/51856418-8291ec80-22e4-11e9-9621-65fca467ddf5.png)

* When trying to remove the BCGW resource:
_Workflow #1:_
> Click the wrench to start editing the record > Click the Resources tab > Click Manage for the BCGW resource, get this window:
![image](https://user-images.githubusercontent.com/44584495/51856528-cdabff80-22e4-11e9-8114-6f3152ae9cc6.png)
> Click Delete, get this window:
![image](https://user-images.githubusercontent.com/44584495/51856555-e1576600-22e4-11e9-8eb9-f2ba7bc231df.png)
> Click Yes, get this window:
![image](https://user-images.githubusercontent.com/44584495/51856605-f7fdbd00-22e4-11e9-9a5b-df1e1782a576.png)

_Workflow #2:_
* On the main metadata page (not in edit mode), under Data and Resources, Click Explore > Edit, get this window:
![image](https://user-images.githubusercontent.com/44584495/51856824-85d9a800-22e5-11e9-97fd-265820ee50e2.png)
> Click Delete, get this window:
![image](https://user-images.githubusercontent.com/44584495/51856555-e1576600-22e4-11e9-8eb9-f2ba7bc231df.png)
> Click Yes, get this window:
![image](https://user-images.githubusercontent.com/44584495/51856605-f7fdbd00-22e4-11e9-9a5b-df1e1782a576.png)

**Comment by cbexson** [comment]
I cannot create any new records in the Catalogue. - Getting the same 500 Internal Server Error as above, whether I do a 'Save Dataset' or Next: Add Data.  I've tried some different Orgs/Sub-Orgs, same thing.

**Comment by dkelsey** [comment]
We restarted the index, re-indexed all the data.
I was able to change the object name, removing the 'S' after TRAIL.

This now passes.
