### ISSUE TITLE
VueJS UI

### ISSUE THREAD

**Issue by jachurchill** [bcgov/ckanext-bcgov#716]
Epic for new UI 

---
## User Story
**As a** _user_,<br>
**I want** _a new ui_<br>
**so that** _shiny_.

**As a** _developer_,<br>
**I want** _a new ui_<br>
**so that** _concerns are separated thus making maintenance is easier_.

**Comment by SteveChapmanBCDX** [comment]
Migrated epic and its issues to => https://github.com/bcgov/ckan-ui/issues/19
