### ISSUE TITLE
VueJS UI - Login

### ISSUE THREAD

**Issue by BrandonSharratt** [bcgov/ckanext-bcgov#720]
See epic but add the ability to login, probably keycloak related. Depends on Mikes user stories that come of this, but investigate for now

**Comment by BrandonSharratt** [comment]
ckanext-keycloak exists and although buggy does work with minor changes for us. It will even tie into existing users.

The ui uses keycloak authentication and then uses the jwt to authorize with ckan.

Keycloaks default timeout is 5 minutes on the token so we'll need to build renewal into the token

**Comment by BrandonSharratt** [comment]
I've made it refresh tokens in the window between expired and refresh tokens being valid (keycloak default is access expires in 5, refresh expires in 10, so therefore it would refresh the token on a call made between 5 and 10).

**Comment by SteveChapmanBCDX** [comment]
Issue moved to [bcgov/ckan-ui #12](https://github.com/bcgov/ckan-ui/issues/12) via [**ZenHub**](https://www.zenhub.com/)
