### ISSUE TITLE
VueJS UI - Add/Edit Resources on a dataset

### ISSUE THREAD

**Issue by BrandonSharratt** [bcgov/ckanext-bcgov#721]
See epic but allow the adding and editing of resources on the standard dataset type. Only need to make sure that csv and xlsx work by default but if 'trivial' to support add more types. Support preview of csv/xslx

**Comment by SteveChapmanBCDX** [comment]
Issue moved to [bcgov/ckan-ui #18](https://github.com/bcgov/ckan-ui/issues/18) via [**ZenHub**](https://www.zenhub.com/)
