### ISSUE TITLE
Data Viz on databc homepage carousel is broken.

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#723]
# ENV
`PROD`, `CAT`, 
Not: `CAD`

# TESTCASE
* navigate to https://data.gov.bc.ca
* open the developer console to the console tab
* Navigate to the BC Seafood Harvest and Wholesale Value visualization (the 4th on in PROD 1st one in TEST)

# EXPECTED
* the viz renders correctly
* no errors reported in the console.

# ACTUAL
<img width="1191" alt="screen shot 2019-03-07 at 10 44 44 am" src="https://user-images.githubusercontent.com/3906047/53980823-25990b80-40c6-11e9-80a9-00e3622a3ce9.png">

![screen shot 2019-03-07 at 10 45 11 am](https://user-images.githubusercontent.com/3906047/53980838-2e89dd00-40c6-11e9-990f-a617a4b64bc9.png)

**Comment by ll911** [comment]
iss related to data change.
