### ISSUE TITLE
Improve email notification regarding record state changes

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#75]
Sometimes users added to an organization with an editor role are confused when  they receive email notification messages from the application on record state changes. It would help editors and system administrators if the messages were more explicit.

Existing message Sample:

> The following record is "Pending Publication" for Ministry of Advanced Education - Enterprise Data Services

> Record https://<domain>.data.gov.bc.ca/dataset/record-title-goes-here, Record Title Goes Here

> Please review and act as required.

A new message with the following form should be prepared:

> As a [BC Data Catalogue](<domain>.data.gov.bc.ca) editor  for  the Ministry of Advanced Education - Enterprise Data Services, please be advised that the publication state of this record:  https://<domain>.data.gov.bc.ca/dataset/record-title-goes-here is now "Pending Publication" .

> If you are no longer an editor for Ministry of Advanced Education - Enterprise Data Services or if you have a question or concern regarding this message  please contact DataBC Catalogue Services datacat@gov.bc.ca .

> Thanks.
.........................................................................................................

This is the code that generates the message.
https://github.com/bcgov/ckanext-bcgov/blob/b8a9ba0492697622199604bbf9824e783c6ab1b6/ckanext/bcgov/logic/action.py

**Comment by Mbrownshoes** [comment]
Can we also have it so that when an editor is removed from an organization using the organization manage feature (member_remove) that the individual no longer receives these messages.
<img width="343" alt="screen shot 2016-05-09 at 1 57 01 pm" src="https://cloud.githubusercontent.com/assets/3362533/15127956/fbfa0d66-15ed-11e6-9501-0acf7265565f.png">

Currently, the individual also needs to be deleted, but in some cases we have people who are editors in multiple organizations and we may want to remove them from one org but not delete them.

**Comment by jrods** [comment]
@Mbrownshoes Is that a different issue to CITZEDC-843?

**Comment by Mbrownshoes** [comment]
@jrods yes it is. Right now a user needs to be 'non-active' before they stop receiving a notification, but ideally notifications would stop once they are removed as an editor for that org. We might still want them to be 'active', perhaps as an editor for another organization, but the notifications should stop for the org they have been removed from.

**Comment by jrods** [comment]
@Mbrownshoes Alright, I see. Also may i suggest making it a new issue so it can be tracked separately from this issue and have the new issue just reference this one?

**Comment by Mbrownshoes** [comment]
will do.
