### ISSUE TITLE
Stop email notifications when an editor has been removed from an organization

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#76]
When an editor is removed from an organization using the organization manage feature (member_remove) that the individual should no longer receive notifications. Currently, the individual also needs to be deleted, but in some cases we have people who are editors in multiple organizations and we may want to remove them from one org but not delete them.

Right now a user needs to be 'non-active' before they stop receiving a notification, but ideally notifications would stop once they are removed as an editor for that org. We might still want them to be 'active', perhaps as an editor for another organization, but the notifications should stop for the org they have been removed from.

**Comment by gjlawran** [comment]
This ticket should also consider changes that were committed under https://github.com/bcgov/ckanext-bcgov/pull/71

**Comment by gjlawran** [comment]
Confirmed deleted  user no longer receiving email notifications.

**Comment by Mbrownshoes** [comment]
We have a situation as described above -- an existing user has been removed as an editor from organization A but remains an editor for organization B. The user is still receiving notifications from org A. I haven't been able to find a reference to how this was supposedly fixed.

**Comment by jrods** [comment]
@Mbrownshoes what environment was this in? Are these orgs unrelated, as in one or the other isn't a sub org of the other org?

**Comment by Mbrownshoes** [comment]
This is production, these sub orgs are unrelated and are in different Orgs. However, there are records in org B that used to be in org A - but transferred  over about a year ago.  I'm testing this out in cat and it looks like only admin's are receiving notifications, but editor's aren't. 
@jrods, I'll test in CAD.

**Comment by jrods** [comment]
@Mbrownshoes it seems i have made the ~~wrong~~  fix the first time around.
The query that got the user list for the org to send emails to, ~~was using the user state rather then the state in members, the members table is the one that keeps track of users within the org.~~ needs to check user state to see if the user is active or not **and** needs to check if the user is active in the org (member state)

**Comment by kfishwick** [comment]
This is fixed, can we put it in 1.5.2?

**Comment by Mbrownshoes** [comment]
verified in CAD
