### ISSUE TITLE
Fix Bugs (from Dev testing)

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckanext-bcgov#770]

**Comment by jachurchill** [comment]
Found Issues in testing on CATI (add below):

-

**Comment by BrandonSharratt** [comment]
New round of issues found in CATI (add below)

-  All Dataset list pages (dataset/group/org) - Record Published / Modified not displayed, sector not displayed, dataset type no longer exists

- Dataset Type is not filterable because it doesn't exist. Resource Type is not filterable as a replacement.
