### ISSUE TITLE
Underscores in resource filenames should be maintained when uploaded.

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#78]
As a user, when I upload a file with underscores in the filename I would like them to be maintained.

An issue has been identified on core https://github.com/ckan/ckan/issues/2597  however it appears to be dormant. Consider offering to address if original poster has not provided PR.

**Comment by jeff-at-h3** [comment]
reassess to validate if still a bug - retest
Can be fixed when UI/UX plan in place

**Comment by mdunhamwilkie** [comment]
It appears that this is fixed.  Verified using https://cat.data.gov.bc.ca/dataset/test-of-underscores-in-resource-file-names.
