### ISSUE TITLE
Each group's "about" page is broken

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckanext-bcgov#808]
For each of the application's groups, the "about" endpoint is broken.  Example => https://catalogue.data.gov.bc.ca/group/about/data-innovation-program

Reproduction steps:
* Navigate to a group's detailed view;
* Click on the "read more" button at the bottom of the group's description (upper left side of page)

**Comment by jachurchill** [comment]
@SteveChapmanBCDX This fix was merged to master but it has not been deployed

**Comment by SteveChapmanBCDX** [comment]
Deployed to Prod (release 1.7.25).
