### ISSUE TITLE
Investigate timing for editors browsing organization view

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#81]
Navigation by editors of the organization view (https://catalogue.data.gov.bc.ca/organization ) is slow. 
Identify options for improving the timing to be closer to that provided to public/admin (<2 secs).

This is linked to CIZTEDC-874.

@Mbrownshoes will provide time statistics for various roles as a baseline.

**Comment by Mbrownshoes** [comment]
| CAT                             |                         |                      |                                         |                      |                      |                      |                                          |
|---------------------------------|-------------------------|----------------------|-----------------------------------------|----------------------|----------------------|----------------------|------------------------------------------|
| Editor                          |                         |                      |                                         |                      |                      |                      |                                          |
| Run                             | Data Tab Submit Invalid | Add Data Invalid     | Add Data Valid                          | Add Data Empty       | Select Datatype      | Add Resource Empty   | Data Tab Submit Valid                    |
| 2016-06-20~11_25_09             | [0.6081039905548096]    | [5.860871076583862]  | [7.7078869342803955, 7.63922905921936]  | [2.9525389671325684] | [3.0452849864959717] | [0.7622361183166504] | [24.459079027175903, 24.338877201080322] |
| 2016-06-20~15_56_57             | [0.9179840087890625]    | [6.685149908065796]  | [7.786017894744873, 7.470398902893066]  | [2.943892002105713]  | [2.9198601245880127] | [0.9145998954772949] | [24.284399032592773, 24.163266897201538] |
|                                 |                         |                      |                                         |                      |                      |                      |                                          |
|                                 |                         |                      |                                         |                      |                      |                      |                                          |
| Admin                           |                         |                      |                                         |                      |                      |                      |                                          |
| 2016-06-20~11_07_33             | [0.5330009460449219]    | [1.482978105545044]  | [1.390733003616333, 1.2245800495147705] | [1.1783568859100342] | [1.2296321392059326] | [0.7114510536193848] | [2.340728998184204, 2.3506269454956055]  |
| 2016-06-20~16_42_11             | [0.591339111328125]     | [1.4775471687316895] | [2.827404022216797, 1.236678123474121]  | [1.1683800220489502] | [1.2350220680236816] | [0.6069910526275635] | [2.5192689895629883, 2.3680789470672607] |
|                                 |                         |                      |                                         |                      |                      |                      |                                          |
|                                 |                         |                      |                                         |                      |                      |                      |                                          |
| Time to reach organization view | admin                   | editor               |                                         |                      |                      |                      |                                          |
| Geobc (cat and prod)            | < 2 s                   | ~6.5 s               |                                         |                      |                      |                      |                                          |

**Comment by kfishwick** [comment]
Khalegh has identified the major culprit for slowness in editor create/browse datasets.  It is indeed related to the orb/suborg queries to return user membership.  He has a proposed solution and is testing it.  Should we use this ticket for release 1.4 delivery or make a new one?

**Comment by ll911** [comment]
@gjlawran @kfishwick I suggest close this one and create new one attached to 1.4.0

**Comment by gjlawran** [comment]
@kfishwick  @ll911  lets follow SDLC - close it once we here about the proposed solution and confirm its assignment to a release - this ticket can be moved to the next step though for our review/verification - also if we are doing 2.4/2.5 update in release 1.4 - it may have implications for this issue

**Comment by kfishwick** [comment]
Preliminary analysis of new timing is sub - second dataset creation for editors.  Needs quite a lot of testing to ensure security rules are followed.
