### ISSUE TITLE
Be able to define a resource without specifying a file or URL

### ISSUE THREAD

**Issue by mdunhamwilkie** [bcgov/ckanext-bcgov#840]
---
## User Story
**As a** _Data Administrator_,<br>
**I want** _to be able to define a resource that isn't a file or URL_<br>
**so that** _I don't have to a specify dummy link (e.g., the "faq" resource) when defining, for example, a not downloadable BCGW table/view_.

In the current BC Data Catalogue, resources cannot be added unless you upload a file or specify a URL.  This means that in order to add a BCGW table or view as a resource it either has to be downloadable (it has an OFI link) or we have to associate it with the dummy "FAQ" URL (http://apps.gov.bc.ca/notice/edc/faq/). (See for example [this record](https://catalogue.data.gov.bc.ca/dataset/f430f054-8ea8-495f-bceb-8b0e5fb12225)).  This is bad UX - the user navigates to a resource in order to access it and is then told they can't.  Some non-downloadable tables/views have Catalogue records that have no resources defined. This isn't good either, as we should define a resource where we can describe the table or view, even if it is not downloadable (such as supplying the last refresh date value).

This issue could easily be fixed by removing the restriction that a resource has to be either an uploaded file or a URL.

**Comment by SteveChapmanBCDX** [comment]
Issue moved to [bcgov/ckan-ui #179](https://github.com/bcgov/ckan-ui/issues/179) via [**ZenHub**](https://www.zenhub.com/)
