### ISSUE TITLE
Singular (non-plural) word stems are not returned by search

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#85]
When users search for a singular version of a word - e.g. home - the search does not return any records that include the stem of the word  - e.g. homes. 

 demo.ckan.org  (currently CKAN 2.5.2)   does return records that include word stems .

Is this a SOLR version or configuration issue?

**Comment by ll911** [comment]
@gjlawran demo.ckan.org use solr 6.0 
https://github.com/ckan/ckan/blob/master/contrib/docker/solr/Dockerfile

**Comment by gjlawran** [comment]
@kfishwick please compare SOLR config for CKAN 2.3.4 (https://github.com/ckan/ckan/blob/ckan-2.3.4/ckan/config/solr/schema.xml ) with ours

**Comment by kfishwick** [comment]
We will double check this once the SOLR & CKAN versions have been updated.

**Comment by jrods** [comment]
@gjlawran I did a search in cad for 'test' 'tests' and 'testing', all results return 151 datasets. So I believe plurals in search are working.

**Comment by Mbrownshoes** [comment]
A search for 'building' did not return this record, which has the word 'buildings' in the description
https://cat.data.gov.bc.ca/dataset/consolidated-community-energy-and-emissions-inventory-reports

**Comment by jrods** [comment]
I did a search on 'building' and found that dataset in cat. 

<img width="749" alt="screen shot 2016-07-29 at 4 01 24 pm" src="https://cloud.githubusercontent.com/assets/5874122/17265756/90b3cf30-55a6-11e6-87b2-c623c0a160ac.png">

**Comment by Mbrownshoes** [comment]
Ah sorry, Leo re-indexed solr which fixed the problem.

**Comment by gjlawran** [comment]
Needs to be validated in production with 1.4.0
