### ISSUE TITLE
Fork geoview repo - update with openlayers - make pull request - and sync/clone

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#95]
Linked to CITZEDC-814

**Comment by Mbrownshoes** [comment]
Are we still doing this or have we decided to go a different route?

**Comment by gjlawran** [comment]
OK - Hwy 3 will update vagrant - will drop the fork for the CKAN core version.

**Comment by jrods** [comment]
@gjlawran @Mbrownshoes @ll911 a new version of the core ext has been tagged, v0.0.11 and is available on pypi now. `pip install ckanext-geoview` should replace the old cmd to install the extension in delivery.

**Comment by ll911** [comment]
Rebuild now
