### ISSUE TITLE
Add a spinner  that indicates to a user progress is underway - lock edit fields

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#99]
When users are updating records or uploading resources they need to be aware of the time needed by the application to complete the task.  Sometimes this leads to data corruption. 

An indicator such as  spin.js may reduce the chance that they will attempt to update when a transaction is in progress.

As a secondary investigate locking fields.

**Comment by Mbrownshoes** [comment]
I've had two cases in the past couple of days where editors have created two of the same resource due to double clicking 'add data'. They did not know it has already been added. A spinner would solve that.

**Comment by jrods** [comment]
There's one little quirk, it's mainly there to fix an issue only in Firefox, but the spinner and element that covers the form disappears just before the next page displays. This is to prevent the spinner and element covering the form if the user happens to click on the browser back button. It's only a visual issue.

**Comment by Mbrownshoes** [comment]
The spinner isn't showing on the current window.
<img width="1440" alt="screen shot 2016-07-26 at 3 49 08 pm" src="https://cloud.githubusercontent.com/assets/3362533/17157969/fd12dd3a-5347-11e6-9165-136eea7bcaaa.png">

can we remove the large grey background and just have a standalone spinner, i.e.
http://jsfiddle.net/5CQJP/1/

**Comment by jrods** [comment]
I moved the spinner to the bottom of the form rather than the top.

As for the grey background, this indicates that form is disabled and prevents the user from editing anything in the form once the add resource button has been clicked.

But I can remove the grey background if you want.

**Comment by Mbrownshoes** [comment]
Looks good to me.
